"""fem_utils.py.

Core FEM utilities and data container.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import jax
import jax.numpy as jnp

jax.config.update("jax_enable_x64", True)

Array = jnp.ndarray


@dataclass(frozen=True)
class TetGeom:
    """Container for tetrahedral mesh geometry data used in FEM kernels.

    Attributes:
        conn (Array): Topology connectivity (E, 4) of node indices.
        volume (Array): Element volumes (E,).
        mat_id (Array): Material identifiers (E,).
        grad_phi (Array | None): Precomputed shape function gradients (E, 4, 3).
        JinvT (Array | None): Precomputed inverse Jacobian transpose (E, 3, 3).
        x_nodes (Array | None): Node coordinates (N, 3).
    """

    conn: Array
    volume: Array
    mat_id: Array
    grad_phi: Array | None = None
    JinvT: Array | None = None
    x_nodes: Array | None = None


def compute_node_volumes(geom: TetGeom) -> Array:
    """Compute the lumped volume at each node using CPU NumPy.

    The nodal volume is defined as the sum of (Ve/4) for all tetrahedra
    connected to that node.

    Args:
        geom (TetGeom): The geometry container.

    Returns:
        Array: Lumped volume at each node (N,).
    """
    import numpy as np

    N = geom.x_nodes.shape[0] if geom.x_nodes is not None else int(np.max(geom.conn)) + 1

    conn_np = np.asarray(geom.conn)
    vol_np = np.asarray(geom.volume)

    weights = np.repeat(vol_np / 4.0, 4)
    vols = np.bincount(conn_np.flatten(), weights=weights, minlength=N)

    return vols


def _B_split_from_JinvT(JinvT_c: Array, dtype: Any) -> tuple[Array, Array, Array]:
    """Compute shape function gradients B from inverse Jacobian transpose in split components.

    Args:
        JinvT_c (Array): Inverse Jacobian transpose (chunk_elems, 3, 3).
        dtype (jnp.dtype): Target data type.

    Returns:
        tuple[Array, Array, Array]: (Bx, By, Bz) shape function gradients (chunk_elems, 4) each.
    """
    J_cast = JinvT_c.astype(dtype)

    # x-components
    bx1 = J_cast[:, 0, 0]
    bx2 = J_cast[:, 0, 1]
    bx3 = J_cast[:, 0, 2]
    bx0 = -(bx1 + bx2 + bx3)
    bx = jnp.stack([bx0, bx1, bx2, bx3], axis=1)

    # y-components
    by1 = J_cast[:, 1, 0]
    by2 = J_cast[:, 1, 1]
    by3 = J_cast[:, 1, 2]
    by0 = -(by1 + by2 + by3)
    by = jnp.stack([by0, by1, by2, by3], axis=1)

    # z-components
    bz1 = J_cast[:, 2, 0]
    bz2 = J_cast[:, 2, 1]
    bz3 = J_cast[:, 2, 2]
    bz0 = -(bz1 + bz2 + bz3)
    bz = jnp.stack([bz0, bz1, bz2, bz3], axis=1)

    return bx, by, bz


def _compute_JinvT_from_coords(x_e: Array, dtype: Any) -> Array:
    """Compute inverse Jacobian transpose from tetrahedron node coordinates.

    Args:
        x_e (Array): Node coordinates for the chunk (chunk_elems, 4, 3).
        dtype (jnp.dtype): Target data type.

    Returns:
        Array: Inverse Jacobian transpose (chunk_elems, 3, 3).
    """
    x0 = x_e[:, 0, :]
    J = jnp.stack([x_e[:, 1, :] - x0, x_e[:, 2, :] - x0, x_e[:, 3, :] - x0], axis=2)
    invJ = jnp.linalg.inv(J.astype(dtype))
    return jnp.swapaxes(invJ, 1, 2)
