[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "tommos"
version = "0.1.0"
description = "Matrix-free micromagnetic simulations with JAX"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "MaMMoS-project" },
]
dependencies = [
  "jax",
  "matplotlib",
  "meshpy",
  "numpy",
  "pyamg",
  "scipy",
]

[project.optional-dependencies]
io = [
  "mammos-entity",
  "meshio",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["tommos*"]
namespaces = false

[tool.ruff]
target-version = "py311"
exclude = [
  "dev",
]
line-length = 120
[tool.ruff.lint]
select = [
  "B",   # flake8-bugbear
  "D",   # pydocstyle
  "E",   # pycodestyle
  "F",   # Pyflakes
  "I",   # isort
  "SIM", # flake8-simplify
  "UP",  # pyupgrade
]
isort.known-local-folder = [ "tommos" ]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["B018"]  # "Found useless expression. Either assign it to a variable or remove it."; false positives when using implicit __repr__ in the notebook
"tests/*" = ["D100", "D103"]  # do not enforce docstrings in tests
