[build-system]
requires = [
  "scikit-build-core>=0.12",
  "mkl-devel>=2026.0,<2027; sys_platform == 'linux' and platform_machine == 'x86_64'",
]
build-backend = "scikit_build_core.build"

[project]
name = "tommos"
version = "0.1.0"
description = "Matrix-free micromagnetic simulations with JAX"
readme = "README.md"
requires-python = ">=3.11"
authors = [
  { name = "MaMMoS-project" },
]
dependencies = [
  "jax",
  "matplotlib",
  "meshpy",
  "mkl>=2026.0,<2027; sys_platform == \"linux\" and platform_machine == \"x86_64\"",
  "numpy",
  "pyamg",
  "scipy",
  "sparse-dot-mkl>=0.9.10; sys_platform == \"linux\" and platform_machine == \"x86_64\"",
]

[project.optional-dependencies]
io = [
  "mammos-entity",
  "meshio",
]

[tool.scikit-build]
minimum-version = "build-system.requires"
cmake.source-dir = "src/cpp"
wheel.packages = ["src/tommos"]
wheel.py-api = "py3"
sdist.include = ["src/cpp/CMakeLists.txt", "src/cpp/cpp_mkl_minimizer.cpp", "src/cpp/find_mkl.py"]

[[tool.scikit-build.overrides]]
if.platform-system = "^darwin"
wheel.cmake = false
wheel.platlib = false

[tool.ruff]
target-version = "py311"
exclude = [
  "dev",
]
line-length = 120
[tool.ruff.lint]
select = [
  "B",   # flake8-bugbear
  "D",   # pydocstyle
  "E",   # pycodestyle
  "F",   # Pyflakes
  "I",   # isort
  "SIM", # flake8-simplify
  "UP",  # pyupgrade
]
isort.known-local-folder = [ "tommos" ]
pydocstyle.convention = "google"

[tool.ruff.lint.per-file-ignores]
"*.ipynb" = ["B018"]  # "Found useless expression. Either assign it to a variable or remove it."; false positives when using implicit __repr__ in the notebook
"tests/*" = ["D100", "D103"]  # do not enforce docstrings in tests
