"""aggregation_utils.py

CPU-side: build aggregates for coarse correction using uniform spatial binning.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

import numpy as np


def build_aggregates_by_binning(x_nodes: np.ndarray, k_target: int = 256):
    x = np.asarray(x_nodes, dtype=np.float64)
    if x.ndim != 2 or x.shape[1] != 3:
        raise ValueError('x_nodes must be (N,3)')

    b = int(np.round(float(k_target) ** (1.0 / 3.0)))
    b = max(b, 1)
    bins = np.array([b, b, b], dtype=np.int64)

    xmin = x.min(axis=0)
    xmax = x.max(axis=0)
    span = np.maximum(xmax - xmin, 1e-15)

    u = (x - xmin) / span
    ijk = np.floor(u * bins).astype(np.int64)
    ijk = np.clip(ijk, 0, bins - 1)

    raw = ijk[:, 0] + bins[0] * (ijk[:, 1] + bins[1] * ijk[:, 2])
    uniq, inv = np.unique(raw, return_inverse=True)
    agg_id = inv.astype(np.int32)
    k = int(uniq.size)

    counts = np.bincount(agg_id, minlength=k).astype(np.int64)
    inv_sqrt_counts = (1.0 / np.sqrt(np.maximum(counts, 1))).astype(np.float64)

    return agg_id, inv_sqrt_counts, k
