"""curvilinear_bb_minimizer.py

Curvilinear + BB minimiser. Uses PCG+Jacobi+warm start for the Poisson solve.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Callable, Dict, Literal, Optional
import time

import jax
import jax.numpy as jnp
from jax import lax

from fem_utils import TetGeom
from energy_kernels import make_energy_kernels
from poisson_solve import make_solve_U

Array = jnp.ndarray
GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']


def cayley_update(m: Array, H: Array, tau: Array) -> Array:
    k = 0.5 * tau * H
    k2 = jnp.sum(k * k, axis=1, keepdims=True)
    denom = 1.0 + k2
    km = jnp.cross(k, m)
    kdotm = jnp.sum(k * m, axis=1, keepdims=True)
    m_new = ((1.0 - k2) * m + 2.0 * km + 2.0 * kdotm * k) / denom
    return m_new / jnp.linalg.norm(m_new, axis=1, keepdims=True)


def tangent_grad(m: Array, g_raw: Array) -> Array:
    return g_raw - jnp.sum(m * g_raw, axis=1, keepdims=True) * m


def armijo_weak_line_search(
    m: Array,
    pg: float,
    H_for_update: Array,
    E0: float,
    U_base: Array,
    solve_U: Callable[[Array, Array, Optional[float]], Array],
    energy_only: Callable[[Array, Array, Array], Array],
    B_ext: Array,
    phi_tol: float,
    *,
    eta1: float = 0.1,
    eta2: float = 0.1,
    C: float = 2.0,
    c: float = 0.5,
    s0: float = 1.0,
    max_evals: int = 15,
) -> float:

    if pg >= 0:
        return 0.0

    def D(s: float) -> float:
        m_trial = cayley_update(m, H_for_update, jnp.asarray(s, m.dtype))
        U_trial = solve_U(m_trial, U_base, phi_tol)
        E_trial = float(energy_only(m_trial, U_trial, B_ext))
        val = (E_trial - float(E0)) / (float(s) * pg + 1e-30)
        return float(val)

    s = float(s0)
    s_min = 0.0
    
    it_exp = 0
    for _ in range(max_evals):
        d = D(s)
        if abs(1.0 - d) < eta2:
            s_min = s
            s = C * s
            it_exp += 1
        else:
            break

    it_con = 0
    final_d = 0.0
    for _ in range(max_evals):
        d = D(s)
        final_d = d
        if d >= eta1:
            return s
        s = s_min + c * (s - s_min)
        it_con += 1

    return s


@jax.tree_util.register_pytree_node_class
@dataclass
class MinimState:
    m: Array
    U_prev: Array
    g_prev: Array
    m_prev: Array
    tau: Array
    it: Array

    def tree_flatten(self):
        children = (self.m, self.U_prev, self.g_prev, self.m_prev, self.tau, self.it)
        aux_data = None
        return (children, aux_data)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)


def make_minimizer(
    geom: TetGeom,
    A_lookup: Array,
    K1_lookup: Array,
    Js_lookup: Array,
    k_easy_lookup: Array,
    V_mag: float,
    node_volumes: Array,
    *,
    precond_type: str = 'jacobi',
    order: int = 3,
    chunk_elems: int = 200_000,
    energy_assembly: str = 'scatter',
    cg_maxiter: int = 400,
    cg_tol: float = 1e-8,
    poisson_reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    boundary_mask: Optional[Array] = None,
):
    # inv_V_rel: node-wise scaling to go from (total_energy_grad / V_mag)
    # to (local_energy_density_grad). This is a diagonal preconditioner.
    inv_V_rel = jnp.where(node_volumes > 0, V_mag / node_volumes, 0.0)[:, None]

    energy_and_grad, energy_only, _ = make_energy_kernels(
        geom,
        A_lookup=A_lookup,
        K1_lookup=K1_lookup,
        Js_lookup=Js_lookup,
        k_easy_lookup=k_easy_lookup,
        V_mag=V_mag,
        chunk_elems=chunk_elems,
        assembly=energy_assembly,
        grad_backend=grad_backend,
    )

    solve_U = make_solve_U(
        geom,
        Js_lookup,
        precond_type=precond_type,
        order=order,
        chunk_elems=chunk_elems,
        cg_maxiter=cg_maxiter,
        cg_tol=cg_tol,
        poisson_reg=poisson_reg,
        grad_backend=grad_backend,
        enforce_zero_mean=True,
        boundary_mask=boundary_mask,
        assembly=energy_assembly,
    )

    def jax_armijo_line_search(
        m: Array,
        pg: Array,
        H_for_update: Array,
        E0: Array,
        U_base: Array,
        B_ext: Array,
        phi_tol: Array,
        eta1: float,
        eta2: float,
        C: float,
        c: float,
        s0: float,
        max_evals: int,
    ) -> Array:
        # pg is expected to be < 0 for descent
        
        def D(s):
            m_trial = cayley_update(m, H_for_update, s)
            U_trial = solve_U(m_trial, U_base, phi_tol)
            E_trial = energy_only(m_trial, U_trial, B_ext)
            return (E_trial - E0) / (s * pg + 1e-30)

        # Expansion phase
        def exp_cond(state):
            s, s_min, it, done = state
            return (it < max_evals) & (~done)

        def exp_body(state):
            s, s_min, it, done = state
            d = D(s)
            stop = jnp.abs(1.0 - d) >= eta2
            s_next = jnp.where(stop, s, C * s)
            s_min_next = jnp.where(stop, s_min, s)
            return (s_next, s_min_next, it + 1, stop)

        s_start = jnp.asarray(s0, dtype=m.dtype)
        init_exp = (s_start, jnp.zeros_like(s_start), jnp.int32(0), jnp.array(False))
        s_exp, s_min_exp, _, _ = lax.while_loop(exp_cond, exp_body, init_exp)

        # Contraction phase
        def con_cond(state):
            s, it, done = state
            return (it < max_evals) & (~done)

        def con_body(state):
            s, it, done = state
            d = D(s)
            stop = d >= eta1
            s_next = jnp.where(stop, s, s_min_exp + c * (s - s_min_exp))
            return (s_next, it + 1, stop)

        init_con = (s_exp, jnp.int32(0), jnp.array(False))
        s_final, _, _ = lax.while_loop(con_cond, con_body, init_con)
        
        return jnp.where(pg >= 0, 0.0, s_final)

    jit_ls = jax.jit(jax_armijo_line_search, static_argnums=(7, 8, 9, 10, 11, 12))

    def _bb_step(state: MinimState, B_ext: Array, tau_min: float, tau_max: float, cg_tol_base: float):
        m = state.m
        U = solve_U(m, state.U_prev, cg_tol_base)
        E, g_raw = energy_and_grad(m, U, B_ext)
        
        # Apply preconditioning: g_prec is approximately the local energy density gradient
        g_prec = g_raw * inv_V_rel
        g_tan = tangent_grad(m, g_prec)
        gnorm = jnp.sqrt(jnp.vdot(g_tan, g_tan))

        def compute_tau(_):
            s = (m - state.m_prev).reshape(-1)
            y = (g_tan - state.g_prev).reshape(-1)
            sty = jnp.vdot(s, y)
            sts = jnp.vdot(s, s)
            yty = jnp.vdot(y, y)
            eps = jnp.asarray(1e-30, dtype=m.dtype)
            tau1 = sts / (sty + eps)
            tau2 = sty / (yty + eps)
            tau = jnp.where((state.it % 2) == 1, tau1, tau2)
            tau = jnp.where(sty > 0, tau, state.tau)
            return jnp.clip(tau, tau_min, tau_max)

        tau = lax.cond(state.it > 0, compute_tau, lambda _: jnp.clip(state.tau, tau_min, tau_max), operand=None)

        H = -jnp.cross(m, g_prec)
        m_new = cayley_update(m, H, tau)

        new_state = MinimState(m=m_new, U_prev=U, g_prev=g_tan, m_prev=m, tau=tau, it=state.it + jnp.int32(1))
        return new_state, E, gnorm

    bb_step = jax.jit(_bb_step, donate_argnums=(0,))

    def minimize(
        m0: Array,
        B_ext: Array,
        *,
        U0: Optional[Array] = None,
        gamma: int = 5,
        max_iter: int = 200,
        tau_f: float = 1e-6,
        eps_a: float = 1e-12,
        tau0: float = 1e-2,
        tau_min: float = 1e-6,
        tau_max: float = 1.0,
        ls_eta1: float = 0.1,
        ls_eta2: float = 0.1,
        ls_C: float = 2.0,
        ls_c: float = 0.5,
        ls_s0: float = 1.0,
        ls_max_evals: int = 15,
        verbose: bool = True,
    ):
        m = jnp.asarray(m0, dtype=jnp.float64)
        m = m / jnp.linalg.norm(m, axis=1, keepdims=True)
        B_ext = jnp.asarray(B_ext, dtype=jnp.float64)

        # Derived Poisson base tolerance: must satisfy all stopping criteria
        cg_tol_base = float(min(cg_tol, tau_f * 0.1, eps_a * 0.1))

        # Perform initial tight solve using provided U0 or zeros
        if U0 is None:
            U0 = jnp.zeros((m.shape[0],), dtype=jnp.float64)
        U = solve_U(m, U0, cg_tol_base)
        E_prev, g_raw = energy_and_grad(m, U, B_ext)
        g_prec = g_raw * inv_V_rel
        g_tan = tangent_grad(m, g_prec)
        gnorm = float(jnp.sqrt(jnp.vdot(g_tan, g_tan)))

        state = MinimState(m=m, U_prev=U, g_prev=g_tan, m_prev=m, tau=jnp.asarray(tau0, jnp.float64), it=jnp.int32(0))
        history = []

        t_ls_total = 0.0
        t_bb_total = 0.0

        for k in range(gamma):
            start_ls = time.time()
            U = solve_U(state.m, state.U_prev, cg_tol_base)
            E, g_raw = energy_and_grad(state.m, U, B_ext)
            g_prec = g_raw * inv_V_rel
            g_tan = tangent_grad(state.m, g_prec)
            pg = float(-jnp.vdot(g_raw, g_tan))
            
            # Infinity norms for convergence check
            gnorm_inf = float(jnp.max(jnp.abs(g_tan)))
            m_norm_inf = 1.0 # Nodes are normalized to unit length
            diff_m_norm_inf = float(jnp.max(jnp.abs(state.m - state.m_prev)))
            
            # U1, U2, U3, U4 criteria
            u1 = (E_prev - E) < tau_f * (1.0 + abs(E))
            u2 = diff_m_norm_inf < jnp.sqrt(tau_f) * (1.0 + m_norm_inf)
            u3 = gnorm_inf <= (tau_f**(1/3.0)) * (1.0 + abs(E))
            u4 = gnorm_inf < eps_a
            
            converged = (u1 and u2 and u3) or u4
            
            history.append({"E": float(E), "gnorm": gnorm_inf, "phase": 0.0})

            if verbose:
                print(f"[LS {k:03d}] E={float(E):.6e}  |g|_inf={gnorm_inf:.3e}")
            if converged:
                t_ls_total += time.time() - start_ls
                if verbose: print(f"  Line Search Total Time: {t_ls_total:.3f}s")
                return state.m, U, {"E": float(E), "gnorm": gnorm_inf, "iters": float(k), "phase": 0.0, "history": history, "t_ls": t_ls_total, "t_bb": t_bb_total}

            H = -jnp.cross(state.m, g_prec)
            
            # Using the JIT line search to avoid CPU sync
            tau = jit_ls(
                state.m, jnp.asarray(pg), H, jnp.asarray(E),
                U, B_ext, jnp.asarray(cg_tol_base),
                ls_eta1, ls_eta2, ls_C, ls_c, ls_s0, ls_max_evals
            )

            m_new = cayley_update(state.m, H, tau)
            E_prev = E
            state = replace(state, m=m_new, m_prev=state.m, g_prev=g_tan, tau=tau, it=state.it + jnp.int32(1), U_prev=U)
            gnorm = float(jnp.sqrt(jnp.vdot(g_tan, g_tan)))
            t_ls_total += time.time() - start_ls

        if verbose: print(f"  Line Search Total Time: {t_ls_total:.3f}s")

        for k in range(gamma, max_iter):
            start_bb = time.time()
            state, E, gnorm = bb_step(state, B_ext, tau_min, tau_max, cg_tol_base)
            # bb_step returns 2-norm, we need inf-norm for consistent criteria
            gnorm_inf = float(jnp.max(jnp.abs(state.g_prev))) # state.g_prev is the tangent gradient of the new state m
            diff_m_norm_inf = float(jnp.max(jnp.abs(state.m - state.m_prev)))
            
            u1 = (E_prev - E) < tau_f * (1.0 + abs(E))
            u2 = diff_m_norm_inf < jnp.sqrt(tau_f) * (1.0 + m_norm_inf)
            u3 = gnorm_inf <= (tau_f**(1/3.0)) * (1.0 + abs(E))
            u4 = gnorm_inf < eps_a
            
            converged = (u1 and u2 and u3) or u4
            
            history.append({"E": float(E), "gnorm": gnorm_inf, "phase": 1.0})

            if verbose and (k % 10 == 0 or converged):
                print(f"[BB {k:03d}] E={float(E):.6e}  |g|_inf={gnorm_inf:.3e}  tau={float(state.tau):.3e}")
            
            t_bb_total += time.time() - start_bb
            if converged:
                U = solve_U(state.m, state.U_prev, cg_tol_base)
                if verbose: print(f"  BB Phase Total Time: {t_bb_total:.3f}s")
                return state.m, U, {"E": float(E), "gnorm": gnorm_inf, "iters": float(k + 1), "phase": 1.0, "history": history, "t_ls": t_ls_total, "t_bb": t_bb_total}
            
            E_prev = E

        U = solve_U(state.m, state.U_prev, cg_tol_base)
        E_end = float(energy_only(state.m, U, B_ext))
        gnorm_inf = float(jnp.max(jnp.abs(state.g_prev)))
        if verbose: print(f"  BB Phase Total Time: {t_bb_total:.3f}s")
        return state.m, U, {"E": E_end, "gnorm": gnorm_inf, "iters": float(max_iter), "phase": 2.0, "history": history, "t_ls": t_ls_total, "t_bb": t_bb_total}


    return minimize
