"""curvilinear_bb_minimizer.py.

Curvilinear + Barzilai-Borwein (BB) minimizer for micromagnetics.
Ensures unit-length magnetization constraints via Cayley transforms and
utilizes PCG with warm starts for the Poisson potential.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

import time
from collections.abc import Callable
from dataclasses import dataclass
from typing import Any, Literal

import jax
import jax.numpy as jnp
from jax import lax

from energy_kernels import make_energy_kernels
from fem_utils import TetGeom

Array = jnp.ndarray
GradBackend = Literal["stored_grad_phi", "stored_JinvT", "on_the_fly"]


def cayley_update(m: Array, H: Array, tau: Array) -> Array:
    """Perform a unit-length preserving magnetization update using a Cayley transform.

    Choice: The Cayley transform maps a skew-symmetric torque H directly to a
    rotation, ensuring that m_new has exactly the same norm as m (unity).
    This is more robust than a simple gradient step followed by re-normalization,
    especially for large step sizes tau.

    Args:
        m (Array): Current unit magnetization vectors (N, 3).
        H (Array): Search direction or torque field (N, 3).
        tau (Array): Step size.

    Returns:
        Array: Updated unit magnetization vectors (N, 3).
    """
    k = 0.5 * tau * H
    k2 = jnp.sum(k * k, axis=1, keepdims=True)
    denom = 1.0 + k2
    km = jnp.cross(k, m)
    kdotm = jnp.sum(k * m, axis=1, keepdims=True)
    m_new = ((1.0 - k2) * m + 2.0 * km + 2.0 * kdotm * k) / denom
    return m_new / jnp.linalg.norm(m_new, axis=1, keepdims=True)


def tangent_grad(m: Array, g_raw: Array) -> Array:
    """Project a raw gradient onto the tangent space of the unit sphere.

    Args:
        m (Array): Unit magnetization vectors (N, 3).
        g_raw (Array): Raw energy gradient (N, 3).

    Returns:
        Array: Tangent gradient vectors (N, 3).
    """
    return g_raw - jnp.sum(m * g_raw, axis=1, keepdims=True) * m


@jax.tree_util.register_pytree_node_class
@dataclass
class MinimState:
    """State container for the minimization process.

    Attributes:
        m (Array): Current unit magnetization.
        U_prev (Array): Current scalar potential.
        g_prev (Array): Tangent gradient from the previous step.
        m_prev (Array): Magnetization from the previous step.
        tau (Array): Current step size.
        it (Array): Iteration counter.
        E_prev (Array): Energy from the previous step.
        converged (Array): Boolean flag indicating if convergence was reached.
    """

    m: Array
    U_prev: Array
    g_prev: Array
    m_prev: Array
    tau: Array
    it: Array
    E_prev: Array
    converged: Array

    def tree_flatten(
        self,
    ) -> tuple[tuple[Array, Array, Array, Array, Array, Array, Array, Array], Any]:
        """Flatten the state for JAX.

        Returns:
            tuple: (children, aux_data).
        """
        children = (
            self.m,
            self.U_prev,
            self.g_prev,
            self.m_prev,
            self.tau,
            self.it,
            self.E_prev,
            self.converged,
        )
        aux_data = None
        return (children, aux_data)

    @classmethod
    def tree_unflatten(
        cls, aux_data: Any, children: tuple[Array, Array, Array, Array, Array, Array, Array, Array]
    ) -> MinimState:
        """Unflatten the state for JAX.

        Args:
            aux_data: Auxiliary data.
            children: Flattened components.

        Returns:
            MinimState: The unflattened state.
        """
        return cls(*children)


def make_minimizer(
    geom: TetGeom,
    A_lookup: Array,
    K1_lookup: Array,
    Js_lookup: Array,
    k_easy_lookup: Array,
    V_mag: float,
    node_volumes: Array,
    M_nodal: Array,
    solve_U: Callable[[Array, Array, float], Array],
    cg_tol: float,
    *,
    B_bias: Array | None = None,
    chunk_elems: int = 200_000,
    energy_assembly: str = "scatter",
    grad_backend: GradBackend = "stored_grad_phi",
) -> Callable[..., tuple[Array, Array, dict[str, Any]]]:
    """Create a high-level micromagnetic minimizer.

    Args:
        geom (TetGeom): Geometry container.
        A_lookup (Array): Exchange constants.
        K1_lookup (Array): Anisotropy constants.
        Js_lookup (Array): Saturation polarization.
        k_easy_lookup (Array): Easy axis vectors.
        V_mag (float): Magnetic volume.
        node_volumes (Array): Total nodal volumes.
        M_nodal (Array): Nodal magnetic moments.
        solve_U (Callable): Pre-built Poisson solver function.
        cg_tol (float): Poisson solver tolerance.
        B_bias (Array, optional): Per-node bias field for mode initialization.
        chunk_elems (int, optional): loop chunk size. Defaults to 200_000.
        energy_assembly (str, optional): 'scatter' or 'segment_sum'.
            Defaults to 'scatter'.
        grad_backend (GradBackend, optional): Strategy for gradients.
            Defaults to 'stored_grad_phi'.

    Returns:
        Callable: minimize(m0, B_ext, **kwargs) -> (m_final, U_final, info_dict).
    """
    # inv_M_rel: node-wise scaling to go from (total_energy_grad / V_mag)
    # to (local_energy_density_grad / Js). This is a physical preconditioner.
    inv_M_rel = jnp.where(M_nodal > 1e-20, V_mag / M_nodal, 0.0)[:, None]

    energy_and_grad, energy_only, _ = make_energy_kernels(
        geom,
        A_lookup=A_lookup,
        K1_lookup=K1_lookup,
        Js_lookup=Js_lookup,
        k_easy_lookup=k_easy_lookup,
        V_mag=V_mag,
        M_nodal=M_nodal,
        B_bias=B_bias,
        chunk_elems=chunk_elems,
        assembly=energy_assembly,
        grad_backend=grad_backend,
    )

    def jax_armijo_line_search(
        m: Array,
        pg: Array,
        H_for_update: Array,
        E0: Array,
        U_base: Array,
        B_ext: Array,
        phi_tol: Array,
        eta1: float,
        eta2: float,
        C: float,
        c: float,
        s0: Array,
        max_evals: int,
    ) -> Array:
        """Perform a JAX-native Armijo line search on the curvilinear path.

        Args:
            m (Array): current magnetization.
            pg (Array): projected gradient.
            H_for_update (Array): update torque.
            E0 (Array): current energy.
            U_base (Array): current potential.
            B_ext (Array): external field.
            phi_tol (Array): Poisson tolerance.
            eta1 (float): Sufficient decrease parameter.
            eta2 (float): Expansion parameter.
            C (float): Expansion factor.
            c (float): Contraction factor.
            s0 (Array): Initial step size guess.
            max_evals (int): Maximum evaluations.

        Returns:
            Array: Step size tau.
        """

        def D(s: Array) -> Array:
            m_trial = cayley_update(m, H_for_update, s)
            U_trial = solve_U(m_trial, U_base, phi_tol)
            E_trial = energy_only(m_trial, U_trial, B_ext)
            return (E_trial - E0) / (s * pg + 1e-30)

        # Expansion phase
        def exp_cond(state: tuple[Array, Array, jnp.int32, bool]) -> bool:
            s, s_min, it, done = state
            return (it < max_evals) & (~done)

        def exp_body(
            state: tuple[Array, Array, jnp.int32, bool],
        ) -> tuple[Array, Array, jnp.int32, bool]:
            s, s_min, it, done = state
            d = D(s)
            stop = jnp.abs(1.0 - d) >= eta2
            s_next = jnp.where(stop, s, C * s)
            s_min_next = jnp.where(stop, s_min, s)
            return (s_next, s_min_next, it + 1, stop)

        s_start = jnp.asarray(s0, dtype=m.dtype)
        init_exp = (s_start, jnp.zeros_like(s_start), jnp.int32(0), jnp.array(False))
        s_exp, s_min_exp, _, _ = lax.while_loop(exp_cond, exp_body, init_exp)

        # Contraction phase
        def con_cond(state: tuple[Array, jnp.int32, bool]) -> bool:
            s, it, done = state
            return (it < max_evals) & (~done)

        def con_body(
            state: tuple[Array, jnp.int32, bool],
        ) -> tuple[Array, jnp.int32, bool]:
            s, it, done = state
            d = D(s)
            stop = d >= eta1
            s_next = jnp.where(stop, s, s_min_exp + c * (s - s_min_exp))
            return (s_next, it + 1, stop)

        init_con = (s_exp, jnp.int32(0), jnp.array(False))
        s_final, _, _ = lax.while_loop(con_cond, con_body, init_con)

        return jnp.where(pg >= 0, 0.0, s_final)

    jit_ls = jax.jit(jax_armijo_line_search)

    def minim_step(
        state: MinimState,
        B_ext: Array,
        gamma: int,
        tau_f: float,
        eps_a: float,
        tau0: float,
        tau_min: float,
        tau_max: float,
        ls_eta1: float,
        ls_eta2: float,
        ls_C: float,
        ls_c: float,
        ls_s0: float,
        ls_max_evals: int,
        cg_tol_base: float,
    ) -> MinimState:
        """Take one minimization step (Initial Line Search or pure BB)."""
        m = state.m
        U = solve_U(m, state.U_prev, cg_tol_base)
        E, g_raw = energy_and_grad(m, U, B_ext)

        # Preconditioning & tangent projection
        g_prec = g_raw * inv_M_rel
        g_tan = tangent_grad(m, g_prec)
        gnorm_inf = jnp.max(jnp.abs(g_tan))
        pg = -jnp.vdot(g_raw, g_tan)

        # 1. Compute BB spectral estimate
        s = (m - state.m_prev).reshape(-1)
        y = (g_tan - state.g_prev).reshape(-1)
        sty = jnp.vdot(s, y)
        sts = jnp.vdot(s, s)
        yty = jnp.vdot(y, y)
        eps = jnp.asarray(1e-30, dtype=m.dtype)

        tau1 = sts / (sty + eps)
        tau2 = sty / (yty + eps)
        tau_spec = jnp.where((state.it % 2) == 0, tau1, tau2)

        # 2. Decision Logic
        # Phase A: Initial steps (it < gamma) -> Always Line Search
        # Phase B: Main steps (it >= gamma) -> BB if curvature is positive, else Line Search
        is_initial = state.it < gamma
        use_pure_bb = (~is_initial) & (sty > 1e-12)

        H = -jnp.cross(m, g_prec)

        # Initial guess for line search if we fall back
        tau_init = jnp.where(state.it > 0, state.tau, jnp.asarray(tau0, m.dtype))

        # Select step size (Hybrid logic)
        tau = lax.cond(
            use_pure_bb,
            lambda _: jnp.clip(tau_spec, tau_min, tau_max),
            lambda _: jit_ls(
                m,
                pg,
                H,
                E,
                U,
                B_ext,
                jnp.asarray(cg_tol_base, m.dtype),
                ls_eta1,
                ls_eta2,
                ls_C,
                ls_c,
                tau_init,
                ls_max_evals,
            ),
            operand=None,
        )

        m_new = cayley_update(m, H, tau)

        # 3. Convergence Check
        m_norm_inf = 1.0
        diff_m_norm_inf = jnp.max(jnp.abs(m_new - m))

        u1 = (state.E_prev - E) < tau_f * (1.0 + jnp.abs(E))
        u2 = diff_m_norm_inf < jnp.sqrt(tau_f) * (1.0 + m_norm_inf)
        u3 = gnorm_inf <= (tau_f ** (1 / 3.0)) * (1.0 + jnp.abs(E))
        u4 = gnorm_inf < eps_a

        is_converged = jnp.where(state.it > 0, (u1 & u2 & u3) | u4, False)

        return MinimState(
            m=m_new,
            U_prev=U,
            g_prev=g_tan,
            m_prev=m,
            tau=tau,
            it=state.it + jnp.int32(1),
            E_prev=E,
            converged=is_converged,
        )

    # Internal kernel for JITed loop
    @jax.jit
    def _minim_kernel(
        initial_state: MinimState,
        B_ext: Array,
        h_jax: Array,
        gamma: int,
        max_iter: int,
        tau_f: float,
        eps_a: float,
        tau0: float,
        tau_min: float,
        tau_max: float,
        ls_eta1: float,
        ls_eta2: float,
        ls_C: float,
        ls_c: float,
        ls_s0: float,
        ls_max_evals: int,
        cg_tol_base: float,
        mfinal: float,
    ) -> MinimState:
        def cond_fun(state: MinimState) -> bool:
            it_ok = state.it < max_iter
            conv_ok = ~state.converged
            # mfinal logic inside JIT (mfinal=-1e30 means disabled)
            m_par = jnp.sum(jnp.dot(state.m, h_jax) * M_nodal) / V_mag
            mfinal_ok = m_par > mfinal
            return it_ok & conv_ok & mfinal_ok

        def body_fun(state: MinimState) -> MinimState:
            return minim_step(
                state,
                B_ext,
                gamma,
                tau_f,
                eps_a,
                tau0,
                tau_min,
                tau_max,
                ls_eta1,
                ls_eta2,
                ls_C,
                ls_c,
                ls_s0,
                ls_max_evals,
                cg_tol_base,
            )

        return jax.lax.while_loop(cond_fun, body_fun, initial_state)

    def minimize(
        m0: Array,
        B_ext: Array,
        *,
        U0: Array | None = None,
        gamma: int = 5,
        max_iter: int = 200,
        tau_f: float = 1e-6,
        eps_a: float = 1e-10,
        tau0: float = 1e-2,
        tau_min: float = 1e-6,
        tau_max: float = 1.0,
        ls_eta1: float = 0.1,
        ls_eta2: float = 0.1,
        ls_C: float = 2.0,
        ls_c: float = 0.5,
        ls_s0: float = 1.0,
        ls_max_evals: int = 15,
        h: Array | None = None,
        mfinal: float | None = None,
        Js_ref: float = 1.0,
        verbose: bool = True,
    ) -> tuple[Array, Array, dict[str, Any]]:
        """Minimize the micromagnetic energy using BB and line search.

        Args:
            m0 (Array): Initial unit magnetization (N, 3).
            B_ext (Array): external field (3,).
            U0 (Array | None): initial scalar potential.
            gamma (int, optional): number of initial line-search steps.
            max_iter (int, optional): maximum iterations.
            tau_f (float): relative energy tolerance.
            eps_a (float): absolute tangent gradient tolerance.
            tau0 (float): initial step size guess.
            tau_min (float): minimum step size.
            tau_max (float): maximum step size.
            ls_eta1 (float): line search sufficient decrease parameter.
            ls_eta2 (float): line search expansion parameter.
            ls_C (float): line search expansion factor.
            ls_c (float): line search contraction factor.
            ls_s0 (float): line search initial step size.
            ls_max_evals (int): maximum line search evaluations.
            h (Array | None): magnetic field direction.
            mfinal (float | None): final magnetization threshold.
            Js_ref (float): SI scaling factor.
            verbose (bool): enable logging.

        Returns:
            tuple[Array, Array, dict[str, Any]]: (m_final, U_final, info).
        """
        m = jnp.asarray(m0, dtype=jnp.float64)
        m = m / jnp.linalg.norm(m, axis=1, keepdims=True)
        B_ext = jnp.asarray(B_ext, dtype=jnp.float64)

        if h is not None:
            h_jax = jnp.asarray(h, dtype=jnp.float64)
        else:
            # Fallback to B_ext direction if h not provided
            B_norm = jnp.linalg.norm(B_ext)
            h_jax = jnp.where(B_norm > 1e-20, B_ext / B_norm, jnp.array([0.0, 0.0, 1.0]))

        def get_m_par(m_current: Array) -> float:
            # Volume averaged m parallel to h
            return float(jnp.sum(jnp.dot(m_current, h_jax) * M_nodal) / V_mag)

        # Derived Poisson base tolerance: must satisfy all stopping criteria
        cg_tol_base = float(min(cg_tol, tau_f * 0.1, eps_a * 0.1))

        # Perform initial solve
        if U0 is None:
            U0 = jnp.zeros((m.shape[0],), dtype=jnp.float64)
        U = solve_U(m, U0, cg_tol_base)
        E_init, g_raw = energy_and_grad(m, U, B_ext)
        g_prec = g_raw * inv_M_rel
        g_tan = tangent_grad(m, g_prec)

        initial_state = MinimState(
            m=m,
            U_prev=U,
            g_prev=g_tan,
            m_prev=m,
            tau=jnp.asarray(tau0, jnp.float64),
            it=jnp.int32(0),
            E_prev=jnp.asarray(E_init + 1e6, jnp.float64),  # Force first step
            converged=jnp.array(False),
        )

        # Handle mfinal (None -> large negative number for JAX)
        mfinal_val = float(mfinal) if mfinal is not None else -1e30

        # Execute JITed kernel
        start_time = time.time()
        final_state = _minim_kernel(
            initial_state,
            B_ext,
            h_jax,
            gamma,
            max_iter,
            tau_f,
            eps_a,
            tau0,
            tau_min,
            tau_max,
            ls_eta1,
            ls_eta2,
            ls_C,
            ls_c,
            ls_s0,
            ls_max_evals,
            cg_tol_base,
            mfinal_val,
        )
        total_time = time.time() - start_time

        # Final Poisson solve for the potential (highest accuracy)
        U_final = solve_U(final_state.m, final_state.U_prev, cg_tol_base)
        E_final, _ = energy_and_grad(final_state.m, U_final, B_ext)
        gnorm_inf = float(jnp.max(jnp.abs(final_state.g_prev)))

        if verbose:
            mh_tesla = get_m_par(final_state.m) * Js_ref
            print(
                f"[Minim] it={int(final_state.it):03d}  E={float(E_final):.6e}  "
                f"|g|_inf={gnorm_inf:.3e}  mh={mh_tesla:+.4f} T  t={total_time:.3f}s"
            )

        return (
            final_state.m,
            U_final,
            {
                "E": float(E_final),
                "gnorm": gnorm_inf,
                "iters": float(final_state.it),
                "converged": bool(final_state.converged),
                "total_time": total_time,
            },
        )

    return minimize
