"""curvilinear_bb_minimizer.py

Curvilinear + BB minimiser. Uses PCG+Jacobi+warm start for the Poisson solve.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Callable, Dict, Literal, Optional

import jax
import jax.numpy as jnp
from jax import lax

from fem_utils import TetGeom
from energy_kernels import make_energy_kernels
from poisson_solve import make_solve_U

Array = jnp.ndarray
GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']


def cayley_update(m: Array, H: Array, tau: Array) -> Array:
    k = 0.5 * tau * H
    k2 = jnp.sum(k * k, axis=1, keepdims=True)
    denom = 1.0 + k2
    km = jnp.cross(k, m)
    kdotm = jnp.sum(k * m, axis=1, keepdims=True)
    m_new = ((1.0 - k2) * m + 2.0 * km + 2.0 * kdotm * k) / denom
    return m_new / jnp.linalg.norm(m_new, axis=1, keepdims=True)


def tangent_grad(m: Array, g_raw: Array) -> Array:
    return g_raw - jnp.sum(m * g_raw, axis=1, keepdims=True) * m


def armijo_weak_line_search(
    m: Array,
    g_tan: Array,
    H_for_update: Array,
    E0: float,
    U_base: Array,
    solve_U: Callable[[Array, Array], Array],
    energy_only: Callable[[Array, Array, Array], Array],
    B_ext: Array,
    *,
    eta1: float = 0.1,
    eta2: float = 0.1,
    C: float = 2.0,
    c: float = 0.5,
    s0: float = 1.0,
    max_evals: int = 15,
) -> float:

    pg = float(-jnp.vdot(g_tan, g_tan))
    if pg >= 0:
        return 0.0

    def D(s: float) -> float:
        m_trial = cayley_update(m, H_for_update, jnp.asarray(s, m.dtype))
        U_trial = solve_U(m_trial, U_base)
        E_trial = float(energy_only(m_trial, U_trial, B_ext))
        return (E_trial - float(E0)) / (s * pg + 1e-30)

    s = float(s0)
    s_min = 0.0

    for _ in range(max_evals):
        d = D(s)
        if abs(1.0 - d) < eta2:
            s_min = s
            s = C * s
        else:
            break

    for _ in range(max_evals):
        d = D(s)
        if d >= eta1:
            return s
        s = s_min + c * (s - s_min)

    return s


@dataclass
class MinimState:
    m: Array
    U_prev: Array
    g_prev: Array
    m_prev: Array
    tau: Array
    it: Array


def make_minimizer(
    geom: TetGeom,
    A_lookup: Array,
    K1_lookup: Array,
    Js_lookup: Array,
    k_easy_lookup: Array,
    V_mag: float,
    *,
    precond_type: str = 'jacobi',
    chunk_elems: int = 200_000,
    energy_assembly: str = 'scatter',
    cg_maxiter: int = 400,
    cg_tol: float = 1e-8,
    poisson_reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    boundary_mask: Optional[Array] = None,
):

    energy_and_grad, energy_only, _ = make_energy_kernels(
        geom,
        A_lookup=A_lookup,
        K1_lookup=K1_lookup,
        Js_lookup=Js_lookup,
        k_easy_lookup=k_easy_lookup,
        V_mag=V_mag,
        chunk_elems=chunk_elems,
        assembly=energy_assembly,
        grad_backend=grad_backend,
    )

    solve_U = make_solve_U(
        geom,
        Js_lookup,
        precond_type=precond_type,
        chunk_elems=chunk_elems,
        cg_maxiter=cg_maxiter,
        cg_tol=cg_tol,
        poisson_reg=poisson_reg,
        grad_backend=grad_backend,
        enforce_zero_mean=True,
        boundary_mask=boundary_mask,
    )

    def _bb_step(state: MinimState, B_ext: Array, tau_min: float, tau_max: float):
        m = state.m
        U = solve_U(m, state.U_prev)
        E, g_raw = energy_and_grad(m, U, B_ext)
        g_tan = tangent_grad(m, g_raw)
        gnorm = jnp.sqrt(jnp.vdot(g_tan, g_tan))

        def compute_tau(_):
            s = (m - state.m_prev).reshape(-1)
            y = (g_tan - state.g_prev).reshape(-1)
            sty = jnp.vdot(s, y)
            sts = jnp.vdot(s, s)
            yty = jnp.vdot(y, y)
            eps = jnp.asarray(1e-30, dtype=m.dtype)
            tau1 = sts / (sty + eps)
            tau2 = sty / (yty + eps)
            tau = jnp.where((state.it % 2) == 1, tau1, tau2)
            tau = jnp.where(sty > 0, tau, state.tau)
            return jnp.clip(tau, tau_min, tau_max)

        tau = lax.cond(state.it > 0, compute_tau, lambda _: jnp.clip(state.tau, tau_min, tau_max), operand=None)

        H = -jnp.cross(m, g_raw)
        m_new = cayley_update(m, H, tau)

        new_state = MinimState(m=m_new, U_prev=U, g_prev=g_tan, m_prev=m, tau=tau, it=state.it + jnp.int32(1))
        return new_state, E, gnorm

    bb_step = jax.jit(_bb_step, donate_argnums=(0,))

    def minimize(
        m0: Array,
        B_ext: Array,
        *,
        gamma: int = 5,
        max_iter: int = 200,
        tol_grad: float = 1e-6,
        tau0: float = 1e-2,
        tau_min: float = 1e-6,
        tau_max: float = 1.0,
        ls_eta1: float = 0.1,
        ls_eta2: float = 0.1,
        ls_C: float = 2.0,
        ls_c: float = 0.5,
        ls_s0: float = 1.0,
        ls_max_evals: int = 15,
        verbose: bool = True,
    ):
        m = jnp.asarray(m0, dtype=jnp.float64)
        m = m / jnp.linalg.norm(m, axis=1, keepdims=True)
        B_ext = jnp.asarray(B_ext, dtype=jnp.float64)

        U0 = jnp.zeros((m.shape[0],), dtype=jnp.float64)
        U = solve_U(m, U0)
        E0, g_raw = energy_and_grad(m, U, B_ext)
        g_tan = tangent_grad(m, g_raw)

        state = MinimState(m=m, U_prev=U, g_prev=g_tan, m_prev=m, tau=jnp.asarray(tau0, jnp.float64), it=jnp.int32(0))

        for k in range(gamma):
            U = solve_U(state.m, state.U_prev)
            E, g_raw = energy_and_grad(state.m, U, B_ext)
            g_tan = tangent_grad(state.m, g_raw)
            gnorm = float(jnp.sqrt(jnp.vdot(g_tan, g_tan)))
            if verbose:
                print(f"[LS {k:03d}] E={float(E):.6e}  |g|={gnorm:.3e}")
            if gnorm <= tol_grad:
                return state.m, U, {"E": float(E), "gnorm": gnorm, "iters": float(k), "phase": 0.0}

            H = -jnp.cross(state.m, g_raw)
            tau = armijo_weak_line_search(
                state.m, g_tan, H, float(E),
                U_base=U,
                solve_U=solve_U,
                energy_only=energy_only,
                B_ext=B_ext,
                eta1=ls_eta1,
                eta2=ls_eta2,
                C=ls_C,
                c=ls_c,
                s0=ls_s0,
                max_evals=ls_max_evals,
            )
            m_new = cayley_update(state.m, H, jnp.asarray(tau, jnp.float64))
            state = replace(state, m=m_new, m_prev=state.m, g_prev=g_tan, tau=jnp.asarray(tau, jnp.float64), it=state.it + jnp.int32(1), U_prev=U)

        for k in range(gamma, max_iter):
            state, E, gnorm = bb_step(state, B_ext, tau_min, tau_max)
            gnorm_f = float(gnorm)
            if verbose and (k % 10 == 0 or gnorm_f <= tol_grad):
                print(f"[BB {k:03d}] E={float(E):.6e}  |g|={gnorm_f:.3e}  tau={float(state.tau):.3e}")
            if gnorm_f <= tol_grad:
                U = solve_U(state.m, state.U_prev)
                return state.m, U, {"E": float(E), "gnorm": gnorm_f, "iters": float(k + 1), "phase": 1.0}

        U = solve_U(state.m, state.U_prev)
        E_end = float(energy_only(state.m, U, B_ext))
        return state.m, U, {"E": E_end, "gnorm": float(gnorm), "iters": float(max_iter), "phase": 2.0}

    return minimize
