"""energy_kernels.py.

Micromagnetic energy + gradient kernels on tetrahedral P1 FEM meshes.
Optimized for speed and consistency using the property:
E = 0.5 * sum(m * (g_total + g_zeeman))

Energy Scaling and Physical Units:
----------------------------------
This implementation uses a dimensionless scaling based on the reference
saturation magnetization Js_ref (Tesla) and the associated energy density:
    Kd_ref = Js_ref^2 / (2 * mu0)  [J/m^3]

Dimensionless variables:
    m = M / Js             (Unit vector)
    Js_red = Js / Js_ref   (Dimensionless)
    B_red = B_ext / Js_ref (Dimensionless)
    u = (mu0 / Js_ref) * u_calc (Dimensionless potential)

Energy Normalization (E_dimensionless = E_SI / (Kd_ref * Vmag)):
    1. Exchange:   E_ex  = (1/Vmag) * Integral( A_red * |grad m|^2 ) dV
    2. Anisotropy: E_an  = (1/Vmag) * Integral( K1_red * [1 - (m.k)^2] ) dV
    3. Zeeman:     E_z   = (1/Vmag) * Integral( -2 * Js_red * m . B_red ) dV
    4. Demag:      E_dem = (1/Vmag) * Integral( Js_red * m . grad(u) ) dV

    Note: The factor '2' in Zeeman arises because 1/Kd_ref = 2*mu0/Js_ref^2.
    Note: The factor '1/2' in physical Demag (0.5 * M . Hd) is cancelled
    by the '2' in the denominator of Kd_ref, resulting in a factor of 1.

Physical Field Conversions:
    - Scalar Potential [A]:      U_phys = (Js_ref / mu0) * u
    - Demag Field Hd [A/m]:      Hd = -grad(U_phys) = -(Js_ref / mu0) * grad(u)
    - Demag Field mu0*Hd [T]:    mu0*Hd = -Js_ref * grad(u)

Gradient Property:
    For quadratic terms (Ex, An, Demag), m^T * g = 2 * E.
    For linear terms (Zeeman), m^T * g = E.
    Thus, E_total = 0.5 * m^T * (g_quadratic + 2 * g_zeeman)
                   = 0.5 * m^T * (g_total + g_zeeman).

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Literal

import jax

jax.config.update("jax_enable_x64", True)
import jax.numpy as jnp  # noqa: E402
from jax import lax  # noqa: E402

from fem_utils import (  # noqa: E402
    TetGeom,
    assemble_scatter,
    assemble_segment_sum,
    chunk_mask,
    pad_geom_for_chunking,
    _B_split_from_JinvT,
    _compute_JinvT_from_coords,
)

MU0 = 4e-7 * jnp.pi
Array = jnp.ndarray

GradBackend = Literal["stored_grad_phi", "stored_JinvT", "on_the_fly"]
Assembly = Literal["scatter", "segment_sum"]

_GRAD_HAT = jnp.array(
    [
        [-1.0, -1.0, -1.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ],
    dtype=jnp.float64,
)


def make_energy_kernels(
    geom: TetGeom,
    A_lookup: Array,
    K1_lookup: Array,
    Js_lookup: Array,
    k_easy_lookup: Array,
    V_mag: float,
    M_nodal: Array,
    *,
    B_bias: Array | None = None,
    k1me: Array | None = None,
    k1me_p: Array | None = None,
    chunk_elems: int = 200_000,
    assembly: Assembly = "segment_sum",
    grad_backend: GradBackend = "stored_grad_phi",
    mode: str = "matrix_free",
    Kex_sparse: Any | None = None,
    Gx_sparse: Any | None = None,
    Gy_sparse: Any | None = None,
    Gz_sparse: Any | None = None,
    Kan_sparse: Any | None = None,
    k_nodes: Array | None = None,
) -> tuple[
    Callable[[Array, Array, Array], tuple[Array, Array]],
    Callable[[Array, Array, Array], Array],
    Callable[[Array, Array, Array], Array],
    Callable[[Array], Array],
]:
    """Create JIT-compiled micromagnetic energy and gradient functions in matrix-free or matrix-assembled mode.

    Returns a quartet of functions (energy_and_grad, energy_only, grad_only, local_grad_only).
    All calculations use dimensionless scaling.

    Args:
        geom (TetGeom): Geometry container.
        A_lookup (Array): Dimensionless exchange constants for each material.
        K1_lookup (Array): Dimensionless anisotropy constants for each material.
        Js_lookup (Array): Dimensionless saturation polarization for each material.
        k_easy_lookup (Array): Easy axis vectors (unit length) for each material (G, 3).
        V_mag (float): Total magnetic volume in mesh units (e.g., nm^3).
        M_nodal (Array): Nodal magnetic moment scaling (N,).
        B_bias (Array | None, optional): Per-node bias field for mode initialization.
        k1me (Array | None, optional): Per-element magnetoelastic constant Kx.
        k1me_p (Array | None, optional): Per-element magnetoelastic constant Ky.
        chunk_elems (int, optional): Elements processed per loop iteration.
            Defaults to 200_000.
        assembly (Assembly, optional): Nodal assembly method
            ('scatter' or 'segment_sum'). Defaults to 'scatter'.
        grad_backend (GradBackend, optional): Strategy for shape function gradients.
            'stored_grad_phi', 'stored_JinvT', or 'on_the_fly'.
            Defaults to 'stored_grad_phi'.
        mode (str, optional): Operator mode ('matrix_free' or 'assembled').
        Kex_sparse (Any | None): Assembled exchange matrix in JAX BCOO format.
        Gx_sparse, Gy_sparse, Gz_sparse (Any | None): Assembled demag gradient component matrices.
        Kan_sparse (Any | None): Assembled anisotropy matrix in JAX BCOO format.
        k_nodes (Array | None): Precomputed easy axis per node (N, 3).

    Returns:
        tuple[Callable, Callable, Callable, Callable]: (energy_and_grad, energy_only, grad_only, local_grad_only).
            Each function takes (m, U, B_ext) as input, except local_grad_only which takes only v.
    """
    inv_Vmag = 1.0 / V_mag

    if mode == "assembled":
        if Kex_sparse is None or Gx_sparse is None or Gy_sparse is None or Gz_sparse is None or Kan_sparse is None or k_nodes is None:
            raise ValueError("assembled mode requires Kex_sparse, Gx_sparse, Gy_sparse, Gz_sparse, Kan_sparse, and k_nodes")

        def energy_and_grad(Kex_sparse_arg, Kan_sparse_arg, Gx_sparse_arg, Gy_sparse_arg, Gz_sparse_arg, k_nodes_arg, M_nodal_arg, inv_Vmag_arg, B_bias_arg, m: Array, U: Array, B_ext: Array) -> tuple[Array, Array]:
            N = m.shape[0]
            dtype = m.dtype
            B_ext = jnp.asarray(B_ext, dtype=dtype)

            # 1. Exchange gradient: Kex @ m (shape (N, 3))
            g_ex = Kex_sparse_arg @ m

            # 2. Uniaxial anisotropy gradient: Kan @ (m . k) * k (shape (N, 3))
            p = m[:, 0] * k_nodes_arg[:, 0] + m[:, 1] * k_nodes_arg[:, 1] + m[:, 2] * k_nodes_arg[:, 2]
            w = Kan_sparse_arg @ p
            g_an = w[:, None] * k_nodes_arg

            # 3. Demag gradient: G @ U (shape (N, 3))
            g_dem_x = Gx_sparse_arg @ U
            g_dem_y = Gy_sparse_arg @ U
            g_dem_z = Gz_sparse_arg @ U
            g_dem = jnp.stack([g_dem_x, g_dem_y, g_dem_z], axis=1)

            # 4. Zeeman gradient
            B_eff = B_ext[None, :]
            if B_bias_arg is not None:
                B_eff = B_eff + B_bias_arg
            g_z = -2.0 * M_nodal_arg[:, None] * B_eff

            # Total gradient
            g_total = g_ex + g_an + g_dem + g_z

            # Energy calculation trick: E = 0.5 * sum(m * (g_total + g_z))
            E = 0.5 * jnp.sum(m * (g_total + g_z))
            return E * inv_Vmag_arg, g_total * inv_Vmag_arg

        def energy_only(Kex_sparse_arg, Kan_sparse_arg, Gx_sparse_arg, Gy_sparse_arg, Gz_sparse_arg, k_nodes_arg, M_nodal_arg, inv_Vmag_arg, B_bias_arg, m: Array, U: Array, B_ext: Array) -> Array:
            E, _ = energy_and_grad(Kex_sparse_arg, Kan_sparse_arg, Gx_sparse_arg, Gy_sparse_arg, Gz_sparse_arg, k_nodes_arg, M_nodal_arg, inv_Vmag_arg, B_bias_arg, m, U, B_ext)
            return E

        def grad_only(Kex_sparse_arg, Kan_sparse_arg, Gx_sparse_arg, Gy_sparse_arg, Gz_sparse_arg, k_nodes_arg, M_nodal_arg, inv_Vmag_arg, B_bias_arg, m: Array, U: Array, B_ext: Array) -> Array:
            _, g = energy_and_grad(Kex_sparse_arg, Kan_sparse_arg, Gx_sparse_arg, Gy_sparse_arg, Gz_sparse_arg, k_nodes_arg, M_nodal_arg, inv_Vmag_arg, B_bias_arg, m, U, B_ext)
            return g

        def local_grad_only(Kex_sparse_arg, Kan_sparse_arg, k_nodes_arg, inv_Vmag_arg, v: Array) -> Array:
            # Action of local Hessian (Ex + An)
            g_ex = Kex_sparse_arg @ v
            p = v[:, 0] * k_nodes_arg[:, 0] + v[:, 1] * k_nodes_arg[:, 1] + v[:, 2] * k_nodes_arg[:, 2]
            g_an = (Kan_sparse_arg @ p)[:, None] * k_nodes_arg
            return (g_ex + g_an) * inv_Vmag_arg

        return (
            jax.tree_util.Partial(jax.jit(energy_and_grad), Kex_sparse, Kan_sparse, Gx_sparse, Gy_sparse, Gz_sparse, k_nodes, M_nodal, inv_Vmag, B_bias),
            jax.tree_util.Partial(jax.jit(energy_only), Kex_sparse, Kan_sparse, Gx_sparse, Gy_sparse, Gz_sparse, k_nodes, M_nodal, inv_Vmag, B_bias),
            jax.tree_util.Partial(jax.jit(grad_only), Kex_sparse, Kan_sparse, Gx_sparse, Gy_sparse, Gz_sparse, k_nodes, M_nodal, inv_Vmag, B_bias),
            jax.tree_util.Partial(jax.jit(local_grad_only), Kex_sparse, Kan_sparse, k_nodes, inv_Vmag),
        )

    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id

    # Inverse volume normalization
    inv_Vmag = 1.0 / V_mag

    # Pre-calculate material-weighted geometry terms to save multiplications
    # in the loop.
    g_ids = mat_id - 1
    A_Ve = 2.0 * A_lookup[g_ids] * Ve
    K1_Ve = 2.0 * K1_lookup[g_ids] * Ve / 20.0
    Js_Ve = 2.0 * Js_lookup[g_ids] * Ve / 4.0

    # Magnetoelastic terms (per element)
    if k1me is not None:
        k1me_padded = jnp.zeros(conn.shape[0])
        k1me_padded = k1me_padded.at[: k1me.shape[0]].set(k1me)
        k1mep_padded = jnp.zeros(conn.shape[0])
        if k1me_p is not None:
            k1mep_padded = k1mep_padded.at[: k1me_p.shape[0]].set(k1me_p)

        Kx_Ve = 2.0 * (k1me_padded + k1mep_padded) * Ve / 20.0
        Ky_Ve = 2.0 * (k1me_padded - k1mep_padded) * Ve / 20.0
    else:
        Kx_Ve = None
        Ky_Ve = None

    if grad_backend == "stored_grad_phi":
        if geom_p.grad_phi is None:
            raise ValueError("stored_grad_phi requires geom.grad_phi")
        grad_phi = geom_p.grad_phi
        grad_phi_x = grad_phi[:, :, 0]
        grad_phi_y = grad_phi[:, :, 1]
        grad_phi_z = grad_phi[:, :, 2]
        JinvT = None
        x_nodes = None
    elif grad_backend == "stored_JinvT":
        if geom_p.JinvT is None:
            raise ValueError("stored_JinvT requires geom.JinvT")
        grad_phi = None
        JinvT = geom_p.JinvT
        x_nodes = None
    else:
        if geom_p.x_nodes is None:
            raise ValueError("on_the_fly requires geom.x_nodes")
        grad_phi = None
        JinvT = None
        x_nodes = geom_p.x_nodes

    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems

    # Ensure all lookups are JAX arrays
    A_lookup = jnp.asarray(A_lookup)
    K1_lookup = jnp.asarray(K1_lookup)
    Js_lookup = jnp.asarray(Js_lookup)
    k_easy_lookup = jnp.asarray(k_easy_lookup)

    def _get_B(conn_c: Array, s: int, dtype: Any) -> tuple[Array, Array, Array]:
        if grad_backend == "stored_grad_phi":
            bx = lax.dynamic_slice(grad_phi_x, (s, 0), (chunk_elems, 4)).astype(dtype)
            by = lax.dynamic_slice(grad_phi_y, (s, 0), (chunk_elems, 4)).astype(dtype)
            bz = lax.dynamic_slice(grad_phi_z, (s, 0), (chunk_elems, 4)).astype(dtype)
            return bx, by, bz
        elif grad_backend == "stored_JinvT":
            JinvT_c = lax.dynamic_slice(JinvT, (s, 0, 0), (chunk_elems, 3, 3)).astype(dtype)
            return _B_split_from_JinvT(JinvT_c, dtype)
        else:
            x_e = x_nodes[conn_c].astype(dtype)
            JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
            return _B_split_from_JinvT(JinvT_c, dtype)

    def local_grad_only(v: Array) -> Array:
        """Compute the action of the local Hessian (Ex + An) on vector v.

        Used for PCG preconditioning.
        """
        N = v.shape[0]
        dtype = v.dtype

        def body(i: int, g_acc: Array) -> Array:
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            Bx, By, Bz = _get_B(conn_c, s, dtype)
            mask = chunk_mask(E_orig, s, chunk_elems, dtype)

            a_ve_c = lax.dynamic_slice(A_Ve, (s,), (chunk_elems,)) * mask
            q_ve_c = lax.dynamic_slice(K1_Ve, (s,), (chunk_elems,)) * mask
            k_c = k_easy_lookup[mat_c - 1].astype(dtype)
            v_e = v[conn_c]

            # 1. Exchange
            vx_e, vy_e, vz_e = v_e[:, :, 0], v_e[:, :, 1], v_e[:, :, 2]
            
            grad_vx_x = Bx[:, 0] * vx_e[:, 0] + Bx[:, 1] * vx_e[:, 1] + Bx[:, 2] * vx_e[:, 2] + Bx[:, 3] * vx_e[:, 3]
            grad_vx_y = By[:, 0] * vx_e[:, 0] + By[:, 1] * vx_e[:, 1] + By[:, 2] * vx_e[:, 2] + By[:, 3] * vx_e[:, 3]
            grad_vx_z = Bz[:, 0] * vx_e[:, 0] + Bz[:, 1] * vx_e[:, 1] + Bz[:, 2] * vx_e[:, 2] + Bz[:, 3] * vx_e[:, 3]
            
            grad_vy_x = Bx[:, 0] * vy_e[:, 0] + Bx[:, 1] * vy_e[:, 1] + Bx[:, 2] * vy_e[:, 2] + Bx[:, 3] * vy_e[:, 3]
            grad_vy_y = By[:, 0] * vy_e[:, 0] + By[:, 1] * vy_e[:, 1] + By[:, 2] * vy_e[:, 2] + By[:, 3] * vy_e[:, 3]
            grad_vy_z = Bz[:, 0] * vy_e[:, 0] + Bz[:, 1] * vy_e[:, 1] + Bz[:, 2] * vy_e[:, 2] + Bz[:, 3] * vy_e[:, 3]
            
            grad_vz_x = Bx[:, 0] * vz_e[:, 0] + Bx[:, 1] * vz_e[:, 1] + Bx[:, 2] * vz_e[:, 2] + Bx[:, 3] * vz_e[:, 3]
            grad_vz_y = By[:, 0] * vz_e[:, 0] + By[:, 1] * vz_e[:, 1] + By[:, 2] * vz_e[:, 2] + By[:, 3] * vz_e[:, 3]
            grad_vz_z = Bz[:, 0] * vz_e[:, 0] + Bz[:, 1] * vz_e[:, 1] + Bz[:, 2] * vz_e[:, 2] + Bz[:, 3] * vz_e[:, 3]
            
            Km_x = Bx * grad_vx_x[:, None] + By * grad_vx_y[:, None] + Bz * grad_vx_z[:, None]
            Km_y = Bx * grad_vy_x[:, None] + By * grad_vy_y[:, None] + Bz * grad_vy_z[:, None]
            Km_z = Bx * grad_vz_x[:, None] + By * grad_vz_y[:, None] + Bz * grad_vz_z[:, None]
            
            contrib = a_ve_c[:, None, None] * jnp.stack([Km_x, Km_y, Km_z], axis=2)

            # 2. Anisotropy
            proj_v = v_e[:, :, 0] * k_c[:, None, 0] + v_e[:, :, 1] * k_c[:, None, 1] + v_e[:, :, 2] * k_c[:, None, 2]
            sum_proj = (proj_v[:, 0] + proj_v[:, 1] + proj_v[:, 2] + proj_v[:, 3])[:, None]
            factor = -q_ve_c[:, None] * (sum_proj + proj_v)
            contrib = contrib + factor[..., None] * k_c[:, None, :]

            # 3. Magnetoelastic
            if Kx_Ve is not None:
                kx_ve_c = lax.dynamic_slice(Kx_Ve, (s,), (chunk_elems,)) * mask
                ky_ve_c = lax.dynamic_slice(Ky_Ve, (s,), (chunk_elems,)) * mask
                vx_e, vy_e = v_e[:, :, 0], v_e[:, :, 1]
                sum_vx = (vx_e[:, 0] + vx_e[:, 1] + vx_e[:, 2] + vx_e[:, 3])[:, None]
                sum_vy = (vy_e[:, 0] + vy_e[:, 1] + vy_e[:, 2] + vy_e[:, 3])[:, None]
                gx_me = kx_ve_c[:, None] * (sum_vx + vx_e)
                gy_me = ky_ve_c[:, None] * (sum_vy + vy_e)
                contrib = contrib.at[:, :, 0].add(gx_me)
                contrib = contrib.at[:, :, 1].add(gy_me)

            if assembly == "scatter":
                g_acc = assemble_scatter(g_acc, conn_c, contrib)
            else:
                g_acc = g_acc + assemble_segment_sum(N, conn_c, contrib, dtype)
            return g_acc

        g_local = lax.fori_loop(0, n_chunks, body, jnp.zeros((N, 3), dtype=dtype))
        return g_local * inv_Vmag

    def energy_and_grad(m: Array, U: Array, B_ext: Array) -> tuple[Array, Array]:
        """Compute the total dimensionless energy and gradient.

        Args:
            m (Array): Nodal unit magnetization vectors (N, 3).
            U (Array): Nodal scalar potential (N,).
            B_ext (Array): Dimensionless external field vector (3,).

        Returns:
            tuple[Array, Array]: (Total Energy, Total Gradient N, 3).
        """
        N = m.shape[0]
        dtype = m.dtype
        # B_ext is expected to be reduced: b_ext = B_ext / Js_ref
        B_ext = jnp.asarray(B_ext, dtype=dtype)

        def body(i: int, g_acc: Array) -> Array:
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            Bx, By, Bz = _get_B(conn_c, s, dtype)

            mask = chunk_mask(E_orig, s, chunk_elems, dtype)

            # Slice pre-scaled properties and apply mask
            a_ve_c = lax.dynamic_slice(A_Ve, (s,), (chunk_elems,)) * mask
            q_ve_c = lax.dynamic_slice(K1_Ve, (s,), (chunk_elems,)) * mask
            j_ve_c = lax.dynamic_slice(Js_Ve, (s,), (chunk_elems,)) * mask

            k_c = k_easy_lookup[mat_c - 1].astype(dtype)

            m_e = m[conn_c]
            U_e = U[conn_c]

            # 1. Exchange Gradient (Quadratic)
            mx_e, my_e, mz_e = m_e[:, :, 0], m_e[:, :, 1], m_e[:, :, 2]
            
            grad_mx_x = Bx[:, 0] * mx_e[:, 0] + Bx[:, 1] * mx_e[:, 1] + Bx[:, 2] * mx_e[:, 2] + Bx[:, 3] * mx_e[:, 3]
            grad_mx_y = By[:, 0] * mx_e[:, 0] + By[:, 1] * mx_e[:, 1] + By[:, 2] * mx_e[:, 2] + By[:, 3] * mx_e[:, 3]
            grad_mx_z = Bz[:, 0] * mx_e[:, 0] + Bz[:, 1] * mx_e[:, 1] + Bz[:, 2] * mx_e[:, 2] + Bz[:, 3] * mx_e[:, 3]
            
            grad_my_x = Bx[:, 0] * my_e[:, 0] + Bx[:, 1] * my_e[:, 1] + Bx[:, 2] * my_e[:, 2] + Bx[:, 3] * my_e[:, 3]
            grad_my_y = By[:, 0] * my_e[:, 0] + By[:, 1] * my_e[:, 1] + By[:, 2] * my_e[:, 2] + By[:, 3] * my_e[:, 3]
            grad_my_z = Bz[:, 0] * my_e[:, 0] + Bz[:, 1] * my_e[:, 1] + Bz[:, 2] * my_e[:, 2] + Bz[:, 3] * my_e[:, 3]
            
            grad_mz_x = Bx[:, 0] * mz_e[:, 0] + Bx[:, 1] * mz_e[:, 1] + Bx[:, 2] * mz_e[:, 2] + Bx[:, 3] * mz_e[:, 3]
            grad_mz_y = By[:, 0] * mz_e[:, 0] + By[:, 1] * mz_e[:, 1] + By[:, 2] * mz_e[:, 2] + By[:, 3] * mz_e[:, 3]
            grad_mz_z = Bz[:, 0] * mz_e[:, 0] + Bz[:, 1] * mz_e[:, 1] + Bz[:, 2] * mz_e[:, 2] + Bz[:, 3] * mz_e[:, 3]
            
            Km_x = Bx * grad_mx_x[:, None] + By * grad_mx_y[:, None] + Bz * grad_mx_z[:, None]
            Km_y = Bx * grad_my_x[:, None] + By * grad_my_y[:, None] + Bz * grad_my_z[:, None]
            Km_z = Bx * grad_mz_x[:, None] + By * grad_mz_y[:, None] + Bz * grad_mz_z[:, None]
            
            contrib = a_ve_c[:, None, None] * jnp.stack([Km_x, Km_y, Km_z], axis=2)

            # 2. Uniaxial Anisotropy Gradient (Quadratic)
            v_e = m_e[:, :, 0] * k_c[:, None, 0] + m_e[:, :, 1] * k_c[:, None, 1] + m_e[:, :, 2] * k_c[:, None, 2]

            sum_v = (v_e[:, 0] + v_e[:, 1] + v_e[:, 2] + v_e[:, 3])[:, None]
            factor = -q_ve_c[:, None] * (sum_v + v_e)
            contrib = contrib + factor[..., None] * k_c[:, None, :]

            # 3. Demag Gradient (Quadratic)
            grad_ux = Bx[:, 0] * U_e[:, 0] + Bx[:, 1] * U_e[:, 1] + Bx[:, 2] * U_e[:, 2] + Bx[:, 3] * U_e[:, 3]
            grad_uy = By[:, 0] * U_e[:, 0] + By[:, 1] * U_e[:, 1] + By[:, 2] * U_e[:, 2] + By[:, 3] * U_e[:, 3]
            grad_uz = Bz[:, 0] * U_e[:, 0] + Bz[:, 1] * U_e[:, 1] + Bz[:, 2] * U_e[:, 2] + Bz[:, 3] * U_e[:, 3]
            
            grad_u = jnp.stack([grad_ux, grad_uy, grad_uz], axis=1)

            contrib = contrib + j_ve_c[:, None, None] * grad_u[:, None, :]

            # 4. Magnetoelastic Anisotropy (Quadratic)
            if Kx_Ve is not None:
                kx_ve_c = lax.dynamic_slice(Kx_Ve, (s,), (chunk_elems,)) * mask
                ky_ve_c = lax.dynamic_slice(Ky_Ve, (s,), (chunk_elems,)) * mask

                mx_e = m_e[:, :, 0]
                my_e = m_e[:, :, 1]

                sum_mx = (mx_e[:, 0] + mx_e[:, 1] + mx_e[:, 2] + mx_e[:, 3])[:, None]
                sum_my = (my_e[:, 0] + my_e[:, 1] + my_e[:, 2] + my_e[:, 3])[:, None]

                gx_me = kx_ve_c[:, None] * (sum_mx + mx_e)
                gy_me = ky_ve_c[:, None] * (sum_my + my_e)

                contrib = contrib.at[:, :, 0].add(gx_me)
                contrib = contrib.at[:, :, 1].add(gy_me)

            if assembly == "scatter":
                g_acc = assemble_scatter(g_acc, conn_c, contrib)
            else:
                g_acc = g_acc + assemble_segment_sum(N, conn_c, contrib, dtype)

            return g_acc

        # Compute sum of quadratic gradients (Ex + An + Demag)
        g_quad = lax.fori_loop(0, n_chunks, body, jnp.zeros((N, 3), dtype=dtype))

        # 4. Zeeman Gradient (Linear)
        B_eff = B_ext[None, :]
        if B_bias is not None:
            B_eff = B_eff + B_bias

        g_z = -2.0 * M_nodal[:, None] * B_eff

        # Total Gradient
        g_total = g_quad + g_z

        # Total Energy calculation choice.
        # Mathematical Trick:
        # For quadratic terms (Ex, An, Demag): m^T * g_quad = 2 * E_quad
        # For linear terms (Zeeman): m^T * g_z = E_z
        # Total F = E_quad + E_z = 0.5 * (2 * E_quad + 2 * E_z)
        # Therefore, F = 0.5 * m^T * (g_quad + 2 * g_z) = 0.5 * m^T * (g_total + g_z)
        # This avoids separate energy integrations and ensures consistency.
        E = 0.5 * jnp.sum(m * (g_total + g_z))

        return E * inv_Vmag, g_total * inv_Vmag

    def energy_only(m: Array, U: Array, B_ext: Array) -> Array:
        """Compute only the total dimensionless energy.

        Args:
            m (Array): Nodal unit magnetization vectors (N, 3).
            U (Array): Nodal scalar potential (N,).
            B_ext (Array): Dimensionless external field vector (3,).

        Returns:
            Array: Scalar dimensionless energy.
        """
        E, _ = energy_and_grad(m, U, B_ext)
        return E

    def grad_only(m: Array, U: Array, B_ext: Array) -> Array:
        """Compute only the total energy gradient.

        Args:
            m (Array): Nodal unit magnetization vectors (N, 3).
            U (Array): Nodal scalar potential (N,).
            B_ext (Array): Dimensionless external field vector (3,).

        Returns:
            Array: Energy gradient vectors (N, 3).
        """
        _, g = energy_and_grad(m, U, B_ext)
        return g

    return jax.jit(energy_and_grad), jax.jit(energy_only), jax.jit(grad_only), jax.jit(local_grad_only)


def compute_exchange_diagonal(
    geom: TetGeom,
    A_lookup: Array,
    V_mag: float,
    *,
    chunk_elems: int = 200_000,
    assembly: Assembly = "segment_sum",
    grad_backend: GradBackend = "stored_grad_phi",
) -> Array:
    """Compute the diagonal of the exchange (stiffness) matrix.
    
    This is used for Jacobi preconditioning.
    """
    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id
    
    if geom_p.x_nodes is not None:
        N = geom_p.x_nodes.shape[0]
    else:
        N = int(jnp.max(geom.conn)) + 1
        
    dtype = jnp.float64
    inv_Vmag = 1.0 / V_mag
    
    g_ids = mat_id - 1
    A_Ve = 2.0 * A_lookup[g_ids] * Ve
    
    # We need grad_phi or other variables for _get_B
    grad_phi = geom_p.grad_phi
    grad_phi_x = grad_phi[:, :, 0] if grad_phi is not None else None
    grad_phi_y = grad_phi[:, :, 1] if grad_phi is not None else None
    grad_phi_z = grad_phi[:, :, 2] if grad_phi is not None else None
    JinvT = geom_p.JinvT
    x_nodes = geom_p.x_nodes
    
    def _get_B(conn_c: Array, s: int) -> tuple[Array, Array, Array]:
        if grad_backend == "stored_grad_phi":
            bx = lax.dynamic_slice(grad_phi_x, (s, 0), (chunk_elems, 4)).astype(dtype)
            by = lax.dynamic_slice(grad_phi_y, (s, 0), (chunk_elems, 4)).astype(dtype)
            bz = lax.dynamic_slice(grad_phi_z, (s, 0), (chunk_elems, 4)).astype(dtype)
            return bx, by, bz
        elif grad_backend == "stored_JinvT":
            JinvT_c = lax.dynamic_slice(JinvT, (s, 0, 0), (chunk_elems, 3, 3)).astype(dtype)
            return _B_split_from_JinvT(JinvT_c, dtype)
        else:
            x_e = x_nodes[conn_c].astype(dtype)
            JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
            return _B_split_from_JinvT(JinvT_c, dtype)
            
    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems
    
    def body(i: int, d_acc: Array) -> Array:
        s = i * chunk_elems
        conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
        Bx, By, Bz = _get_B(conn_c, s)
        mask = chunk_mask(E_orig, s, chunk_elems, dtype)
        
        a_ve_c = lax.dynamic_slice(A_Ve, (s,), (chunk_elems,)) * mask
        
        # B_c has shape (chunk_elems, 4, 3)
        # We compute sum_{k=0}^2 (B_c[:, a, k]**2) for each a in {0, 1, 2, 3}
        grad_phi_sq = Bx ** 2 + By ** 2 + Bz ** 2  # (chunk_elems, 4)
        contrib = a_ve_c[:, None] * grad_phi_sq  # (chunk_elems, 4)
        
        if assembly == "scatter":
            d_acc = assemble_scatter(d_acc, conn_c, contrib)
        else:
            d_acc = d_acc + assemble_segment_sum(N, conn_c, contrib, dtype)
        return d_acc
        
    d0 = jnp.zeros((N,), dtype=dtype)
    d_diag = jax.lax.fori_loop(0, n_chunks, body, d0)
    
    # Scale by inv_Vmag to match the scaling of local_grad_only
    d_diag = d_diag * inv_Vmag
    return jax.jit(lambda: d_diag)()

