"""energy_kernels.py

Micromagnetic energy + gradient kernels on tetrahedral P1 FEM meshes.
Optimized for speed and consistency using the property:
E = 0.5 * sum(m * (g_total + g_zeeman))

Energy Scaling and Physical Units:
----------------------------------
This implementation uses a dimensionless scaling based on the reference 
saturation magnetization Js_ref (Tesla) and the associated energy density:
    Kd_ref = Js_ref^2 / (2 * mu0)  [J/m^3]

Dimensionless variables:
    m = M / Js             (Unit vector)
    Js_red = Js / Js_ref   (Dimensionless)
    B_red = B_ext / Js_ref (Dimensionless)
    u = (mu0 / Js_ref) * u_calc (Dimensionless potential)

Energy Normalization (E_dimensionless = E_SI / (Kd_ref * Vmag)):
    1. Exchange:   E_ex  = (1/Vmag) * Integral( A_red * |grad m|^2 ) dV
    2. Anisotropy: E_an  = (1/Vmag) * Integral( K1_red * [1 - (m.k)^2] ) dV
    3. Zeeman:     E_z   = (1/Vmag) * Integral( -2 * Js_red * m . B_red ) dV
    4. Demag:      E_dem = (1/Vmag) * Integral( Js_red * m . grad(u) ) dV

    Note: The factor '2' in Zeeman arises because 1/Kd_ref = 2*mu0/Js_ref^2.
    Note: The factor '1/2' in physical Demag (0.5 * M . Hd) is cancelled 
    by the '2' in the denominator of Kd_ref, resulting in a factor of 1.

Physical Field Conversions:
    - Scalar Potential [A]:      U_phys = (Js_ref / mu0) * u
    - Demag Field Hd [A/m]:      Hd = -grad(U_phys) = -(Js_ref / mu0) * grad(u)
    - Demag Field mu0*Hd [T]:    mu0*Hd = -Js_ref * grad(u)

Gradient Property:
    For quadratic terms (Ex, An, Demag), m^T * g = 2 * E.
    For linear terms (Zeeman), m^T * g = E.
    Thus, E_total = 0.5 * m^T * (g_quadratic + 2 * g_zeeman) = 0.5 * m^T * (g_total + g_zeeman).

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from typing import Callable, Tuple, Literal

import jax
import jax.numpy as jnp
from jax import lax

from fem_utils import TetGeom, pad_geom_for_chunking, chunk_mask, assemble_scatter, assemble_segment_sum

MU0 = 4e-7 * jnp.pi
Array = jnp.ndarray

GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']
Assembly = Literal['scatter', 'segment_sum']

_GRAD_HAT = jnp.array([
    [-1.0, -1.0, -1.0],
    [ 1.0,  0.0,  0.0],
    [ 0.0,  1.0,  0.0],
    [ 0.0,  0.0,  1.0],
], dtype=jnp.float64)


def _B_from_JinvT(JinvT_c: Array, dtype) -> Array:
    return jnp.einsum('eij,aj->eai', JinvT_c.astype(dtype), _GRAD_HAT.astype(dtype))


def _compute_JinvT_from_coords(x_e: Array, dtype) -> Array:
    x0 = x_e[:, 0, :]
    J = jnp.stack([x_e[:, 1, :] - x0, x_e[:, 2, :] - x0, x_e[:, 3, :] - x0], axis=2)
    invJ = jnp.linalg.inv(J.astype(dtype))
    return jnp.swapaxes(invJ, 1, 2)


def make_energy_kernels(
    geom: TetGeom,
    A_lookup: Array,
    K1_lookup: Array,
    Js_lookup: Array,
    k_easy_lookup: Array,
    V_mag: float,
    M_nodal: Array,
    *,
    chunk_elems: int = 200_000,
    assembly: Assembly = 'scatter',
    grad_backend: GradBackend = 'stored_grad_phi',
) -> Tuple[
    Callable[[Array, Array, Array], Tuple[Array, Array]],
    Callable[[Array, Array, Array], Array],
    Callable[[Array, Array, Array], Array],
]:

    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id

    # Inverse volume normalization
    inv_Vmag = 1.0 / V_mag

    # Pre-calculate material-weighted geometry terms to save multiplications in the loop
    # mat_id is 1-based, so subtract 1 for lookup
    g_ids = mat_id - 1
    # Scale factors for each energy term (Factor 2.0 for quadratic gradients)
    A_Ve = 2.0 * A_lookup[g_ids] * Ve
    K1_Ve = 2.0 * K1_lookup[g_ids] * Ve / 20.0
    Js_Ve = 2.0 * Js_lookup[g_ids] * Ve / 4.0

    if grad_backend == 'stored_grad_phi':
        if geom_p.grad_phi is None:
            raise ValueError('stored_grad_phi requires geom.grad_phi')
        grad_phi = geom_p.grad_phi
        JinvT = None
        x_nodes = None
    elif grad_backend == 'stored_JinvT':
        if geom_p.JinvT is None:
            raise ValueError('stored_JinvT requires geom.JinvT')
        grad_phi = None
        JinvT = geom_p.JinvT
        x_nodes = None
    else:
        if geom_p.x_nodes is None:
            raise ValueError('on_the_fly requires geom.x_nodes')
        grad_phi = None
        JinvT = None
        x_nodes = geom_p.x_nodes

    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems

    A_lookup = jnp.asarray(A_lookup)
    K1_lookup = jnp.asarray(K1_lookup)
    Js_lookup = jnp.asarray(Js_lookup)
    k_easy_lookup = jnp.asarray(k_easy_lookup)

    def _get_B(conn_c: Array, s: int, dtype) -> Array:
        if grad_backend == 'stored_grad_phi':
            return lax.dynamic_slice(grad_phi, (s, 0, 0), (chunk_elems, 4, 3)).astype(dtype)
        elif grad_backend == 'stored_JinvT':
            JinvT_c = lax.dynamic_slice(JinvT, (s, 0, 0), (chunk_elems, 3, 3)).astype(dtype)
            return _B_from_JinvT(JinvT_c, dtype)
        else:
            x_e = x_nodes[conn_c].astype(dtype)
            JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
            return _B_from_JinvT(JinvT_c, dtype)

    def energy_and_grad(m: Array, U: Array, B_ext: Array) -> Tuple[Array, Array]:
        N = m.shape[0]
        dtype = m.dtype
        # B_ext is expected to be reduced: b_ext = B_ext / Js_ref
        B_ext = jnp.asarray(B_ext, dtype=dtype)

        def body(i, g_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)

            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            
            # Slice pre-scaled properties and apply mask
            a_ve_c = lax.dynamic_slice(A_Ve, (s,), (chunk_elems,)) * mask
            q_ve_c = lax.dynamic_slice(K1_Ve, (s,), (chunk_elems,)) * mask
            j_ve_c = lax.dynamic_slice(Js_Ve, (s,), (chunk_elems,)) * mask
            
            k_c = k_easy_lookup[mat_c - 1].astype(dtype)

            m_e = m[conn_c]
            U_e = U[conn_c]

            # 1. Exchange Gradient (Quadratic)
            # grad_m [e, i, k] = sum_a m_eai * B_eak
            G = (m_e[:, 0, :, None] * B_c[:, 0, None, :] + 
                 m_e[:, 1, :, None] * B_c[:, 1, None, :] + 
                 m_e[:, 2, :, None] * B_c[:, 2, None, :] + 
                 m_e[:, 3, :, None] * B_c[:, 3, None, :])
            
            # Km [e, a, i] = sum_k G_eik * B_eak
            # We unroll over the spatial index k=0,1,2
            Km = (G[:, :, 0][:, None, :] * B_c[:, :, 0][:, :, None] + 
                  G[:, :, 1][:, None, :] * B_c[:, :, 1][:, :, None] + 
                  G[:, :, 2][:, None, :] * B_c[:, :, 2][:, :, None])
            
            contrib = a_ve_c[:, None, None] * Km

            # 2. Uniaxial Anisotropy Gradient (Quadratic)
            # Unrolled dot products and sums for maximum register pressure efficiency
            v_e = (m_e[:, :, 0] * k_c[:, None, 0] + 
                   m_e[:, :, 1] * k_c[:, None, 1] + 
                   m_e[:, :, 2] * k_c[:, None, 2])
            
            sum_v = (v_e[:, 0] + v_e[:, 1] + v_e[:, 2] + v_e[:, 3])[:, None]
            factor = -q_ve_c[:, None] * (sum_v + v_e)
            contrib = contrib + factor[..., None] * k_c[:, None, :]

            # 3. Demag Gradient (Quadratic)
            # grad_u = sum_a U_ea * B_eak
            grad_u = (U_e[:, 0, None] * B_c[:, 0, :] + 
                      U_e[:, 1, None] * B_c[:, 1, :] + 
                      U_e[:, 2, None] * B_c[:, 2, :] + 
                      U_e[:, 3, None] * B_c[:, 3, :])
            
            contrib = contrib + j_ve_c[:, None, None] * grad_u[:, None, :]

            if assembly == 'scatter':
                g_acc = assemble_scatter(g_acc, conn_c, contrib)
            else:
                g_acc = g_acc + assemble_segment_sum(N, conn_c, contrib, dtype)

            return g_acc

        # Compute sum of quadratic gradients (Ex + An + Demag)
        g_quad = lax.fori_loop(0, n_chunks, body, jnp.zeros((N, 3), dtype=dtype))
        
        # 4. Zeeman Gradient (Linear)
        # scale_z = -2.0 * Js_red * Ve / 4
        g_z = -2.0 * M_nodal[:, None] * B_ext[None, :]
        
        # Total Gradient
        g_total = g_quad + g_z
        
        # Total Energy (using Eq 9 logic)
        # F = 0.5 * m^T (g_quad) + m^T g_z = 0.5 * m^T (g_quad + 2*g_z)
        # Alternatively: F = 0.5 * m^T (g_total + g_z)
        E = 0.5 * jnp.sum(m * (g_total + g_z))
        
        return E * inv_Vmag, g_total * inv_Vmag

    def energy_only(m: Array, U: Array, B_ext: Array) -> Array:
        E, _ = energy_and_grad(m, U, B_ext)
        return E

    def grad_only(m: Array, U: Array, B_ext: Array) -> Array:
        _, g = energy_and_grad(m, U, B_ext)
        return g

    return jax.jit(energy_and_grad), jax.jit(energy_only), jax.jit(grad_only)
