"""energy_kernels.py

Micromagnetic energy + gradient kernels on tetrahedral P1 FEM meshes.

Supports grad_backend:
  - stored_grad_phi: geom.grad_phi (E,4,3)
  - stored_JinvT:    geom.JinvT (E,3,3)
  - on_the_fly:      geom.x_nodes (N,3) + conn

All computations remain float64 if inputs are float64.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from typing import Callable, Tuple, Literal

import jax
import jax.numpy as jnp
from jax import lax

from fem_utils import TetGeom, pad_geom_for_chunking, chunk_mask, assemble_scatter, assemble_segment_sum

MU0 = 4e-7 * jnp.pi
Array = jnp.ndarray

GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']
Assembly = Literal['scatter', 'segment_sum']

_GRAD_HAT = jnp.array([
    [-1.0, -1.0, -1.0],
    [ 1.0,  0.0,  0.0],
    [ 0.0,  1.0,  0.0],
    [ 0.0,  0.0,  1.0],
], dtype=jnp.float64)


def _B_from_JinvT(JinvT_c: Array, dtype) -> Array:
    return jnp.einsum('eij,aj->eai', JinvT_c.astype(dtype), _GRAD_HAT.astype(dtype))


def _compute_JinvT_from_coords(x_e: Array, dtype) -> Array:
    x0 = x_e[:, 0, :]
    J = jnp.stack([x_e[:, 1, :] - x0, x_e[:, 2, :] - x0, x_e[:, 3, :] - x0], axis=2)
    invJ = jnp.linalg.inv(J.astype(dtype))
    return jnp.swapaxes(invJ, 1, 2)


def make_energy_kernels(
    geom: TetGeom,
    A_lookup: Array,
    K1_lookup: Array,
    Js_lookup: Array,
    k_easy_lookup: Array,
    V_mag: float,
    *,
    chunk_elems: int = 200_000,
    assembly: Assembly = 'scatter',
    grad_backend: GradBackend = 'stored_grad_phi',
) -> Tuple[
    Callable[[Array, Array, Array], Tuple[Array, Array]],
    Callable[[Array, Array, Array], Array],
    Callable[[Array, Array, Array], Array],
]:

    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id

    # Inverse volume normalization
    inv_Vmag = 1.0 / V_mag

    if grad_backend == 'stored_grad_phi':
        if geom_p.grad_phi is None:
            raise ValueError('stored_grad_phi requires geom.grad_phi')
        grad_phi = geom_p.grad_phi
        JinvT = None
        x_nodes = None
    elif grad_backend == 'stored_JinvT':
        if geom_p.JinvT is None:
            raise ValueError('stored_JinvT requires geom.JinvT')
        grad_phi = None
        JinvT = geom_p.JinvT
        x_nodes = None
    else:
        if geom_p.x_nodes is None:
            raise ValueError('on_the_fly requires geom.x_nodes')
        grad_phi = None
        JinvT = None
        x_nodes = geom_p.x_nodes

    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems

    A_lookup = jnp.asarray(A_lookup)
    K1_lookup = jnp.asarray(K1_lookup)
    Js_lookup = jnp.asarray(Js_lookup)
    k_easy_lookup = jnp.asarray(k_easy_lookup)

    def _get_B(conn_c: Array, s: int, dtype) -> Array:
        if grad_backend == 'stored_grad_phi':
            return lax.dynamic_slice(grad_phi, (s, 0, 0), (chunk_elems, 4, 3)).astype(dtype)
        elif grad_backend == 'stored_JinvT':
            JinvT_c = lax.dynamic_slice(JinvT, (s, 0, 0), (chunk_elems, 3, 3)).astype(dtype)
            return _B_from_JinvT(JinvT_c, dtype)
        else:
            x_e = x_nodes[conn_c].astype(dtype)
            JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
            return _B_from_JinvT(JinvT_c, dtype)

    def energy_and_grad(m: Array, U: Array, B_ext: Array) -> Tuple[Array, Array]:
        N = m.shape[0]
        dtype = m.dtype
        # B_ext is expected to be reduced: b_ext = B_ext / Js_ref
        B_ext = jnp.asarray(B_ext, dtype=dtype)

        def body(i, carry):
            E_acc, g_acc = carry
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)

            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask

            g_ids = mat_c - 1
            # Reduced properties (from loop.py):
            # a_c = A / Kd,  q_c = K1 / Kd,  j_c = Js / Js_ref
            a_c = A_lookup[g_ids].astype(dtype)
            q_c = K1_lookup[g_ids].astype(dtype)
            j_c = Js_lookup[g_ids].astype(dtype)
            k_c = k_easy_lookup[g_ids].astype(dtype)

            m_e = m[conn_c]
            U_e = U[conn_c]

            # Exchange
            G = jnp.einsum('eal,eak->elk', m_e, B_c)
            E_ex = jnp.sum(a_c * Ve_eff * jnp.sum(G * G, axis=(1, 2)))
            Km = jnp.einsum('elk,egk->egl', G, B_c)
            contrib = (2.0 * a_c * Ve_eff)[:, None, None] * Km

            # Uniaxial anisotropy
            v_e = jnp.einsum('eac,ec->ea', m_e, k_c)
            sum_v = jnp.sum(v_e, axis=1)
            sum_v2 = jnp.sum(v_e * v_e, axis=1)
            quad = (sum_v * sum_v + sum_v2) * (Ve_eff / 20.0)
            E_an = jnp.sum(-q_c * quad)
            Mv = (Ve_eff / 20.0)[:, None] * (sum_v[:, None] + v_e)
            factor = (-2.0 * q_c)[:, None] * Mv
            contrib = contrib + factor[..., None] * k_c[:, None, :]

            # Zeeman: E_z = -2 * integral( j_c * m . b_ext ) dV
            sum_m = jnp.sum(m_e, axis=1)
            sum_m_dot_B = jnp.einsum('ec,c->e', sum_m, B_ext)
            E_z = jnp.sum(-2.0 * j_c * Ve_eff * 0.25 * sum_m_dot_B)
            scale_z = (-2.0 * j_c * Ve_eff / 4.0)[:, None, None]
            contrib = contrib + jnp.broadcast_to(scale_z * B_ext[None, None, :], (chunk_elems, 4, 3))

            # Demag: E_dem = - integral( j_c * m . b_dem ) dV, b_dem = -grad(U)
            B_dem = -jnp.einsum('ea,eak->ek', U_e, B_c)
            m_avg = 0.25 * sum_m
            E_dem = jnp.sum(-1.0 * j_c * Ve_eff * jnp.einsum('ec,ec->e', m_avg, B_dem))
            scale_dem = (-1.0 * j_c * Ve_eff / 4.0)[:, None, None]
            contrib = contrib + jnp.broadcast_to(scale_dem * B_dem[:, None, :], (chunk_elems, 4, 3))

            if assembly == 'scatter':
                g_acc = assemble_scatter(g_acc, conn_c, contrib)
            else:
                g_acc = g_acc + assemble_segment_sum(N, conn_c, contrib, dtype)

            return (E_acc + (E_ex + E_an + E_z + E_dem), g_acc)

        E0 = jnp.array(0.0, dtype=dtype)
        g0 = jnp.zeros((N, 3), dtype=dtype)
        E_total, g_total = lax.fori_loop(0, n_chunks, body, (E0, g0))
        return E_total * inv_Vmag, g_total * inv_Vmag

    def energy_only(m: Array, U: Array, B_ext: Array) -> Array:
        dtype = m.dtype
        B_ext = jnp.asarray(B_ext, dtype=dtype)

        def body(i, E_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)

            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask

            g_ids = mat_c - 1
            a_c = A_lookup[g_ids].astype(dtype)
            q_c = K1_lookup[g_ids].astype(dtype)
            j_c = Js_lookup[g_ids].astype(dtype)
            k_c = k_easy_lookup[g_ids].astype(dtype)

            m_e = m[conn_c]
            U_e = U[conn_c]

            G = jnp.einsum('eal,eak->elk', m_e, B_c)
            E_ex = jnp.sum(a_c * Ve_eff * jnp.sum(G * G, axis=(1, 2)))

            v_e = jnp.einsum('eac,ec->ea', m_e, k_c)
            sum_v = jnp.sum(v_e, axis=1)
            sum_v2 = jnp.sum(v_e * v_e, axis=1)
            quad = (sum_v * sum_v + sum_v2) * (Ve_eff / 20.0)
            E_an = jnp.sum(-q_c * quad)

            sum_m = jnp.sum(m_e, axis=1)
            sum_m_dot_B = jnp.einsum('ec,c->e', sum_m, B_ext)
            E_z = jnp.sum(-2.0 * j_c * Ve_eff * 0.25 * sum_m_dot_B)

            B_dem = -jnp.einsum('ea,eak->ek', U_e, B_c)
            m_avg = 0.25 * sum_m
            E_dem = jnp.sum(-1.0 * j_c * Ve_eff * jnp.einsum('ec,ec->e', m_avg, B_dem))

            return E_acc + (E_ex + E_an + E_z + E_dem)

        E0 = jnp.array(0.0, dtype=m.dtype)
        return lax.fori_loop(0, n_chunks, body, E0) * inv_Vmag

    def grad_only(m: Array, U: Array, B_ext: Array) -> Array:
        N = m.shape[0]
        dtype = m.dtype
        B_ext = jnp.asarray(B_ext, dtype=dtype)

        def body(i, g_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s, 0), (chunk_elems, 4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)

            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask

            g_ids = mat_c - 1
            a_c = A_lookup[g_ids].astype(dtype)
            q_c = K1_lookup[g_ids].astype(dtype)
            j_c = Js_lookup[g_ids].astype(dtype)
            k_c = k_easy_lookup[g_ids].astype(dtype)

            m_e = m[conn_c]
            U_e = U[conn_c]

            G = jnp.einsum('eal,eak->elk', m_e, B_c)
            Km = jnp.einsum('elk,egk->egl', G, B_c)
            contrib = (2.0 * a_c * Ve_eff)[:, None, None] * Km

            v_e = jnp.einsum('eac,ec->ea', m_e, k_c)
            sum_v = jnp.sum(v_e, axis=1)
            Mv = (Ve_eff / 20.0)[:, None] * (sum_v[:, None] + v_e)
            factor = (-2.0 * q_c)[:, None] * Mv
            contrib = contrib + factor[..., None] * k_c[:, None, :]

            scale_z = (-2.0 * j_c * Ve_eff / 4.0)[:, None, None]
            contrib = contrib + jnp.broadcast_to(scale_z * B_ext[None, None, :], (chunk_elems, 4, 3))

            B_dem = -jnp.einsum('ea,eak->ek', U_e, B_c)
            scale_dem = (-1.0 * j_c * Ve_eff / 4.0)[:, None, None]
            contrib = contrib + jnp.broadcast_to(scale_dem * B_dem[:, None, :], (chunk_elems, 4, 3))

            if assembly == 'scatter':
                g_acc = assemble_scatter(g_acc, conn_c, contrib)
            else:
                g_acc = g_acc + assemble_segment_sum(N, conn_c, contrib, dtype)

            return g_acc

        g0 = jnp.zeros((N, 3), dtype=dtype)
        return lax.fori_loop(0, n_chunks, body, g0) * inv_Vmag

    return jax.jit(energy_and_grad), jax.jit(energy_only), jax.jit(grad_only)
