"""fem_utils.py

Core FEM utilities and data container.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional, Tuple

import jax
import jax.numpy as jnp

Array = jnp.ndarray


@dataclass(frozen=True)
class TetGeom:
    conn: Array
    volume: Array
    mat_id: Array
    grad_phi: Optional[Array] = None
    JinvT: Optional[Array] = None
    x_nodes: Optional[Array] = None


def pad_to_multiple(x: Array, multiple: int, pad_value=0) -> Array:
    n = x.shape[0]
    rem = n % multiple
    if rem == 0:
        return x
    pad = multiple - rem
    pad_width = [(0, pad)] + [(0, 0)] * (x.ndim - 1)
    return jnp.pad(x, pad_width, constant_values=pad_value)


def pad_geom_for_chunking(geom: TetGeom, chunk_elems: int) -> Tuple[TetGeom, int]:
    """Pad element axis to a multiple of chunk_elems.

    conn/volume/mat_id are always padded.
    grad_phi and JinvT are padded if present.
    x_nodes is not padded.

    Returns (geom_padded, E_original).
    """
    E_orig = int(geom.conn.shape[0])

    conn = pad_to_multiple(geom.conn.astype(jnp.int32), chunk_elems, pad_value=0)
    volume = pad_to_multiple(geom.volume, chunk_elems, pad_value=0.0)
    mat_id = pad_to_multiple(geom.mat_id.astype(jnp.int32), chunk_elems, pad_value=1)

    grad_phi = pad_to_multiple(geom.grad_phi, chunk_elems, pad_value=0.0) if geom.grad_phi is not None else None
    JinvT = pad_to_multiple(geom.JinvT, chunk_elems, pad_value=0.0) if geom.JinvT is not None else None

    return TetGeom(conn=conn, volume=volume, mat_id=mat_id, grad_phi=grad_phi, JinvT=JinvT, x_nodes=geom.x_nodes), E_orig


def chunk_mask(E_orig: int, start_e: int, chunk_elems: int, dtype) -> Array:
    j = jnp.arange(chunk_elems, dtype=jnp.int32)
    valid = (jnp.int32(start_e) + j) < jnp.int32(E_orig)
    return valid.astype(dtype)


def assemble_scatter(g_acc: Array, conn_c: Array, contrib: Array) -> Array:
    return g_acc.at[conn_c].add(contrib)


def assemble_segment_sum(N: int, conn_c: Array, contrib: Array, dtype) -> Array:
    idx = conn_c.reshape(-1)
    val = contrib.reshape(-1, 3)
    return jax.ops.segment_sum(val, idx, N).astype(dtype)
