"""hysteresis_loop.py

Hysteresis loop driver.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict, Literal, Optional

import numpy as np
import jax.numpy as jnp

from fem_utils import TetGeom
from curvilinear_bb_minimizer import make_minimizer
from io_utils import ensure_dir, write_hysteresis_header, append_hysteresis_row, compute_volume_averaged_M_parallel, write_vtu_tetra

GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']


@dataclass
class LoopParams:
    h_dir: np.ndarray
    B_start: float
    B_end: float
    dB: float
    loop: bool = True

    gamma: int = 5
    max_iter: int = 200
    tol_grad: float = 1e-6
    tau0: float = 1e-2
    tau_min: float = 1e-6
    tau_max: float = 1.0

    ls_eta1: float = 0.1
    ls_eta2: float = 0.1
    ls_C: float = 2.0
    ls_c: float = 0.5
    ls_s0: float = 1.0
    ls_max_evals: int = 15

    out_dir: str = 'hyst_out'
    csv_name: str = 'hysteresis.csv'
    snapshot_every: int = 1


def _field_values(H_start: float, H_end: float, dH: float, loop: bool) -> np.ndarray:
    if dH == 0:
        raise ValueError('dH must be nonzero')
    if (H_end - H_start) * dH < 0:
        dH = -dH
    n = int(np.floor((H_end - H_start) / dH + 1e-12))
    vals_up = H_start + dH * np.arange(n + 1)
    if abs(vals_up[-1] - H_end) > 1e-12 * max(1.0, abs(H_end)):
        vals_up = np.append(vals_up, H_end)
    if not loop:
        return vals_up
    return np.concatenate([vals_up, vals_up[-2::-1]])


def run_hysteresis_loop(
    *,
    points: np.ndarray,
    geom: TetGeom,
    A_lookup: np.ndarray,
    K1_lookup: np.ndarray,
    Js_lookup: np.ndarray,
    k_easy_lookup: np.ndarray,
    m0: np.ndarray,
    params: LoopParams,
    energy_assembly: str = 'scatter',
    grad_backend: GradBackend = 'stored_grad_phi',
    chunk_elems: int = 200_000,
    cg_maxiter: int = 400,
    cg_tol: float = 1e-8,
    poisson_reg: float = 1e-12,
    agg_id: Optional[np.ndarray] = None,
    inv_sqrt_counts: Optional[np.ndarray] = None,
) -> Dict[str, object]:

    out_dir = ensure_dir(params.out_dir)
    csv_path = out_dir / params.csv_name
    write_hysteresis_header(csv_path)

    h = np.asarray(params.h_dir, dtype=np.float64)
    h /= np.linalg.norm(h) + 1e-30

    agg_id_j = None if agg_id is None else jnp.asarray(agg_id, dtype=jnp.int32)
    inv_sqrt_j = None if inv_sqrt_counts is None else jnp.asarray(inv_sqrt_counts, dtype=jnp.float64)

    minimize = make_minimizer(
        geom,
        A_lookup=jnp.asarray(A_lookup, dtype=jnp.float64),
        K1_lookup=jnp.asarray(K1_lookup, dtype=jnp.float64),
        Js_lookup=jnp.asarray(Js_lookup, dtype=jnp.float64),
        k_easy_lookup=jnp.asarray(k_easy_lookup, dtype=jnp.float64),
        chunk_elems=chunk_elems,
        energy_assembly=energy_assembly,
        cg_maxiter=cg_maxiter,
        cg_tol=cg_tol,
        poisson_reg=poisson_reg,
        grad_backend=grad_backend,
        agg_id=agg_id_j,
        inv_sqrt_counts=inv_sqrt_j,
    )

    m = jnp.asarray(m0, dtype=jnp.float64)
    m = m / jnp.linalg.norm(m, axis=1, keepdims=True)

    B_vals = _field_values(params.B_start, params.B_end, params.dB, params.loop)

    for step_idx, Bmag in enumerate(B_vals):
        B_ext = jnp.asarray(Bmag * h, dtype=jnp.float64)
        m, U, info = minimize(
            m,
            B_ext,
            gamma=params.gamma,
            max_iter=params.max_iter,
            tol_grad=params.tol_grad,
            tau0=params.tau0,
            tau_min=params.tau_min,
            tau_max=params.tau_max,
            ls_eta1=params.ls_eta1,
            ls_eta2=params.ls_eta2,
            ls_C=params.ls_C,
            ls_c=params.ls_c,
            ls_s0=params.ls_s0,
            ls_max_evals=params.ls_max_evals,
            verbose=False,
        )

        m_np = np.array(m)
        Jpar = compute_volume_averaged_M_parallel(
            m_np,
            np.array(geom.conn),
            np.array(geom.volume),
            np.array(geom.mat_id),
            np.array(Js_lookup),
            h,
        )

        append_hysteresis_row(csv_path, float(Bmag), float(Jpar), float(info.get('E', np.nan)) / 1e27, float(info.get('gnorm', np.nan)))

        if params.snapshot_every > 0 and (step_idx % params.snapshot_every == 0):
            vtu_path = out_dir / f"state_{step_idx:05d}_B{Bmag:+.6e}.vtu"
            write_vtu_tetra(
                vtu_path,
                points,
                np.array(geom.conn),
                point_data={'m': np.array(m).astype(np.float32), 'U': np.array(U).astype(np.float32)},
                cell_data={'mat_id': np.array(geom.mat_id).astype(np.int32)},
            )

        print(f"step {step_idx:05d}  B={Bmag:+.6e}  J_par={Jpar:+.6e}  E={info.get('E', float('nan')) / 1e27:.6e}")

    return {'out_dir': str(out_dir), 'csv_path': str(csv_path), 'last_m': np.array(m), 'last_U': np.array(U)}
