"""hysteresis_loop.py.

Driver module for running micromagnetic hysteresis loop simulations.
Handles field sweeps, energy minimization at each step, and result export.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

import time
from dataclasses import dataclass
from typing import Any, Literal

import jax
import jax.numpy as jnp
import numpy as np

from energy_kernels import make_energy_kernels
from fem_utils import TetGeom
from io_utils import (
    append_hysteresis_row,
    ensure_dir,
    write_hysteresis_header,
    write_vtu_tetra,
)
from minimizers import make_minimizer
from poisson_solve import make_solve_U

GradBackend = Literal["stored_grad_phi", "stored_JinvT", "on_the_fly"]


@dataclass
class LoopParams:
    """Parameters for controlling the hysteresis loop field sweep and solver.

    Attributes:
        h_dir (np.ndarray): Direction vector of the applied field.
        B_start (float): Starting field magnitude (reduced units).
        B_end (float): Final field magnitude (reduced units).
        dB (float): Field step size (reduced units).
        loop (bool): If True, run a full loop back to B_start. Defaults to True.
        gamma (int): Number of initial line-search steps in the minimizer.
        max_iter (int): Maximum minimizer iterations per field step.
        tau_f (float): Energy convergence tolerance.
        eps_a (float): Gradient norm convergence tolerance.
        tau0, tau_min, tau_max (float): Step size control for the minimizer.
        ls_eta1, ls_eta2, ls_C, ls_c, ls_s0, ls_max_evals: Line search parameters.
        out_dir (str): Directory for output files.
        csv_name (str): Filename for the hysteresis CSV data.
        snapshot_every (int): Frequency of VTU snapshots (0 to disable).
        verbose (bool): If True, print iteration details.
        Js_ref (float): Reference saturation polarization for SI conversion.
        cg_maxiter (int): Maximum iterations for the Poisson solver.
        cg_tol (float): Relative tolerance for the Poisson solver.
        poisson_reg (float): Regularization for the Poisson solver.
        mfinal (float | None): Magnetization threshold for early stopping.
        mstep (float | None): Magnetization change threshold for saving snapshots.
        bias_type (str | None): Type of symmetry-breaking field ('circular', 'random').
        bias_strength (float): Strength of the bias field relative to saturation.
        method (str): Minimizer algorithm (e.g., 'pcohen', 'pcohen_exact', 'lbfgs', 'wg').
        pc_iters (int): Inner iterations for preconditioned methods.
        pc_auto (bool): Enable adaptive preconditioning accuracy.
        pc_force_eta (float): Base constant for adaptive forcing sequence.
        pc_force_alpha (float): Exponent for adaptive forcing sequence.
        memory (int): History size for L-BFGS and Anderson acceleration.
        tn_iters (int): Inner iterations for Newton-CG solvers.
        lr (float): Learning rate for Nesterov acceleration.
        mu (float): Momentum factor for Nesterov acceleration.
    """

    h_dir: np.ndarray
    B_start: float
    B_end: float
    dB: float
    loop: bool = True

    gamma: int = 5
    max_iter: int = 2000
    tau_f: float = 1e-8
    eps_a: float = 1e-12
    tau0: float = 1e-2
    tau_min: float = 1e-6
    tau_max: float = 1.0

    ls_eta1: float = 0.1
    ls_eta2: float = 0.1
    ls_C: float = 2.0
    ls_c: float = 0.5
    ls_s0: float = 1.0
    ls_max_evals: int = 15

    out_dir: str = "hyst_out"
    csv_name: str = "hysteresis.csv"
    snapshot_every: int = 1
    verbose: bool = False
    Js_ref: float = 1.0
    cg_maxiter: int = 2000
    cg_tol: float = 1e-8
    poisson_reg: float = 1e-12
    mfinal: float | None = None
    mstep: float | None = None
    bias_type: str | None = None
    bias_strength: float = 0.0

    # Advanced Minimizer Defaults (P-Cohen Auto Strict)
    method: str = "pcohen_hs"
    pc_iters: int = 15
    pc_auto: bool = True
    pc_force_eta: float = 0.5
    pc_force_alpha: float = 0.5
    pc_stagnation_nu: float = 0.01
    memory: int = 5
    tn_iters: int = 5
    lr: float = 0.1
    mu: float = 0.9
    pc_reg: float = 0.0
    phi_extrapolate: bool = True
    wg_gamma: int = 5
    wg_threshold: float = 1e-6


def _field_values(H_start: float, H_end: float, dH: float, loop: bool) -> np.ndarray:
    """Generate the sequence of field magnitudes for the sweep.

    Args:
        H_start (float): Starting field.
        H_end (float): Final field for the first pass.
        dH (float): Field step size.
        loop (bool): If True, append the return path to H_start.

    Returns:
        np.ndarray: Array of field magnitudes.
    """
    if dH == 0:
        raise ValueError("dH must be nonzero")
    if (H_end - H_start) * dH < 0:
        dH = -dH
    n = int(np.floor((H_end - H_start) / dH + 1e-12))
    vals_up = H_start + dH * np.arange(n + 1)
    if abs(vals_up[-1] - H_end) > 1e-12 * max(1.0, abs(H_end)):
        vals_up = np.append(vals_up, H_end)
    if not loop:
        return vals_up
    return np.concatenate([vals_up, vals_up[-2::-1]])


@jax.jit
def jax_compute_volume_averaged_J_parallel(
    m_nodes: jnp.ndarray,
    conn: jnp.ndarray,
    volume: jnp.ndarray,
    mat_id: jnp.ndarray,
    Js_lookup: jnp.ndarray,
    h_dir: jnp.ndarray,
) -> jnp.ndarray:
    """Compute volume-averaged magnetic polarization parallel to h_dir (JAX version).

    Args:
        m_nodes (jnp.ndarray): Nodal unit magnetization vectors.
        conn (jnp.ndarray): Tetrahedron connectivity.
        volume (jnp.ndarray): Element volumes.
        mat_id (jnp.ndarray): Element material IDs.
        Js_lookup (jnp.ndarray): Saturation polarization table.
        h_dir (jnp.ndarray): Field direction vector.

    Returns:
        jnp.ndarray: Scalar averaged polarization component.
    """
    h = h_dir / (jnp.linalg.norm(h_dir) + 1e-30)

    # Average m over tets
    m_e = m_nodes[conn]  # (E, 4, 3)
    m_avg = jnp.mean(m_e, axis=1)  # (E, 3)

    # Material properties
    Js_e = Js_lookup[mat_id - 1]  # (E,)
    J_e = Js_e[:, None] * m_avg  # (E, 3)

    # Magnetic volume (only where Js > 0)
    Vmag = jnp.sum(jnp.where(Js_e > 0, volume, 0.0)) + 1e-30

    # Volume average
    J_avg = jnp.sum(volume[:, None] * J_e, axis=0) / Vmag
    return jnp.dot(J_avg, h)


def jax_compute_volume_averaged_m(
    m_nodes: jnp.ndarray,
    conn: jnp.ndarray,
    volume: jnp.ndarray,
    mat_id: jnp.ndarray,
    Js_lookup: jnp.ndarray,
) -> jnp.ndarray:
    """Compute volume-averaged magnetization components (mx, my, mz) (JAX version).

    Only averages over magnetic material regions (Js > 0).

    Args:
        m_nodes (jnp.ndarray): Nodal unit magnetization vectors.
        conn (jnp.ndarray): Tetrahedron connectivity.
        volume (jnp.ndarray): Element volumes.
        mat_id (jnp.ndarray): Element material IDs.
        Js_lookup (jnp.ndarray): Saturation polarization table.

    Returns:
        jnp.ndarray: Average unit vector (3,).
    """
    # Average m over tets
    m_e = m_nodes[conn]  # (E, 4, 3)
    m_avg = jnp.mean(m_e, axis=1)  # (E, 3)

    # Material properties: only average over magnetic parts
    Js_e = Js_lookup[mat_id - 1]  # (E,)
    Vmag = jnp.sum(jnp.where(Js_e > 0, volume, 0.0)) + 1e-30

    m_vol_avg = jnp.sum(jnp.where(Js_e[:, None] > 0, volume[:, None] * m_avg, 0.0), axis=0) / Vmag
    return m_vol_avg


def run_hysteresis_loop(
    points: np.ndarray,
    geom: TetGeom,
    A_lookup: np.ndarray,
    K1_lookup: np.ndarray,
    Js_lookup: np.ndarray,
    k_easy_lookup: np.ndarray,
    m0: np.ndarray,
    params: LoopParams,
    V_mag: float,
    node_volumes: jnp.ndarray,
    M_nodal: jnp.ndarray,
    B_bias: np.ndarray | None = None,
    precond_type: str = "jacobi",
    order: int = 3,
    energy_assembly: str = "segment_sum",
    grad_backend: GradBackend = "stored_grad_phi",
    chunk_elems: int = 200_000,
    boundary_mask: jnp.ndarray | None = None,
    *,
    mode: str = "matrix_free",
    A_sparse: Any = None,
    Dx_sparse: Any = None,
    Dy_sparse: Any = None,
    Dz_sparse: Any = None,
    A_diag: Any = None,
    Kex_sparse: Any = None,
    Gx_sparse: Any = None,
    Gy_sparse: Any = None,
    Gz_sparse: Any = None,
    Kan_sparse: Any = None,
    k_nodes: Any = None,
    Kex_diag: Any = None,
) -> dict[str, Any]:
    """Execute the full hysteresis loop simulation.

    Args:
        points (np.ndarray): Mesh node coordinates.
        geom (TetGeom): Geometry data.
        A_lookup (np.ndarray): Exchange constants.
        K1_lookup (np.ndarray): Anisotropy constants.
        Js_lookup (np.ndarray): Saturation polarization constants.
        k_easy_lookup (np.ndarray): Easy axis vectors.
        m0 (np.ndarray): Initial magnetization vector.
        params (LoopParams): sweep and solver settings.
        V_mag (float): Magnetic volume.
        node_volumes (Array): Nodal volume vector.
        M_nodal (Array): Nodal magnetic moment scaling.
        B_bias (np.ndarray | None): Bias field.
        precond_type (str): Preconditioning strategy.
        order (int): Chebyshev preconditioner order.
        energy_assembly (str): Nodal assembly strategy.
        grad_backend (GradBackend): shape function gradients source.
        chunk_elems (int): Chunk size for loops.
        boundary_mask (Array | None): Boundary mask.
        mode (str): Operator mode ('matrix_free' or 'assembled').
        A_sparse: Assembled stiffness matrix.
        Dx_sparse, Dy_sparse, Dz_sparse: Assembled divergence component matrices.
        A_diag: Precomputed diagonal of A.
        Kex_sparse: Assembled exchange matrix.
        Gx_sparse, Gy_sparse, Gz_sparse: Assembled demag gradient component matrices.
        Kan_sparse: Assembled anisotropy matrix.
        k_nodes: Precomputed easy axis per node.
        Kex_diag: Precomputed diagonal of Kex.
    """
    out_dir = ensure_dir(params.out_dir)
    csv_path = out_dir / params.csv_name
    write_hysteresis_header(csv_path)

    h = np.asarray(params.h_dir, dtype=np.float64)
    h /= np.linalg.norm(h) + 1e-30

    energy_and_grad, energy_only, _, _ = make_energy_kernels(
        geom,
        A_lookup=jnp.asarray(A_lookup, dtype=jnp.float64),
        K1_lookup=jnp.asarray(K1_lookup, dtype=jnp.float64),
        Js_lookup=jnp.asarray(Js_lookup, dtype=jnp.float64),
        k_easy_lookup=jnp.asarray(k_easy_lookup, dtype=jnp.float64),
        V_mag=V_mag,
        M_nodal=M_nodal,
        chunk_elems=chunk_elems,
        assembly=energy_assembly,
        grad_backend=grad_backend,
        mode=mode,
        Kex_sparse=Kex_sparse,
        Gx_sparse=Gx_sparse,
        Gy_sparse=Gy_sparse,
        Gz_sparse=Gz_sparse,
        Kan_sparse=Kan_sparse,
        k_nodes=k_nodes,
    )

    solve_U = make_solve_U(
        geom,
        jnp.asarray(Js_lookup, dtype=jnp.float64),
        precond_type=precond_type,
        order=order,
        chunk_elems=chunk_elems,
        cg_maxiter=params.cg_maxiter,
        cg_tol=params.cg_tol,
        poisson_reg=params.poisson_reg,
        grad_backend=grad_backend,
        boundary_mask=boundary_mask,
        mode=mode,
        A_sparse=A_sparse,
        Dx_sparse=Dx_sparse,
        Dy_sparse=Dy_sparse,
        Dz_sparse=Dz_sparse,
        A_diag=A_diag,
    )

    minimize = make_minimizer(
        geom,
        A_lookup=jnp.asarray(A_lookup, dtype=jnp.float64),
        K1_lookup=jnp.asarray(K1_lookup, dtype=jnp.float64),
        Js_lookup=jnp.asarray(Js_lookup, dtype=jnp.float64),
        k_easy_lookup=jnp.asarray(k_easy_lookup, dtype=jnp.float64),
        V_mag=V_mag,
        node_volumes=node_volumes,
        M_nodal=M_nodal,
        solve_U=solve_U,
        cg_tol=params.cg_tol,
        method=params.method,
        B_bias=jnp.asarray(B_bias, dtype=jnp.float64) if B_bias is not None else None,
        chunk_elems=chunk_elems,
        energy_assembly=energy_assembly,
        grad_backend=grad_backend,
        mode=mode,
        Kex_sparse=Kex_sparse,
        Gx_sparse=Gx_sparse,
        Gy_sparse=Gy_sparse,
        Gz_sparse=Gz_sparse,
        Kan_sparse=Kan_sparse,
        k_nodes=k_nodes,
        Kex_diag=Kex_diag,
    )

    m = jnp.asarray(m0, dtype=jnp.float64)
    m = m / jnp.linalg.norm(m, axis=1, keepdims=True)

    B_vals = _field_values(params.B_start, params.B_end, params.dB, params.loop)

    config_idx = 0
    J_par_last_saved = None
    history = []

    total_time = 0.0
    U = jnp.zeros(m.shape[0], dtype=m.dtype)
    for step_idx, Bmag in enumerate(B_vals):
        B_ext = jnp.asarray(Bmag * h, dtype=jnp.float64)

        start_step = time.time()
        m, U, info = minimize(
            m,
            B_ext,
            U0=U,
            gamma=params.gamma,
            max_iter=params.max_iter,
            tau_f=params.tau_f,
            eps_a=params.eps_a,
            tau0=params.tau0,
            tau_min=params.tau_min,
            tau_max=params.tau_max,
            ls_eta1=params.ls_eta1,
            ls_eta2=params.ls_eta2,
            ls_C=params.ls_C,
            ls_c=params.ls_c,
            ls_s0=params.ls_s0,
            ls_max_evals=params.ls_max_evals,
            h=h,
            mfinal=params.mfinal,
            Js_ref=params.Js_ref,
            verbose=params.verbose,
            pc_iters=params.pc_iters,
            pc_auto=params.pc_auto,
            pc_force_eta=params.pc_force_eta,
            pc_force_alpha=params.pc_force_alpha,
            pc_stagnation_nu=params.pc_stagnation_nu,
            memory=params.memory,
            tn_iters=params.tn_iters,
            lr=params.lr,
            mu=params.mu,
            pc_reg=params.pc_reg,
            phi_extrapolate=params.phi_extrapolate,
        )
        # Accurate timing: wait for GPU to finish
        m.block_until_ready()
        U.block_until_ready()
        step_duration = time.time() - start_step
        total_time += step_duration

        # Compute volume averages
        Jpar = jax_compute_volume_averaged_J_parallel(
            m,
            geom.conn,
            geom.volume,
            geom.mat_id,
            jnp.asarray(Js_lookup),
            jnp.asarray(h),
        )
        m_avg = jax_compute_volume_averaged_m(m, geom.conn, geom.volume, geom.mat_id, jnp.asarray(Js_lookup))

        B_tesla = float(Bmag) * params.Js_ref
        J_tesla = float(Jpar) * params.Js_ref
        mx, my, mz = map(float, m_avg)
        E_si = float(info.get("E", np.nan)) * (params.Js_ref**2) / (2.0 * 4e-7 * np.pi)

        # Record history row: (B_ext_T, J_par_T, mx, my, mz, E_si)
        history.append([B_tesla, J_tesla, mx, my, mz, E_si])

        # Snapshot trigger logic
        should_save = False
        if J_par_last_saved is None:
            # Always save the very first step
            should_save = True
        elif params.mstep is not None:
            if abs(Jpar - J_par_last_saved) >= params.mstep:
                should_save = True
        elif params.snapshot_every > 0 and (step_idx % params.snapshot_every) == 0:
            should_save = True

        if should_save:
            if J_par_last_saved is not None:
                config_idx += 1
            J_par_last_saved = Jpar

            if params.snapshot_every > 0:
                vtu_path = out_dir / f"state_cfg{config_idx:05d}_B{B_tesla:+.4e}T.vtu"
                write_vtu_tetra(
                    vtu_path,
                    points,
                    np.array(geom.conn),
                    point_data={
                        "m": np.array(m).astype(np.float32),
                        "U": np.array(U).astype(np.float32),
                    },
                    cell_data={"mat_id": np.array(geom.mat_id).astype(np.int32)},
                )

        append_hysteresis_row(
            csv_path,
            config_idx,
            B_tesla,
            J_tesla,
            float(info.get("E", np.nan)),
            float(info.get("gnorm", np.nan)),
        )

        print(
            f"step {step_idx:05d}  B={B_tesla:+.6e} T  J_par={J_tesla:+.6e} T  "
            f"E={info.get('E', float('nan')):.6e}  t={step_duration:.3f}s  "
            f"it={info.get('iters', 0):.0f}  "
            f"t/it={step_duration / max(1.0, info.get('iters', 1.0)):.3e}s  "
            f"nf={info.get('evals', info.get('nf', 0)):.0f}  "
            f"icg_amg={info.get('demag_iters', info.get('icg', 0)):.0f}"
        )

        # Early termination check
        if params.mfinal is not None and Jpar <= params.mfinal:
            print(
                f"\n[loop] mfinal reached ({J_tesla:.4f} T <= {params.mfinal * params.Js_ref:.4f} T). Stopping sweep."
            )
            break

    print(f"\nHysteresis loop finished in {total_time:.3f} s.")
    return {
        "out_dir": str(out_dir),
        "csv_path": str(csv_path),
        "last_m": np.array(m),
        "last_U": np.array(U),
        "history": np.array(history),
    }
