"""io_utils.py

Simple output utilities including ASCII VTU writer.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional, Sequence

import numpy as np


def ensure_dir(path: str | Path) -> Path:
    p = Path(path)
    p.mkdir(parents=True, exist_ok=True)
    return p


def write_hysteresis_header(csv_path: str | Path, extra_cols: Sequence[str] = ("E", "gnorm")) -> None:
    csv_path = Path(csv_path)
    cols = ["B_ext_T", "J_par_T"] + list(extra_cols)
    csv_path.write_text(",".join(cols) + "\n", encoding="utf-8")


def append_hysteresis_row(csv_path: str | Path, H: float, M_parallel: float, E: Optional[float] = None, gnorm: Optional[float] = None) -> None:
    csv_path = Path(csv_path)
    parts = [f"{H:.9e}", f"{M_parallel:.9e}"]
    if E is not None:
        parts.append(f"{E:.9e}")
    if gnorm is not None:
        parts.append(f"{gnorm:.9e}")
    with csv_path.open('a', encoding='utf-8') as f:
        f.write(",".join(parts) + "\n")


def write_mh(path: str | Path, records: np.ndarray) -> None:
    """Write mammos-mumag compatible .mh file."""
    path = Path(path).with_suffix(".mh")
    header = "B_ext [T]  J_parallel [T]  mx  my  mz  E [J/m^3]"
    with open(path, "w") as f:
        f.write("# " + header + " \n")
        np.savetxt(f, records, fmt="%.9e")


def compute_volume_averaged_J_parallel(m_nodes: np.ndarray, conn: np.ndarray, volume: np.ndarray, mat_id: np.ndarray, Js_lookup: np.ndarray, h_dir: np.ndarray) -> float:
    h = np.asarray(h_dir, dtype=np.float64)
    h /= np.linalg.norm(h) + 1e-30

    m_nodes = np.asarray(m_nodes, dtype=np.float64)
    conn = np.asarray(conn, dtype=np.int64)
    volume = np.asarray(volume, dtype=np.float64)
    mat_id = np.asarray(mat_id, dtype=np.int64)
    Js_lookup = np.asarray(Js_lookup, dtype=np.float64)

    m_e = m_nodes[conn]
    m_avg = m_e.mean(axis=1)
    Js_e = Js_lookup[mat_id - 1]
    J_e = Js_e[:, None] * m_avg

    # Normalize by magnetic volume
    Vmag = volume[Js_e > 0].sum() + 1e-30
    J_avg = (volume[:, None] * J_e).sum(axis=0) / Vmag
    return float(J_avg.dot(h))


def _vtk_type(arr: np.ndarray) -> str:
    if arr.dtype == np.float32:
        return "Float32"
    if arr.dtype == np.float64:
        return "Float64"
    if arr.dtype == np.int32:
        return "Int32"
    if arr.dtype == np.int64:
        return "Int64"
    if arr.dtype == np.uint8:
        return "UInt8"
    if np.issubdtype(arr.dtype, np.integer):
        return "Int32"
    return "Float32"


def write_vtu_tetra(path: str | Path, points: np.ndarray, tets: np.ndarray, *, point_data: Optional[Dict[str, np.ndarray]] = None, cell_data: Optional[Dict[str, np.ndarray]] = None) -> None:
    path = Path(path)
    point_data = point_data or {}
    cell_data = cell_data or {}

    pts = np.asarray(points)
    if pts.ndim != 2 or pts.shape[1] != 3:
        raise ValueError('points must have shape (N,3)')
    cells = np.asarray(tets)
    if cells.ndim != 2 or cells.shape[1] != 4:
        raise ValueError('tets must have shape (E,4)')

    N = pts.shape[0]
    E = cells.shape[0]

    pts = pts.astype(np.float32, copy=False)
    conn = cells.astype(np.int32, copy=False).reshape(-1)
    offsets = (np.arange(1, E + 1, dtype=np.int32) * 4)
    types = np.full((E,), 10, dtype=np.uint8)

    def fmt(a: np.ndarray) -> str:
        return " ".join(map(str, a.reshape(-1).tolist()))

    lines = []
    lines.append('<?xml version="1.0"?>')
    lines.append('<VTKFile type="UnstructuredGrid" version="0.1" byte_order="LittleEndian">')
    lines.append('  <UnstructuredGrid>')
    lines.append(f'    <Piece NumberOfPoints="{N}" NumberOfCells="{E}">')

    lines.append('      <Points>')
    lines.append(f'        <DataArray type="{_vtk_type(pts)}" NumberOfComponents="3" format="ascii">')
    lines.append('          ' + fmt(pts))
    lines.append('        </DataArray>')
    lines.append('      </Points>')

    lines.append('      <Cells>')
    lines.append('        <DataArray type="Int32" Name="connectivity" format="ascii">')
    lines.append('          ' + fmt(conn))
    lines.append('        </DataArray>')
    lines.append('        <DataArray type="Int32" Name="offsets" format="ascii">')
    lines.append('          ' + fmt(offsets))
    lines.append('        </DataArray>')
    lines.append('        <DataArray type="UInt8" Name="types" format="ascii">')
    lines.append('          ' + fmt(types))
    lines.append('        </DataArray>')
    lines.append('      </Cells>')

    lines.append('      <PointData>')
    for name, arr in point_data.items():
        a = np.asarray(arr)
        if a.shape[0] != N:
            raise ValueError(f"PointData '{name}' length mismatch")
        ncomp = 1 if a.ndim == 1 else a.shape[1]
        a_out = a.astype(np.int32 if np.issubdtype(a.dtype, np.integer) else np.float32, copy=False)
        lines.append(f'        <DataArray type="{_vtk_type(a_out)}" Name="{name}" NumberOfComponents="{ncomp}" format="ascii">')
        lines.append('          ' + fmt(a_out))
        lines.append('        </DataArray>')
    lines.append('      </PointData>')

    lines.append('      <CellData>')
    for name, arr in cell_data.items():
        a = np.asarray(arr)
        if a.shape[0] != E:
            raise ValueError(f"CellData '{name}' length mismatch")
        ncomp = 1 if a.ndim == 1 else a.shape[1]
        a_out = a.astype(np.int32 if np.issubdtype(a.dtype, np.integer) else np.float32, copy=False)
        lines.append(f'        <DataArray type="{_vtk_type(a_out)}" Name="{name}" NumberOfComponents="{ncomp}" format="ascii">')
        lines.append('          ' + fmt(a_out))
        lines.append('        </DataArray>')
    lines.append('      </CellData>')

    lines.append('    </Piece>')
    lines.append('  </UnstructuredGrid>')
    lines.append('</VTKFile>')

    path.write_text("\n".join(lines), encoding='utf-8')
