"""loop.py.

Main driver script:
  1) Read a FEM mesh (.npz with knt, ijk)
  2) Optionally add a shell / airbox (using add_shell.py)
  3) Precompute geometry for FEM kernels (volume + JinvT or grad_phi) and build TetGeom
  4) Run hysteresis loop

Key option
----------
--geom-backend chooses how gradients are stored in TetGeom:
  - stored_JinvT     : store JinvT (E,3,3), compute grad_phi on the fly
  - stored_grad_phi  : store grad_phi (E,4,3)

The same value is passed to run_hysteresis_loop via --grad-backend.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import jax
import jax.numpy as jnp
import numpy as np

import add_shell
from fem_utils import TetGeom
from hysteresis_loop import LoopParams, run_hysteresis_loop
from io_utils import write_mh


def parse_inp_with_data(path: str):
    """Parses an AVS UCD (.inp) file including cell data.

    Args:
        path (str): Path to the .inp file.

    Returns:
        tuple[np.ndarray, np.ndarray, dict[str, np.ndarray]]:
            (Nodes, Elements, Cell Data).
    """
    print(f"Parsing INP file: {path}")
    with open(path) as f:
        header = f.readline().split()
        if not header:
            return None, None, {}
        num_nodes, num_elems = int(header[0]), int(header[1])
        num_node_data, num_cell_data = int(header[2]), int(header[3])

        nodes = np.zeros((num_nodes, 3))
        for i in range(num_nodes):
            line = f.readline().split()
            nodes[i] = [float(x) for x in line[1:4]]

        elements = np.zeros((num_elems, 5))
        for i in range(num_elems):
            line = f.readline().split()
            mat_id = int(line[1])
            nids = [int(x) - 1 for x in line[3:]]  # 0-based
            elements[i, :4] = nids
            elements[i, 4] = mat_id

        cell_data = {}
        if num_cell_data > 0:
            # Skip node data if present
            if num_node_data > 0:
                f.readline()  # Header
                for _ in range(num_node_data):
                    f.readline()  # Labels
                for _ in range(num_nodes):
                    f.readline()  # Values

            # Read cell data
            header_cd = f.readline().split()
            num_vars = int(header_cd[0])
            labels = []
            for _ in range(num_vars):
                labels.append(f.readline().split(",")[0].strip())

            # Initialize data arrays
            for label in labels:
                cell_data[label] = np.zeros(num_elems)

            # Read values
            for _ in range(num_elems):
                line = f.readline().split()
                eid_idx = int(line[0]) - 1
                for j, label in enumerate(labels):
                    cell_data[label][eid_idx] = float(line[j + 1])

    return nodes, elements, cell_data


jax.config.update("jax_enable_x64", True)

# Reference tetra gradients
_GRAD_HAT = np.array(
    [
        [-1.0, -1.0, -1.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ],
    dtype=np.float64,
)


def compute_volume_JinvT(
    knt: np.ndarray, conn: np.ndarray
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compute volume and inverse Jacobian transpose for P1 tetrahedra.

    Ensures positive orientation by swapping nodes (1,2) for elements
    with negative Jacobians.

    Args:
        knt (np.ndarray): Node coordinates (N, 3).
        conn (np.ndarray): Element connectivity (E, 4).

    Returns:
        tuple[np.ndarray, np.ndarray, np.ndarray]: (Oriented connectivity,
                                                   Volumes, JinvT).
    """
    knt = np.asarray(knt, dtype=np.float64)
    conn = np.asarray(conn, dtype=np.int64)

    x0 = knt[conn[:, 0]]
    J = np.stack(
        [knt[conn[:, 1]] - x0, knt[conn[:, 2]] - x0, knt[conn[:, 3]] - x0], axis=2
    )
    detJ = np.linalg.det(J)

    neg = detJ < 0
    if np.any(neg):
        conn = conn.copy()
        tmp = conn[neg, 1].copy()
        conn[neg, 1] = conn[neg, 2]
        conn[neg, 2] = tmp
        x0 = knt[conn[:, 0]]
        J = np.stack(
            [knt[conn[:, 1]] - x0, knt[conn[:, 2]] - x0, knt[conn[:, 3]] - x0], axis=2
        )
        detJ = np.linalg.det(J)

    volume = np.abs(detJ) / 6.0
    invJ = np.linalg.inv(J)
    JinvT = np.swapaxes(invJ, 1, 2)
    return conn.astype(np.int32), volume.astype(np.float64), JinvT.astype(np.float64)


def compute_grad_phi_from_JinvT(JinvT: np.ndarray) -> np.ndarray:
    """Compute shape function gradients from the inverse Jacobian transpose.

    Args:
        JinvT (np.ndarray): Inverse Jacobian transpose (E, 3, 3).

    Returns:
        np.ndarray: Shape function gradients (E, 4, 3).
    """
    return np.einsum("eij,aj->eai", JinvT, _GRAD_HAT)


def bunge_to_axes(phi1: float, Phi: float, phi2: float) -> np.ndarray:
    """Convert Bunge Euler angles (Z-X-Z passive intrinsic) to crystal axes.

    The rows of the returned 3x3 matrix are the crystal axes (ex, ey, ez)
    expressed in the laboratory coordinate system.

    Args:
        phi1 (float): First rotation about Z (radians).
        Phi (float): Second rotation about X' (radians).
        phi2 (float): Third rotation about Z'' (radians).

    Returns:
        np.ndarray: 3x3 matrix where rows are [ex, ey, ez].
    """
    c1, s1 = np.cos(phi1), np.sin(phi1)
    cP, sP = np.cos(Phi), np.sin(Phi)
    c2, s2 = np.cos(phi2), np.sin(phi2)

    # Bunge matrix R (passive: v_crystal = R * v_lab)
    # The rows are the unit vectors of the crystal axes in the lab frame.
    # Row 0: ex_crystal in lab
    # Row 1: ey_crystal in lab
    # Row 2: ez_crystal in lab
    R = np.array(
        [
            [
                c1 * c2 - s1 * s2 * cP,
                s1 * c2 + c1 * s2 * cP,
                s2 * sP,
            ],
            [
                -c1 * s2 - s1 * c2 * cP,
                -s1 * s2 + c1 * c2 * cP,
                c2 * sP,
            ],
            [
                s1 * sP,
                -c1 * sP,
                cP,
            ],
        ],
        dtype=np.float64,
    )
    return R


def load_materials_krn(
    krn_path: str, G: int, mesh_unit: float = 1e-9, shell_added: bool = False
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Read intrinsic magnetic properties from a MaMMoS .krn file.

    Supports two orientation formats:
    - 2-angle header (6/8 columns): theta, phi, K1, K1p, Js, A, ...
    - 3-angle header (9+ columns): phi1, Phi, phi2, K1, K1p, Js, A, ...

    If shell_added is True, the last material group (G) is treated as air
    automatically and should not have a line in the .krn file.

    Args:
        krn_path (str): Path to the .krn file.
        G (int): Number of material groups in the mesh.
        mesh_unit (float, optional): Physical length of one mesh unit in meters.
            Used to scale the exchange constant A. Defaults to 1e-9 (nm).
        shell_added (bool): If True, group G is air and not in the .krn file.

    Returns:
        tuple[
            np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray
        ]: (A, K1, K1p, Js, axes_lookup).
            axes_lookup has shape (G, 3, 3) where axes_lookup[g, i, :] is axis i.
    """
    data = np.loadtxt(krn_path)
    if data.ndim == 1:
        data = data[None, :]

    n_rows = data.shape[0]
    n_cols = data.shape[1]

    # Required rows in .krn
    G_required = G - 1 if shell_added else G

    # strict material id check
    if n_rows < G_required:
        raise ValueError(
            f"The .krn file '{krn_path}' has {n_rows} rows, but the mesh has {G} "
            f"material groups ({'including' if shell_added else 'no'} added airbox). "
            "Every material ID in the mesh must have a corresponding line in "
            "the .krn file."
        )
    if n_rows > G_required:
        raise ValueError(
            f"The .krn file '{krn_path}' has {n_rows} rows, but the mesh only "
            f"requires {G_required} material definitions. Unused lines are not allowed."
        )

    # Initialize arrays for G material groups
    A = np.zeros(G, dtype=np.float64)
    K1 = np.zeros(G, dtype=np.float64)
    K1p = np.zeros(G, dtype=np.float64)
    Js = np.zeros(G, dtype=np.float64)
    axes_lookup = np.zeros((G, 3, 3), dtype=np.float64)
    for g in range(G):
        axes_lookup[g] = np.eye(3)

    # Only fill up to what we have in the file (G_required)
    n_fill = G_required

    # Detection logic based on column counts:
    # 6 or 8 columns -> Spherical (theta, phi, K1, K1p, Js, A)
    # 7 or 9 columns -> Bunge (phi1, Phi, phi2, K1, K1p, Js, A)
    if n_cols in (7, 9):
        # Bunge Euler format
        phi1 = data[:n_fill, 0]
        Phi = data[:n_fill, 1]
        phi2 = data[:n_fill, 2]
        K1[:n_fill] = data[:n_fill, 3]
        K1p[:n_fill] = data[:n_fill, 4]
        Js[:n_fill] = data[:n_fill, 5]
        A_val = data[:n_fill, 6]

        for i in range(n_fill):
            axes_lookup[i] = bunge_to_axes(phi1[i], Phi[i], phi2[i])
    elif n_cols in (6, 8):
        # Classic spherical format
        theta = data[:n_fill, 0]
        phi = data[:n_fill, 1]
        K1[:n_fill] = data[:n_fill, 2]
        K1p[:n_fill] = data[:n_fill, 3]
        Js[:n_fill] = data[:n_fill, 4]
        A_val = data[:n_fill, 5]
        for i in range(n_fill):
            # ez from spherical
            ez = np.array(
                [
                    np.sin(theta[i]) * np.cos(phi[i]),
                    np.sin(theta[i]) * np.sin(phi[i]),
                    np.cos(theta[i]),
                ]
            )
            # Construct orthogonal ex, ey
            if abs(ez[0]) < 0.9:
                ex = np.cross(ez, [1, 0, 0])
            else:
                ex = np.cross(ez, [0, 1, 0])
            ex /= np.linalg.norm(ex) + 1e-30
            ey = np.cross(ez, ex)
            axes_lookup[i] = np.stack([ex, ey, ez], axis=0)
    else:
        raise ValueError(
            f"Unsupported .krn format with {n_cols} columns. "
            f"Expected 6 or 8 (Spherical) or 7 or 9 (Bunge)."
        )

    A_scale = (1.0 / mesh_unit) ** 2
    A[:n_fill] = A_val * A_scale

    return A, K1, K1p, Js, axes_lookup


def load_params_p2(p2_path: str | Path) -> dict[str, Any]:
    """Basic parser for MaMMoS-mumag .p2 configuration files.

    Extracts field sweep parameters and minimizer tolerances.

    Args:
        p2_path (str | Path): Path to the .p2 file.

    Returns:
        dict[str, Any]: Dictionary of configuration overrides.
    """
    import configparser

    config = configparser.ConfigParser()
    config.read(p2_path)

    overrides = {}
    if "mesh" in config:
        m = config["mesh"]
        if "size" in m:
            overrides["mesh_unit"] = float(m["size"])

    if "field" in config:
        f = config["field"]
        # Support both 'h' csv and individual 'hx','hy','hz'
        if "h" in f:
            h_vec = np.array([float(x) for x in f["h"].split(",")])
            overrides["h_dir"] = h_vec / (np.linalg.norm(h_vec) + 1e-30)
        elif any(k in f for k in ("hx", "hy", "hz")):
            hx = float(f.get("hx", 0.0))
            hy = float(f.get("hy", 0.0))
            hz = float(f.get("hz", 0.0))
            h_vec = np.array([hx, hy, hz])
            overrides["h_dir"] = h_vec / (np.linalg.norm(h_vec) + 1e-30)

        if "hstart" in f:
            overrides["B_start"] = float(f["hstart"])
        if "hfinal" in f:
            overrides["B_end"] = float(f["hfinal"])
        if "hstep" in f:
            overrides["dB"] = float(f["hstep"])
        if "mfinal" in f:
            overrides["mfinal"] = float(f["mfinal"])
        if "mstep" in f:
            overrides["mstep"] = float(f["mstep"])
        if "loop" in f:
            overrides["loop"] = f.getboolean("loop")
        if "no_demag" in f:
            overrides["no_demag"] = f.getboolean("no_demag")

    if "initial state" in config:
        m_sec = config["initial state"]
        if all(k in m_sec for k in ("mx", "my", "mz")):
            mx = float(m_sec["mx"])
            my = float(m_sec["my"])
            mz = float(m_sec["mz"])
            m0_vec = np.array([mx, my, mz])
            m0_vec /= np.linalg.norm(m0_vec) + 1e-30
            overrides["m0_dir"] = f"{m0_vec[0]},{m0_vec[1]},{m0_vec[2]}"

    if "minimizer" in config:
        m_min = config["minimizer"]
        if "tol_fun" in m_min:
            overrides["tau_f"] = float(m_min["tol_fun"])
        if "tol_grad" in m_min:
            overrides["eps_a"] = float(m_min["tol_grad"])
        if "max_iter" in m_min:
            overrides["max_iter"] = int(m_min["max_iter"])

    if "poisson" in config:
        p = config["poisson"]
        if "cg_maxiter" in p:
            overrides["cg_maxiter"] = int(p["cg_maxiter"])

    return overrides


def load_materials(
    mat_path: str | None,
    G: int,
    mesh_path: str | None = None,
    mesh_unit: float = 1e-9,
    shell_added: bool = False,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load intrinsic magnetic properties for G materials.

    Priority:
    1. Explicitly provided .krn file.
    2. Automatic .krn discovery based on the mesh base name.
    3. Default properties (generic hard magnetic material).

    Args:
        mat_path (str | None): Explicit path to a .krn file.
        G (int): Number of material groups.
        mesh_path (str | None): Path to the mesh file (for discovery).
        mesh_unit (float, optional): Length of one mesh unit in meters.
            Defaults to 1e-9.
        shell_added (bool): If True, group G is air automatically.

    Returns:
        tuple[
            np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray
        ]: (A, K1, K1p, Js, axes_lookup).
    """
    # Priority 1: Explicitly provided materials KRN
    if mat_path is not None:
        return load_materials_krn(
            mat_path, G, mesh_unit=mesh_unit, shell_added=shell_added
        )

    # Priority 2: Automatic .krn discovery based on mesh name
    if mesh_path is not None:
        krn_path = Path(mesh_path).with_suffix(".krn")
        if krn_path.exists():
            print(f"[materials] Found auto-krn: {krn_path}")
            return load_materials_krn(
                str(krn_path), G, mesh_unit=mesh_unit, shell_added=shell_added
            )

    # Priority 3: Default (NdFeB-like)
    A_scale = (1.0 / mesh_unit) ** 2
    A = np.ones((G,), dtype=np.float64) * 1e-11 * A_scale
    K1 = np.zeros((G,), dtype=np.float64)
    K1p = np.zeros((G,), dtype=np.float64)
    Js = np.ones((G,), dtype=np.float64)  # 1.0 Tesla
    axes_lookup = np.zeros((G, 3, 3), dtype=np.float64)
    for g in range(G):
        axes_lookup[g] = np.eye(3)
    return A, K1, K1p, Js, axes_lookup


def main() -> None:
    """Main CLI entry point for the micromagnetics hysteresis driver.

    Orchestrates the entire simulation pipeline:
    - Mesh loading and optional shell addition.
    - Material and configuration loading.
    - Precomputing geometry.
    - Running the hysteresis loop.
    - Exporting results.
    """
    ap = argparse.ArgumentParser(
        description="Micromagnetics hysteresis driver with shell + preprocessing."
    )
    ap.add_argument(
        "modelname",
        nargs="?",
        help="Base name of the model (positional, for mammos-mumag compatibility).",
    )
    ap.add_argument("--mesh", help="Input NPZ mesh (knt, ijk).")

    # shell parameters
    ap.add_argument(
        "--add-shell",
        action="store_true",
        help="Add an airbox shell around the core mesh.",
    )
    ap.add_argument(
        "--layers", type=int, default=4, help="Number of graded shell layers (>= 1)."
    )
    ap.add_argument(
        "--K",
        type=float,
        default=1.3,
        help="Geometric growth factor for shell layer thickness (> 1).",
    )
    ap.add_argument(
        "--beta",
        type=float,
        default=1.0,
        help="Mesh-size/geometry coupling exponent (default 1.0 for linear scaling).",
    )
    ap.add_argument(
        "--center",
        type=str,
        default="0,0,0",
        help='Ray origin for shell expansion as "cx,cy,cz" (mesh units).',
    )
    ap.add_argument(
        "--h0",
        type=float,
        default=None,
        help="Target edge length near the body surface (mesh units).",
    )
    ap.add_argument(
        "--hmax",
        type=float,
        default=None,
        help="Target edge length at the outermost shell boundary (mesh units).",
    )
    ap.add_argument(
        "--minratio",
        type=float,
        default=1.4,
        help="TetGen quality minratio (-q) for shell tetrahedra.",
    )
    ap.add_argument(
        "--max-steiner",
        type=int,
        default=None,
        help="Limit the number of Steiner points added by TetGen.",
    )
    ap.add_argument(
        "--no-exact",
        action="store_true",
        help="Suppress exact arithmetic in TetGen (-X).",
    )
    ap.add_argument(
        "--shell-verbose",
        action="store_true",
        help="Enable verbose output from the shell generation pipeline.",
    )

    # materials
    ap.add_argument(
        "--materials",
        type=str,
        default=None,
        help="Path to a .krn file with intrinsic properties "
        "(theta, phi, K1, K1p, Js, A, ...) per material group.",
    )

    # preconditioning
    ap.add_argument(
        "--precond-type",
        type=str,
        default="amgcl",
        choices=["jacobi", "chebyshev", "amg", "amgcl"],
        help="Poisson solver preconditioner: amgcl (default), jacobi, "
        "chebyshev, or amg.",
    )

    # gradient backend selection

    ap.add_argument(
        "--geom-backend",
        type=str,
        default="stored_JinvT",
        choices=["stored_JinvT", "stored_grad_phi", "on_the_fly"],
        help="Strategy for providing gradient info: "
        "stored_JinvT (efficient storage), stored_grad_phi (precomputed), "
        "or on_the_fly (recompute from coordinates).",
    )

    # solver settings
    ap.add_argument(
        "--chunk-elems",
        type=int,
        default=200_000,
        help="Number of elements processed per loop iteration "
        "(chunking to control GPU memory).",
    )
    ap.add_argument(
        "--cg-maxiter",
        type=int,
        default=400,
        help="Maximum iterations for the Poisson PCG solver.",
    )
    ap.add_argument(
        "--cg-tol",
        type=float,
        default=1e-8,
        help="Relative residual tolerance for the Poisson PCG solver.",
    )
    ap.add_argument(
        "--poisson-reg",
        type=float,
        default=1e-12,
        help="Tikhonov regularization constant for the Poisson operator diagonal.",
    )

    ap.add_argument(
        "--no-demag",
        action="store_true",
        help="Disable magnetostatic (demagnetization) energy and skip Poisson solving.",
    )

    # loop settings
    ap.add_argument(
        "--h-dir",
        type=str,
        default="0,0,1",
        help='Applied field direction as unit vector "hx,hy,hz".',
    )
    ap.add_argument(
        "--B-start",
        type=float,
        default=-1.0,
        help="Starting magnitude of the applied field (Tesla).",
    )
    ap.add_argument(
        "--B-end",
        type=float,
        default=1.0,
        help="Final magnitude of the applied field (Tesla).",
    )
    ap.add_argument(
        "--dB", type=float, default=0.05, help="Field step size magnitude (Tesla)."
    )
    ap.add_argument(
        "--tau-f",
        type=float,
        default=1e-6,
        help="Relative energy convergence tolerance for the minimizer.",
    )
    ap.add_argument(
        "--eps-a",
        type=float,
        default=1e-12,
        help="Absolute tangent gradient norm tolerance for the "
        "minimizer (reduced units).",
    )
    ap.add_argument(
        "--max-iter",
        type=int,
        default=100_000,
        help="Maximum minimizer iterations per field step.",
    )

    ap.add_argument(
        "--out-dir",
        type=str,
        default="hyst_out",
        help="Directory for saving results and snapshots.",
    )
    ap.add_argument(
        "--snapshot-every",
        type=int,
        default=1,
        help="Save VTU snapshots every N steps (0 to disable).",
    )
    ap.add_argument(
        "--m0-dir",
        type=str,
        default=None,
        help='Initial magnetization direction "mx,my,mz". Defaults to field direction.',
    )
    ap.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed minimizer iterations at each step.",
    )

    args = ap.parse_args()

    # Automatic file discovery if modelname is provided
    modelname = args.modelname
    if modelname:
        if args.mesh is None:
            # Check for .npz first, then .inp
            npz_path = Path(modelname).with_suffix(".npz")
            inp_path = Path(modelname).with_suffix(".inp")
            if npz_path.exists():
                args.mesh = str(npz_path)
            elif inp_path.exists():
                args.mesh = str(inp_path)
            else:
                args.mesh = str(npz_path)  # Default to .npz for error message
        if args.materials is None:
            krn_path = Path(modelname).with_suffix(".krn")
            if krn_path.exists():
                args.materials = str(krn_path)
        if args.out_dir == "hyst_out":
            args.out_dir = f"hyst_{modelname}"

    if args.mesh is None:
        ap.error("the following arguments are required: --mesh or modelname")

    k1me_raw = None
    k1mep_raw = None

    if args.mesh.lower().endswith(".inp"):
        knt, ijk, cell_data = parse_inp_with_data(args.mesh)
        # Check for k1me / k1me_p or kme / kmep labels
        k1me_raw = cell_data.get("k1me", cell_data.get("kme"))
        k1mep_raw = cell_data.get("k1me_p", cell_data.get("kmep"))
    else:
        data = np.load(args.mesh)
        knt = np.asarray(data["knt"], dtype=np.float64)
        ijk = np.asarray(data["ijk"])

    if ijk.ndim != 2 or ijk.shape[1] not in (4, 5):
        raise ValueError("ijk must have shape (E,4) or (E,5)")

    if ijk.shape[1] == 4:
        mat_id = np.ones((ijk.shape[0],), dtype=np.int32)
        conn = ijk.astype(np.int64)
    else:
        conn = ijk[:, :4].astype(np.int64)
        mat_id = ijk[:, 4].astype(np.int32)
        if mat_id.min() == 0:
            mat_id = mat_id + 1

    shell_added = False
    if args.add_shell:
        shell_added = True
        tmp_npz = Path(args.mesh).with_suffix(".tmp_body.npz")
        np.savez(
            tmp_npz,
            knt=knt,
            ijk=np.column_stack([conn.astype(np.int32), mat_id.astype(np.int32)]),
        )

        knt, ijk_shell = add_shell.run_add_shell_pipeline(
            in_npz=str(tmp_npz),
            layers=args.layers,
            K=args.K,
            beta=args.beta,
            center=args.center,
            h0=args.h0,
            hmax=args.hmax,
            minratio=args.minratio,
            max_steiner=args.max_steiner,
            no_exact=args.no_exact,
            verbose=args.shell_verbose,
        )
        # Cleanup temporary body file
        if tmp_npz.exists():
            tmp_npz.unlink()

        ijk_shell = np.asarray(ijk_shell)
        conn = ijk_shell[:, :4].astype(np.int64)
        mat_id = ijk_shell[:, 4].astype(np.int32)

        # Update per-element arrays to match the new mesh if shell was added
        # (Shell elements get 0.0 for k1me)
        if k1me_raw is not None:
            new_k1me = np.zeros(conn.shape[0])
            new_k1me[: k1me_raw.shape[0]] = k1me_raw
            k1me_raw = new_k1me
        if k1mep_raw is not None:
            new_k1mep = np.zeros(conn.shape[0])
            new_k1mep[: k1mep_raw.shape[0]] = k1mep_raw
            k1mep_raw = new_k1mep

    G = int(mat_id.max())

    # Load .p2 overrides early to get mesh_unit
    p2_overrides = {}
    if modelname:
        p2_path = Path(modelname).with_suffix(".p2")
        if p2_path.exists():
            print(f"[config] Loading overrides from {p2_path}")
            p2_overrides = load_params_p2(p2_path)

    mesh_unit = p2_overrides.get("mesh_unit", 1e-9)
    A_lookup, K1_lookup, K1p_lookup, Js_lookup, axes_lookup = load_materials(
        args.materials,
        G,
        mesh_path=args.mesh,
        mesh_unit=mesh_unit,
        shell_added=shell_added,
    )

    # Use volume from compute_volume_JinvT later, but we need V_mag now or soon.
    # Let's compute volume and JinvT now.
    conn32, volume, JinvT = compute_volume_JinvT(knt, conn)

    # Calculate magnetic volume (V_mag)
    # Only groups with Js > 0 are considered magnetic.
    is_mag = np.isin(mat_id, np.where(Js_lookup > 0)[0] + 1)
    V_mag = np.sum(volume[is_mag])
    if V_mag == 0:
        V_mag = 1.0

    # Normalization: Kd = Js^2 / (2 * mu0)
    Js_ref = np.max(Js_lookup)
    if Js_ref == 0:
        Js_ref = 1.0
    MU0_SI = 4e-7 * np.pi
    Kd_ref = (Js_ref**2) / (2.0 * MU0_SI)

    # Reduced properties:
    A_red = A_lookup / Kd_ref
    K1_red = K1_lookup / Kd_ref
    K1p_red = K1p_lookup / Kd_ref
    Js_red = Js_lookup / Js_ref

    # Reduce per-element magnetoelastic arrays
    k1me_red = None
    k1mep_red = None
    if k1me_raw is not None:
        k1me_red = jnp.asarray(k1me_raw / Kd_ref, dtype=jnp.float64)
    if k1mep_raw is not None:
        k1mep_red = jnp.asarray(k1mep_raw / Kd_ref, dtype=jnp.float64)

    # Build TetGeom depending on backend
    grad_backend = args.geom_backend

    if grad_backend == "on_the_fly":
        geom = TetGeom(
            conn=jnp.asarray(conn32, dtype=jnp.int32),
            volume=jnp.asarray(volume, dtype=jnp.float64),
            mat_id=jnp.asarray(mat_id, dtype=jnp.int32),
            x_nodes=jnp.asarray(knt, dtype=jnp.float64),
        )
    else:
        if grad_backend == "stored_grad_phi":
            grad_phi = compute_grad_phi_from_JinvT(JinvT)
            geom = TetGeom(
                conn=jnp.asarray(conn32, dtype=jnp.int32),
                volume=jnp.asarray(volume, dtype=jnp.float64),
                mat_id=jnp.asarray(mat_id, dtype=jnp.int32),
                grad_phi=jnp.asarray(grad_phi, dtype=jnp.float64),
                JinvT=None,
                x_nodes=None,
            )
        else:
            geom = TetGeom(
                conn=jnp.asarray(conn32, dtype=jnp.int32),
                volume=jnp.asarray(volume, dtype=jnp.float64),
                mat_id=jnp.asarray(mat_id, dtype=jnp.int32),
                JinvT=jnp.asarray(JinvT, dtype=jnp.float64),
                grad_phi=None,
                x_nodes=None,
            )

    # Initial magnetization
    # Priority: p2 override > CLI --m0-dir > CLI --h-dir
    m0_str = p2_overrides.get("m0_dir", args.m0_dir)
    if m0_str:
        m0_vec = np.array([float(x) for x in m0_str.split(",")], dtype=np.float64)
    else:
        m0_vec = np.array([float(x) for x in args.h_dir.split(",")], dtype=np.float64)

    m0_vec = m0_vec / (np.linalg.norm(m0_vec) + 1e-30)
    m0 = np.tile(m0_vec[None, :], (knt.shape[0], 1))

    h_dir = np.array([float(x) for x in args.h_dir.split(",")], dtype=np.float64)
    h_dir = h_dir / (np.linalg.norm(h_dir) + 1e-30)

    # Dirichlet boundary mask (U=0 at outer boundary)
    mask_np = add_shell.find_outer_boundary_mask(conn, knt.shape[0])
    boundary_mask = jnp.asarray(mask_np, dtype=jnp.float64)

    # Preconditioning: compute lumped node volumes and magnetic moments M_nodal
    from fem_utils import compute_node_volumes

    node_vols = compute_node_volumes(geom, chunk_elems=int(args.chunk_elems))

    # Precompute nodal moments M (M_i = sum_e Js_red[e] * Ve / 4)
    # This is used for Zeeman energy/gradient and as a physical preconditioner
    vol_Js = volume * Js_red[mat_id - 1]
    from dataclasses import replace

    geom_Js = replace(geom, volume=jnp.asarray(vol_Js))
    M_nodal = compute_node_volumes(geom_Js, chunk_elems=int(args.chunk_elems))

    params_dict = {
        "h_dir": h_dir,
        "B_start": float(args.B_start) / Js_ref,
        "B_end": float(args.B_end) / Js_ref,
        "dB": float(args.dB) / Js_ref,
        "tau_f": float(args.tau_f),
        "eps_a": float(args.eps_a),
        "max_iter": int(args.max_iter),
        "loop": True,
        "out_dir": args.out_dir,
        "snapshot_every": int(args.snapshot_every),
        "verbose": args.verbose,
        "Js_ref": float(Js_ref),
        "no_demag": args.no_demag,
    }

    # Apply overrides
    if p2_overrides:
        # Scale field values by Js_ref (they are provided in Tesla)
        if "B_start" in p2_overrides:
            p2_overrides["B_start"] /= Js_ref
        if "B_end" in p2_overrides:
            p2_overrides["B_end"] /= Js_ref
        if "dB" in p2_overrides:
            p2_overrides["dB"] /= Js_ref
        if "mfinal" in p2_overrides:
            p2_overrides["mfinal"] /= Js_ref
        if "mstep" in p2_overrides:
            p2_overrides["mstep"] /= Js_ref

        # Remove parameters handled separately
        p2_overrides.pop("mesh_unit", None)
        p2_overrides.pop("m0_dir", None)

        params_dict.update(p2_overrides)

    params = LoopParams(**params_dict)

    res = run_hysteresis_loop(
        points=knt,
        geom=geom,
        A_lookup=A_red,
        K1_lookup=K1_red,
        K1p_lookup=K1p_red,
        Js_lookup=Js_red,
        axes_lookup=axes_lookup,
        m0=m0,
        params=params,
        V_mag=float(V_mag),
        node_volumes=node_vols,
        M_nodal=M_nodal,
        precond_type=args.precond_type,
        grad_backend=grad_backend,
        chunk_elems=int(args.chunk_elems),
        cg_maxiter=int(args.cg_maxiter),
        cg_tol=float(args.cg_tol),
        poisson_reg=float(args.poisson_reg),
        boundary_mask=boundary_mask,
        no_demag=params.no_demag,
        k1me=k1me_red,
        k1me_p=k1mep_red,
    )

    # Write .mh file for mammos-mumag compatibility
    mh_name = modelname if modelname else "hysteresis"
    write_mh(Path(args.out_dir) / mh_name, res["history"])
    print(
        f"[ok] Wrote mammos-mumag compatibility file: {Path(args.out_dir) / mh_name}.mh"
    )


if __name__ == "__main__":
    main()
