"""loop.py.

Main driver script:
  1) Read a FEM mesh (.npz with knt, ijk)
  2) Optionally add a shell / airbox (using add_shell.py)
  3) Precompute geometry for FEM kernels (volume + JinvT or grad_phi) and build TetGeom
  4) Run hysteresis loop

Key option
----------
--geom-backend chooses how gradients are stored in TetGeom:
  - stored_JinvT     : store JinvT (E,3,3), compute grad_phi on the fly
  - stored_grad_phi  : store grad_phi (E,4,3)

The same value is passed to run_hysteresis_loop via --grad-backend.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import jax
import jax.numpy as jnp
import numpy as np

import add_shell
from fem_utils import TetGeom
from hysteresis_loop import LoopParams, run_hysteresis_loop
from io_utils import write_mh

jax.config.update("jax_enable_x64", True)

# Reference tetra gradients
_GRAD_HAT = np.array(
    [
        [-1.0, -1.0, -1.0],
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ],
    dtype=np.float64,
)


def compute_volume_JinvT(knt: np.ndarray, conn: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Compute volume and inverse Jacobian transpose for P1 tetrahedra.

    Ensures positive orientation by swapping nodes (1,2) for elements
    with negative Jacobians.

    Args:
        knt (np.ndarray): Node coordinates (N, 3).
        conn (np.ndarray): Element connectivity (E, 4).

    Returns:
        tuple[np.ndarray, np.ndarray, np.ndarray]: (Oriented connectivity,
                                                   Volumes, JinvT).
    """
    knt = np.asarray(knt, dtype=np.float64)
    conn = np.asarray(conn, dtype=np.int64)

    x0 = knt[conn[:, 0]]
    J = np.stack([knt[conn[:, 1]] - x0, knt[conn[:, 2]] - x0, knt[conn[:, 3]] - x0], axis=2)
    detJ = np.linalg.det(J)

    neg = detJ < 0
    if np.any(neg):
        conn = conn.copy()
        tmp = conn[neg, 1].copy()
        conn[neg, 1] = conn[neg, 2]
        conn[neg, 2] = tmp
        x0 = knt[conn[:, 0]]
        J = np.stack([knt[conn[:, 1]] - x0, knt[conn[:, 2]] - x0, knt[conn[:, 3]] - x0], axis=2)
        detJ = np.linalg.det(J)

    volume = np.abs(detJ) / 6.0
    invJ = np.linalg.inv(J)
    JinvT = np.swapaxes(invJ, 1, 2)
    return conn.astype(np.int32), volume.astype(np.float64), JinvT.astype(np.float64)


def compute_grad_phi_from_JinvT(JinvT: np.ndarray) -> np.ndarray:
    """Compute shape function gradients from the inverse Jacobian transpose.

    Args:
        JinvT (np.ndarray): Inverse Jacobian transpose (E, 3, 3).

    Returns:
        np.ndarray: Shape function gradients (E, 4, 3).
    """
    return np.einsum("eij,aj->eai", JinvT, _GRAD_HAT)


def load_materials_krn(
    krn_path: str, G: int, mesh_unit: float = 1e-9, shell_added: bool = False
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Read intrinsic magnetic properties from a MaMMoS .krn file.

    Expects columns: theta, phi, K1, K2, Js, A, ...

    If shell_added is True, the last material group (G) is treated as air
    automatically and should not have a line in the .krn file.

    Args:
        krn_path (str): Path to the .krn file.
        G (int): Number of material groups in the mesh.
        mesh_unit (float, optional): Physical length of one mesh unit in meters.
            Used to scale the exchange constant A. Defaults to 1e-9 (nm).
        shell_added (bool): If True, group G is air and not in the .krn file.

    Returns:
        tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: (A, K1, Js,
                                                               easy_axis).
    """
    data = np.loadtxt(krn_path)
    if data.ndim == 1:
        data = data[None, :]

    n_rows = data.shape[0]

    # Required rows in .krn
    G_required = G - 1 if shell_added else G

    # strict material id check
    if n_rows < G_required:
        raise ValueError(
            f"The .krn file '{krn_path}' has {n_rows} rows, but the mesh has {G} "
            f"material groups ({'including' if shell_added else 'no'} added airbox). "
            f"The .krn file must have {G_required} rows."
        )
    if n_rows > G_required:
        raise ValueError(
            f"The .krn file '{krn_path}' has {n_rows} rows, but the mesh only "
            f"requires {G_required} material definitions. Unused lines are not allowed."
        )

    # Initialize arrays for G material groups
    A = np.zeros(G, dtype=np.float64)
    K1 = np.zeros(G, dtype=np.float64)
    Js = np.zeros(G, dtype=np.float64)
    k_easy = np.zeros((G, 3), dtype=np.float64)
    k_easy[:, 2] = 1.0  # default easy axis along z

    # Only fill up to what we have in the file (G_required)
    n_fill = G_required

    theta = data[:n_fill, 0]
    phi = data[:n_fill, 1]
    K1[:n_fill] = data[:n_fill, 2]
    Js[:n_fill] = data[:n_fill, 4]

    A_scale = (1.0 / mesh_unit) ** 2
    A[:n_fill] = data[:n_fill, 5] * A_scale

    kx = np.sin(theta) * np.cos(phi)
    ky = np.sin(theta) * np.sin(phi)
    kz = np.cos(theta)
    k_easy[:n_fill] = np.column_stack([kx, ky, kz])

    return A, K1, Js, k_easy


def load_params_p2(p2_path: str | Path) -> dict[str, Any]:
    """Basic parser for MaMMoS-mumag .p2 configuration files.

    Extracts field sweep parameters and minimizer tolerances.

    Args:
        p2_path (str | Path): Path to the .p2 file.

    Returns:
        dict[str, Any]: Dictionary of configuration overrides.
    """
    import configparser

    config = configparser.ConfigParser()
    config.read(p2_path)

    overrides = {}
    if "mesh" in config:
        m = config["mesh"]
        if "size" in m:
            overrides["mesh_unit"] = float(m["size"])

    if "field" in config:
        f = config["field"]
        # Support both 'h' csv and individual 'hx','hy','hz'
        if "h" in f:
            h_vec = np.array([float(x) for x in f["h"].split(",")])
            overrides["h_dir"] = h_vec / (np.linalg.norm(h_vec) + 1e-30)
        elif any(k in f for k in ("hx", "hy", "hz")):
            hx = float(f.get("hx", 0.0))
            hy = float(f.get("hy", 0.0))
            hz = float(f.get("hz", 0.0))
            h_vec = np.array([hx, hy, hz])
            overrides["h_dir"] = h_vec / (np.linalg.norm(h_vec) + 1e-30)

        if "hstart" in f:
            overrides["B_start"] = float(f["hstart"])
        if "hfinal" in f:
            overrides["B_end"] = float(f["hfinal"])
        if "hstep" in f:
            overrides["dB"] = float(f["hstep"])
        if "mfinal" in f:
            overrides["mfinal"] = float(f["mfinal"])
        if "mstep" in f:
            overrides["mstep"] = float(f["mstep"])
        if "loop" in f:
            overrides["loop"] = f.getboolean("loop")
        if "bias_type" in f:
            overrides["bias_type"] = str(f["bias_type"])
        if "bias_strength" in f:
            overrides["bias_strength"] = float(f["bias_strength"])

    if "initial state" in config:
        m_sec = config["initial state"]
        if all(k in m_sec for k in ("mx", "my", "mz")):
            mx = float(m_sec["mx"])
            my = float(m_sec["my"])
            mz = float(m_sec["mz"])
            m0_vec = np.array([mx, my, mz])
            m0_vec /= np.linalg.norm(m0_vec) + 1e-30
            overrides["m0_dir"] = f"{m0_vec[0]},{m0_vec[1]},{m0_vec[2]}"

    if "minimizer" in config:
        m_min = config["minimizer"]
        if "tol_fun" in m_min:
            overrides["tau_f"] = float(m_min["tol_fun"])
        if "eps_a" in m_min:
            overrides["eps_a"] = float(m_min["eps_a"])
        if "max_iter" in m_min:
            overrides["max_iter"] = int(m_min["max_iter"])
        if "tau_min" in m_min:
            overrides["tau_min"] = float(m_min["tau_min"])
        if "tau0" in m_min:
            overrides["tau0"] = float(m_min["tau0"])
        if "tau_max" in m_min:
            overrides["tau_max"] = float(m_min["tau_max"])
        if "method" in m_min:
            overrides["method"] = str(m_min["method"])
        if "pc_iters" in m_min:
            overrides["pc_iters"] = int(m_min["pc_iters"])
        if "pc_auto" in m_min:
            overrides["pc_auto"] = m_min.getboolean("pc_auto")
        if "pc_force_eta" in m_min:
            overrides["pc_force_eta"] = float(m_min["pc_force_eta"])
        if "pc_force_alpha" in m_min:
            overrides["pc_force_alpha"] = float(m_min["pc_force_alpha"])
        if "pc_stagnation_nu" in m_min:
            overrides["pc_stagnation_nu"] = float(m_min["pc_stagnation_nu"])
        if "memory" in m_min:
            overrides["memory"] = int(m_min["memory"])
        if "tn_iters" in m_min:
            overrides["tn_iters"] = int(m_min["tn_iters"])
        if "lr" in m_min:
            overrides["lr"] = float(m_min["lr"])
        if "mu" in m_min:
            overrides["mu"] = float(m_min["mu"])
        if "pc_reg" in m_min:
            overrides["pc_reg"] = float(m_min["pc_reg"])
        if "wg_gamma" in m_min:
            overrides["wg_gamma"] = int(m_min["wg_gamma"])
        if "wg_threshold" in m_min:
            overrides["wg_threshold"] = float(m_min["wg_threshold"])
        if "phi_extrapolate" in m_min:
            overrides["phi_extrapolate"] = m_min.getboolean("phi_extrapolate")

    if "poisson" in config:
        p = config["poisson"]
        if "cg_maxiter" in p:
            overrides["cg_maxiter"] = int(p["cg_maxiter"])
        if "cg_tol" in p:
            overrides["cg_tol"] = float(p["cg_tol"])
        if "reg" in p:
            overrides["poisson_reg"] = float(p["reg"])

    return overrides


def load_materials(
    mat_path: str | None,
    G: int,
    mesh_path: str | None = None,
    mesh_unit: float = 1e-9,
    shell_added: bool = False,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Load intrinsic magnetic properties for G materials.

    Priority:
    1. Explicitly provided .krn file.
    2. Automatic .krn discovery based on the mesh base name.
    3. Default properties (generic hard magnetic material).

    Args:
        mat_path (str | None): Explicit path to a .krn file.
        G (int): Number of material groups.
        mesh_path (str | None): Path to the mesh file (for discovery).
        mesh_unit (float, optional): Length of one mesh unit in meters.
            Defaults to 1e-9.
        shell_added (bool): If True, group G is air automatically.

    Returns:
        tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]: (A, K1, Js,
                                                               easy_axis).
    """
    # Priority 1: Explicitly provided materials KRN
    if mat_path is not None:
        return load_materials_krn(mat_path, G, mesh_unit=mesh_unit, shell_added=shell_added)

    # Priority 2: Automatic .krn discovery based on mesh name
    if mesh_path is not None:
        krn_path = Path(mesh_path).with_suffix(".krn")
        if krn_path.exists():
            print(f"[materials] Found auto-krn: {krn_path}")
            return load_materials_krn(str(krn_path), G, mesh_unit=mesh_unit, shell_added=shell_added)

    # Priority 3: Default (NdFeB-like)
    A_scale = (1.0 / mesh_unit) ** 2
    A = np.ones((G,), dtype=np.float64) * 1e-11 * A_scale
    K1 = np.zeros((G,), dtype=np.float64)
    Js = np.ones((G,), dtype=np.float64)  # 1.0 Tesla
    k_easy = np.zeros((G, 3), dtype=np.float64)
    k_easy[:, 2] = 1.0
    return A, K1, Js, k_easy


def main() -> None:
    """Main CLI entry point for the micromagnetics hysteresis driver.

    Orchestrates the entire simulation pipeline:
    - Mesh loading and optional shell addition.
    - Material and configuration loading.
    - Precomputing geometry.
    - Running the hysteresis loop.
    - Exporting results.
    """
    ap = argparse.ArgumentParser(description="Micromagnetics hysteresis driver with shell + preprocessing.")
    ap.add_argument(
        "modelname",
        nargs="?",
        help="Base name of the model (positional, for mammos-mumag compatibility).",
    )
    ap.add_argument("--mesh", help="Input NPZ mesh (knt, ijk).")

    # shell parameters
    ap.add_argument(
        "--add-shell",
        action="store_true",
        help="Add an airbox shell around the core mesh.",
    )
    ap.add_argument(
        "--shell-type",
        type=str,
        default="hull",
        choices=["triangles", "hull"],
        help="Outer shell boundary type: copy original 'triangles' or use convex 'hull' (default).",
    )
    ap.add_argument("--layers", type=int, default=None, help="Number of graded shell layers (>= 1).")
    ap.add_argument(
        "--K",
        type=float,
        default=1.5,
        help="Geometric growth factor for shell layer thickness (> 1).",
    )
    ap.add_argument(
        "--KL",
        type=float,
        default=10.0,
        help="Total outermost geometric scale relative to body (> 1).",
    )
    ap.add_argument(
        "--auto-layers",
        action="store_true",
        help="Automatically compute the number of layers L given --KL and --K.",
    )
    ap.add_argument(
        "--beta",
        type=float,
        default=1.0,
        help="Mesh-size/geometry coupling exponent (default 1.0 for linear scaling).",
    )
    ap.add_argument(
        "--center",
        type=str,
        default="0,0,0",
        help='Ray origin for shell expansion as "cx,cy,cz" (mesh units).',
    )
    ap.add_argument(
        "--h0",
        type=float,
        default=None,
        help="Target edge length near the body surface (mesh units).",
    )
    ap.add_argument(
        "--hmax",
        type=float,
        default=None,
        help="Target edge length at the outermost shell boundary (mesh units).",
    )
    ap.add_argument(
        "--minratio",
        type=float,
        default=1.4,
        help="TetGen quality minratio (-q) for shell tetrahedra.",
    )
    ap.add_argument(
        "--max-steiner",
        type=int,
        default=None,
        help="Limit the number of Steiner points added by TetGen.",
    )
    ap.add_argument(
        "--no-exact",
        action="store_true",
        help="Suppress exact arithmetic in TetGen (-X).",
    )
    ap.add_argument(
        "--shell-verbose",
        action="store_true",
        help="Enable verbose output from the shell generation pipeline.",
    )

    # materials
    ap.add_argument(
        "--materials",
        type=str,
        default=None,
        help="Path to a .krn file with intrinsic properties (theta, phi, K1, K2, Js, A, ...) per material group.",
    )

    # preconditioning
    ap.add_argument(
        "--precond-type",
        type=str,
        default="amgcl",
        choices=["jacobi", "chebyshev", "amg", "amgcl"],
        help="Poisson solver preconditioner: amgcl (default), jacobi, chebyshev, or amg.",
    )

    # gradient backend selection

    ap.add_argument(
        "--geom-backend",
        type=str,
        default="stored_JinvT",
        choices=["stored_JinvT", "stored_grad_phi", "on_the_fly"],
        help="Strategy for providing gradient info: "
        "stored_JinvT (efficient storage), stored_grad_phi (precomputed), "
        "or on_the_fly (recompute from coordinates).",
    )

    # solver settings
    ap.add_argument(
        "--chunk-elems",
        type=int,
        default=200_000,
        help="Number of elements processed per loop iteration (chunking to control GPU memory).",
    )
    ap.add_argument(
        "--operator-mode",
        choices=["matrix_free", "assembled"],
        default="assembled",
        help="Solver operator execution mode: matrix_free (on-the-fly) or assembled (sparse matrix SpMV).",
    )
    ap.add_argument(
        "--cg-maxiter",
        type=int,
        default=2000,
        help="Maximum iterations for the Poisson PCG solver.",
    )
    ap.add_argument(
        "--cg-tol",
        type=float,
        default=1e-8,
        help="Relative residual tolerance for the Poisson PCG solver.",
    )
    ap.add_argument(
        "--poisson-reg",
        type=float,
        default=1e-12,
        help="Tikhonov regularization constant for the Poisson operator diagonal.",
    )
    ap.add_argument(
        "--cpu-spmv-backend",
        type=str,
        default="persistent_mkl",
        choices=["persistent_mkl", "dot_product_mkl", "scipy", "jax_default", "custom_jax", "mkl_ffi"],
        help="Backend for SpMV operations when running on CPU in assembled mode.",
    )
    ap.add_argument(
        "--poisson-solver",
        type=str,
        default="auto",
        choices=["auto", "jax", "pardiso", "jax_mkl"],
        help="Solver to use for the magnetostatic Poisson problem (default: auto).",
    )

    # loop settings
    ap.add_argument(
        "--h-dir",
        type=str,
        default="0,0,1",
        help='Applied field direction as unit vector "hx,hy,hz".',
    )
    ap.add_argument(
        "--B-start",
        type=float,
        default=-1.0,
        help="Starting magnitude of the applied field (Tesla).",
    )
    ap.add_argument(
        "--B-end",
        type=float,
        default=1.0,
        help="Final magnitude of the applied field (Tesla).",
    )
    ap.add_argument("--dB", type=float, default=0.05, help="Field step size magnitude (Tesla).")
    ap.add_argument(
        "--max-iter",
        type=int,
        default=2000,
        help="Maximum iterations for the energy minimizer per field step.",
    )
    ap.add_argument(
        "--L",
        type=int,
        default=None,
        help="Restart frequency for conjugate gradient methods (default: number of nodes).",
    )
    ap.add_argument(
        "--tau-f",
        type=float,
        default=1e-8,
        help="Relative energy convergence tolerance for the minimizer.",
    )
    ap.add_argument(
        "--eps-a",
        type=float,
        default=1e-12,
        help="Absolute tangent gradient norm tolerance for the minimizer (reduced units).",
    )
    ap.add_argument(
        "--tau0",
        type=float,
        default=1e-2,
        help="Initial step size guess for minimizers.",
    )
    ap.add_argument(
        "--tau-min",
        type=float,
        default=1e-6,
        help="Minimum step size allowed for the BB minimizer.",
    )
    ap.add_argument(
        "--tau-max",
        type=float,
        default=1.0,
        help="Maximum step size allowed for the BB minimizer.",
    )
    ap.add_argument(
        "--bias-type",
        type=str,
        default=None,
        choices=["circular", "random"],
        help="Type of symmetry-breaking field for mode initialization.",
    )
    ap.add_argument(
        "--bias-strength",
        type=float,
        default=0.0,
        help="Strength of the bias field relative to saturation (e.g., 0.01).",
    )

    # advanced minimizer options
    ap.add_argument(
        "--method",
        type=str,
        default="pcohen_hs",
        choices=[
            "cohen",
            "pcg",
            "pcohen",
            "pcohen_hs",
            "pcohen_exact",
            "pcohen_hs_exact",
            "lbfgs",
            "plbfgs",
            "dplbfgs",
            "tn_split",
            "wg_np",
            "tr",
            "aapg",
            "aapg_exact",
            "pnag",
            "pcohen_lbfgs",
            "ptr",
        ],
        help="Energy minimizer algorithm (default: pcohen).",
    )
    ap.add_argument(
        "--pc-iters",
        type=int,
        default=10,
        help="Inner iterations for preconditioning (default: 10).",
    )
    ap.add_argument(
        "--pc-auto",
        action="store_true",
        default=True,
        help="Enable automated tuning of preconditioning accuracy (default: True).",
    )
    ap.add_argument(
        "--pc-no-auto",
        action="store_false",
        dest="pc_auto",
        help="Disable automated tuning of preconditioning accuracy.",
    )
    ap.add_argument(
        "--pc-force-eta",
        type=float,
        default=0.5,
        help="Base forcing parameter for adaptive preconditioning (default: 0.5).",
    )
    ap.add_argument(
        "--pc-force-alpha",
        type=float,
        default=0.5,
        help="Exponent forcing parameter for adaptive preconditioning (default: 0.5).",
    )
    ap.add_argument(
        "--pc-stagnation-nu",
        type=float,
        default=0.01,
        help="Relative threshold for quadratic model stagnation detection (default: 0.01).",
    )
    ap.add_argument(
        "--memory",
        type=int,
        default=5,
        help="Memory/History size for L-BFGS and Anderson acceleration (default: 5).",
    )
    ap.add_argument(
        "--tn-iters",
        type=int,
        default=5,
        help="Inner iterations for Newton-CG solvers (default: 5).",
    )
    ap.add_argument(
        "--lr",
        type=float,
        default=0.1,
        help="Learning rate for Nesterov acceleration (default: 0.1).",
    )
    ap.add_argument(
        "--mu",
        type=float,
        default=0.9,
        help="Momentum factor for Nesterov acceleration (default: 0.9).",
    )

    ap.add_argument(
        "--pc-reg",
        type=float,
        default=0.0,
        help="Diagonal regularization shift for the preconditioner (default: 0.0).",
    )
    ap.add_argument(
        "--wg-gamma",
        type=int,
        default=5,
        help="Number of steps in convex region before switching to BB (default: 5).",
    )
    ap.add_argument(
        "--wg-threshold",
        type=float,
        default=1e-6,
        help="Convexity threshold (sty) for WG algorithm (default: 1e-6).",
    )
    ap.add_argument(
        "--phi-extrapolate",
        action="store_true",
        default=True,
        help="Enable linear extrapolation of scalar potential for faster Poisson solves (default: True).",
    )
    ap.add_argument(
        "--cpp-mkl",
        action=argparse.BooleanOptionalAction,
        default=None,
        help="Use the pure C++ MKL minimizer backend for the entire field step (default: True on CPU with MKL, False otherwise).",
    )
    ap.add_argument(
        "--no-phi-extrapolate",
        action="store_false",
        dest="phi_extrapolate",
        help="Disable linear extrapolation of scalar potential.",
    )
    ap.add_argument(
        "--data-parallel",
        action="store_true",
        default=False,
        help="Use SPMD Data Parallelism for multi-GPU instead of Operator Parallelism (default: False).",
    )
    ap.add_argument(
        "--out-dir",
        type=str,
        default="hyst_out",
        help="Directory for saving results and snapshots.",
    )
    ap.add_argument(
        "--snapshot-every",
        type=int,
        default=1,
        help="Save VTU snapshots every N steps (0 to disable).",
    )
    ap.add_argument(
        "--m0-dir",
        type=str,
        default=None,
        help='Initial magnetization direction "mx,my,mz". Defaults to field direction.',
    )
    ap.add_argument(
        "--verbose",
        action="store_true",
        help="Print detailed minimizer iterations at each step.",
    )
    ap.add_argument(
        "--benchmark",
        action="store_true",
        help="Run a dummy warmup step before the hysteresis loop to compile JIT functions.",
    )

    args = ap.parse_args()

    # Dynamic defaults based on platform
    try:
        has_gpu = any(d.platform == "gpu" for d in jax.devices())
    except Exception:
        has_gpu = False

    try:
        import ctypes

        ctypes.CDLL("libmkl_rt.so")
        has_mkl = True
    except OSError:
        has_mkl = False

    if args.cpp_mkl is None:
        args.cpp_mkl = not has_gpu and has_mkl

    if args.poisson_solver == "auto":
        args.poisson_solver = "pardiso" if (not has_gpu and has_mkl) else "jax"

    # Automatic file discovery if modelname is provided
    modelname = args.modelname
    if modelname:
        if args.mesh is None:
            args.mesh = str(Path(modelname).with_suffix(".npz"))
        if args.materials is None:
            krn_path = Path(modelname).with_suffix(".krn")
            if krn_path.exists():
                args.materials = str(krn_path)
        if args.out_dir == "hyst_out":
            args.out_dir = f"hyst_{modelname}"

    if args.mesh is None:
        ap.error("the following arguments are required: --mesh or modelname")

    mesh_path = Path(args.mesh)
    if not mesh_path.exists() and mesh_path.suffix == "":
        candidate = mesh_path.with_suffix(".npz")
        if candidate.exists():
            mesh_path = candidate
    args.mesh = str(mesh_path)

    data = np.load(mesh_path)
    knt = np.asarray(data["knt"], dtype=np.float64)
    ijk = np.asarray(data["ijk"])

    if ijk.ndim != 2 or ijk.shape[1] not in (4, 5):
        raise ValueError("ijk must have shape (E,4) or (E,5)")

    if ijk.shape[1] == 4:
        mat_id = np.ones((ijk.shape[0],), dtype=np.int32)
        conn = ijk.astype(np.int64)
    else:
        conn = ijk[:, :4].astype(np.int64)
        mat_id = ijk[:, 4].astype(np.int32)
        if mat_id.min() == 0:
            mat_id = mat_id + 1

    shell_added = False
    if args.add_shell:
        shell_added = True
        tmp_npz = Path(args.mesh).with_suffix(".tmp_body.npz")
        np.savez(
            tmp_npz,
            knt=knt,
            ijk=np.column_stack([conn.astype(np.int32), mat_id.astype(np.int32)]),
        )

        knt, ijk_shell = add_shell.run_add_shell_pipeline(
            in_npz=str(tmp_npz),
            layers=args.layers,
            K=args.K,
            KL=args.KL,
            auto_layers=args.auto_layers,
            beta=args.beta,
            center=args.center,
            h0=args.h0,
            hmax=args.hmax,
            minratio=args.minratio,
            max_steiner=args.max_steiner,
            no_exact=args.no_exact,
            verbose=args.shell_verbose,
            shell_type=args.shell_type,
        )
        # Cleanup temporary body file
        if tmp_npz.exists():
            tmp_npz.unlink()

        ijk_shell = np.asarray(ijk_shell)
        conn = ijk_shell[:, :4].astype(np.int64)
        mat_id = ijk_shell[:, 4].astype(np.int32)

    G = int(mat_id.max())

    # Load .p2 overrides early to get mesh_unit
    p2_overrides = {}
    if modelname:
        p2_path = Path(modelname).with_suffix(".p2")
        if p2_path.exists():
            print(f"[config] Loading base settings from {p2_path}")
            p2_overrides = load_params_p2(p2_path)

    mesh_unit = p2_overrides.get("mesh_unit", 1e-9)
    A_lookup, K1_lookup, Js_lookup, k_easy_lookup = load_materials(
        args.materials,
        G,
        mesh_path=args.mesh,
        mesh_unit=mesh_unit,
        shell_added=shell_added,
    )

    # Use volume from compute_volume_JinvT later, but we need V_mag now or soon.
    # Let's compute volume and JinvT now.
    conn32, volume, JinvT = compute_volume_JinvT(knt, conn)

    # Calculate magnetic volume (V_mag)
    # Only groups with Js > 0 are considered magnetic.
    is_mag = np.isin(mat_id, np.where(Js_lookup > 0)[0] + 1)
    V_mag = np.sum(volume[is_mag])
    if V_mag == 0:
        V_mag = 1.0

    # Normalization: Kd = Js^2 / (2 * mu0)
    Js_ref = np.max(Js_lookup)
    if Js_ref == 0:
        Js_ref = 1.0
    MU0_SI = 4e-7 * np.pi
    Kd_ref = (Js_ref**2) / (2.0 * MU0_SI)

    # Reduced properties:
    A_red = A_lookup / Kd_ref
    K1_red = K1_lookup / Kd_ref
    Js_red = Js_lookup / Js_ref

    # Build TetGeom depending on backend
    grad_backend = args.geom_backend

    if grad_backend == "on_the_fly":
        geom = TetGeom(
            conn=jnp.asarray(conn32, dtype=jnp.int32),
            volume=jnp.asarray(volume, dtype=jnp.float64),
            mat_id=jnp.asarray(mat_id, dtype=jnp.int32),
            x_nodes=jnp.asarray(knt, dtype=jnp.float64),
        )
    else:
        if grad_backend == "stored_grad_phi":
            grad_phi = compute_grad_phi_from_JinvT(JinvT)
            geom = TetGeom(
                conn=jnp.asarray(conn32, dtype=jnp.int32),
                volume=jnp.asarray(volume, dtype=jnp.float64),
                mat_id=jnp.asarray(mat_id, dtype=jnp.int32),
                grad_phi=jnp.asarray(grad_phi, dtype=jnp.float64),
                JinvT=None,
                x_nodes=None,
            )
        else:
            geom = TetGeom(
                conn=jnp.asarray(conn32, dtype=jnp.int32),
                volume=jnp.asarray(volume, dtype=jnp.float64),
                mat_id=jnp.asarray(mat_id, dtype=jnp.int32),
                JinvT=jnp.asarray(JinvT, dtype=jnp.float64),
                grad_phi=None,
                x_nodes=None,
            )

    # Initial magnetization
    # Priority: p2 override > CLI --m0-dir > CLI --h-dir
    m0_str = p2_overrides.get("m0_dir", args.m0_dir)
    if m0_str:
        m0_vec = np.array([float(x) for x in m0_str.split(",")], dtype=np.float64)
    else:
        m0_vec = np.array([float(x) for x in args.h_dir.split(",")], dtype=np.float64)

    m0_vec = m0_vec / (np.linalg.norm(m0_vec) + 1e-30)
    m0 = np.tile(m0_vec[None, :], (knt.shape[0], 1))

    h_dir = np.array([float(x) for x in args.h_dir.split(",")], dtype=np.float64)
    h_dir = h_dir / (np.linalg.norm(h_dir) + 1e-30)

    # Dirichlet boundary mask (U=0 at outer boundary)
    mask_np = add_shell.find_outer_boundary_mask(conn, knt.shape[0])
    boundary_mask = jnp.asarray(mask_np, dtype=jnp.float64)

    # Preconditioning: compute lumped node volumes and magnetic moments M_nodal
    from fem_utils import compute_node_volumes

    node_vols = compute_node_volumes(geom, chunk_elems=int(args.chunk_elems))

    # Precompute nodal moments M (M_i = sum_e Js_red[e] * Ve / 4)
    # This is used for Zeeman energy/gradient and as a physical preconditioner
    vol_Js = volume * Js_red[mat_id - 1]
    from dataclasses import replace

    geom_Js = replace(geom, volume=jnp.asarray(vol_Js))
    M_nodal = compute_node_volumes(geom_Js, chunk_elems=int(args.chunk_elems))

    # 1. Start with defaults and CLI values
    param_sources = {}
    params_dict = {
        "h_dir": h_dir,
        "B_start": float(args.B_start) / Js_ref,
        "B_end": float(args.B_end) / Js_ref,
        "dB": float(args.dB) / Js_ref,
        "max_iter": int(args.max_iter),
        "tau_f": float(args.tau_f),
        "eps_a": float(args.eps_a),
        "tau0": float(args.tau0),
        "tau_min": float(args.tau_min),
        "tau_max": float(args.tau_max),
        "cg_maxiter": int(args.cg_maxiter),
        "cg_tol": float(args.cg_tol),
        "poisson_reg": float(args.poisson_reg),
        "loop": False,
        "out_dir": args.out_dir,
        "snapshot_every": int(args.snapshot_every),
        "verbose": args.verbose,
        "Js_ref": float(Js_ref),
        "bias_type": args.bias_type,
        "bias_strength": float(args.bias_strength),
        "method": args.method,
        "pc_iters": int(args.pc_iters),
        "pc_auto": bool(args.pc_auto),
        "pc_force_eta": float(args.pc_force_eta),
        "pc_force_alpha": float(args.pc_force_alpha),
        "pc_stagnation_nu": float(args.pc_stagnation_nu),
        "memory": int(args.memory),
        "tn_iters": int(args.tn_iters),
        "lr": float(args.lr),
        "mu": float(args.mu),
        "pc_reg": float(args.pc_reg),
        "wg_threshold": float(args.wg_threshold),
        "phi_extrapolate": bool(args.phi_extrapolate),
        "cpp_mkl": bool(args.cpp_mkl),
        "benchmark": bool(args.benchmark),
        "poisson_solver": str(args.poisson_solver),
        "data_parallel": bool(args.data_parallel),
    }
    for k in params_dict:
        param_sources[k] = "default"

    # 2. Merge .p2 overrides
    if p2_overrides:
        # Scale field values by Js_ref (they are provided in Tesla)
        if "B_start" in p2_overrides:
            p2_overrides["B_start"] /= Js_ref
        if "B_end" in p2_overrides:
            p2_overrides["B_end"] /= Js_ref
        if "dB" in p2_overrides:
            p2_overrides["dB"] /= Js_ref
        if "mfinal" in p2_overrides:
            p2_overrides["mfinal"] /= Js_ref
        if "mstep" in p2_overrides:
            p2_overrides["mstep"] /= Js_ref

        # Remove parameters handled separately
        p2_overrides.pop("mesh_unit", None)
        p2_overrides.pop("m0_dir", None)

        # Merge p2 into defaults
        for k, v in p2_overrides.items():
            params_dict[k] = v
            param_sources[k] = ".p2"

    # 3. Final CLI Override: If the user explicitly provided an argument on CLI,
    # it should win over BOTH defaults and p2.
    # We check if the arg flag is actually present in sys.argv.
    import sys

    # Map destination variable names to the flags that can set them
    dest_to_flags = {}
    for action in ap._actions:
        dest_to_flags[action.dest] = action.option_strings

    # Identify which variables were explicitly set on the CLI
    explicit_cli_args = set()
    for dest, flags in dest_to_flags.items():
        for flag in flags:
            # Check if any flag matching this dest is in sys.argv
            # (handles both --flag value and --flag=value)
            if any(arg.startswith(flag) for arg in sys.argv):
                explicit_cli_args.add(dest)
                break

    for dest in explicit_cli_args:
        if dest in params_dict:
            params_dict[dest] = getattr(args, dest)
            param_sources[dest] = "cli"
            # Re-scale field units if they came from CLI
            if dest in ["B_start", "B_end", "dB", "mfinal", "mstep"] and params_dict[dest] is not None:
                params_dict[dest] /= Js_ref

    # Clean up params_dict to only include LoopParams fields
    import dataclasses

    loop_param_names = {f.name for f in dataclasses.fields(LoopParams)}

    # Save parameter log
    out_dir_path = Path(args.out_dir)
    out_dir_path.mkdir(parents=True, exist_ok=True)

    log_dict = vars(args).copy()
    log_dict.update(params_dict)

    with open(out_dir_path / "params.log", "w") as f:
        f.write("| Parameter | Value | Source |\n")
        f.write("| :--- | :--- | :--- |\n")
        for k in sorted(log_dict.keys()):
            if "extrapolate" in k:
                continue
            source = param_sources.get(k, "cli" if k in explicit_cli_args else "default")
            f.write(f"| {k} | {log_dict[k]} | {source} |\n")
            if k == "cg_tol":
                phi_tol = float(min(log_dict["cg_tol"], log_dict["tau_f"] * 0.1))
                f.write(f"| phi_tol | {phi_tol} | derived |\n")

    params_dict = {k: v for k, v in params_dict.items() if k in loop_param_names}

    params = LoopParams(**params_dict)

    # Compute per-node bias field
    B_bias = np.zeros((knt.shape[0], 3))
    if params.bias_type == "circular":
        # Compute center of the magnetic part
        mag_nodes = np.unique(conn[mat_id == 1])
        if mag_nodes.size > 0:
            center = np.mean(knt[mag_nodes], axis=0)
            coords = knt - center
            bx = -coords[:, 1]
            by = coords[:, 0]
            norm = np.sqrt(bx**2 + by**2) + 1e-30
            B_bias[:, 0] = bx / norm
            B_bias[:, 1] = by / norm
    elif params.bias_type == "random":
        rng = np.random.default_rng(42)
        B_bias = rng.standard_normal((knt.shape[0], 3))
        B_bias /= np.linalg.norm(B_bias, axis=1, keepdims=True) + 1e-30

    # Scale by strength relative to saturation (dimensionless in our code)
    B_bias *= params.bias_strength

    mode = args.operator_mode
    assembled_kwargs = {}
    cpu_spmv_backend = args.cpu_spmv_backend

    if mode == "assembled":
        print("Assembling global sparse operators on CPU...")
        from amg_utils import (
            assemble_divergence_matrices_cpu,
            assemble_poisson_matrix_cpu,
            get_gpu_assignments,
            make_sparse_operator,
        )

        # Ensure grad_phi is computed
        l_grad_phi = grad_phi if "grad_phi" in locals() and grad_phi is not None else compute_grad_phi_from_JinvT(JinvT)

        A_scipy = assemble_poisson_matrix_cpu(
            conn32, volume, l_grad_phi, boundary_mask=mask_np, reg=float(args.poisson_reg)
        )
        A_diag_cpu = A_scipy.diagonal()
        A_diag = jnp.asarray(A_diag_cpu)

        # GPU device detection and assignment
        try:
            gpus = jax.devices("gpu")
            num_gpus = len(gpus)
        except Exception:
            gpus = []
            num_gpus = 0

        if num_gpus >= 2:
            assignments = get_gpu_assignments(num_gpus, gpus)
            print(f"[multi-gpu] Found {num_gpus} GPUs. Device assignments: {assignments}")
            dev_amg = assignments["AMG"]
            dev_d = assignments["D"]
            dev_g = assignments["G"]
        else:
            dev_amg = dev_d = dev_g = jax.devices()[0]

        A_sparse = make_sparse_operator(A_scipy, cpu_spmv_backend=cpu_spmv_backend)
        A_sparse = jax.device_put(A_sparse, dev_amg)

        Dx_scipy, Dy_scipy, Dz_scipy = assemble_divergence_matrices_cpu(conn32, volume, l_grad_phi, Js_red, mat_id)

        import scipy.sparse as sp

        if args.cpp_mkl:
            Dx_coo = Dx_scipy.tocoo()
            Dy_coo = Dy_scipy.tocoo()
            Dz_coo = Dz_scipy.tocoo()
            rows = np.concatenate([Dx_coo.row, Dy_coo.row, Dz_coo.row])
            cols = np.concatenate([Dx_coo.col * 3 + 0, Dy_coo.col * 3 + 1, Dz_coo.col * 3 + 2])
            data = np.concatenate([Dx_coo.data, Dy_coo.data, Dz_coo.data])
            D_scipy = sp.csr_matrix((data, (rows, cols)), shape=(Dx_scipy.shape[0], 3 * Dx_scipy.shape[1]))
            D_scipy.sort_indices()
            D_sparse = make_sparse_operator(D_scipy, cpu_spmv_backend=cpu_spmv_backend)
            D_sparse = jax.device_put(D_sparse, dev_d)

            Gx_coo = (2.0 * Dx_scipy.transpose()).tocoo()
            Gy_coo = (2.0 * Dy_scipy.transpose()).tocoo()
            Gz_coo = (2.0 * Dz_scipy.transpose()).tocoo()
            rows_g = np.concatenate([Gx_coo.row * 3 + 0, Gy_coo.row * 3 + 1, Gz_coo.row * 3 + 2])
            cols_g = np.concatenate([Gx_coo.col, Gy_coo.col, Gz_coo.col])
            data_g = np.concatenate([Gx_coo.data, Gy_coo.data, Gz_coo.data])
            G_scipy = sp.csr_matrix((data_g, (rows_g, cols_g)), shape=(3 * Gx_coo.shape[0], Gx_coo.shape[1]))
            G_scipy.sort_indices()
            G_sparse = make_sparse_operator(G_scipy, cpu_spmv_backend=cpu_spmv_backend)
            G_sparse = jax.device_put(G_sparse, dev_g)
        else:
            D_scipy = sp.hstack([Dx_scipy, Dy_scipy, Dz_scipy]).tocsr()
            D_sparse = make_sparse_operator(D_scipy, cpu_spmv_backend=cpu_spmv_backend)
            D_sparse = jax.device_put(D_sparse, dev_d)
            N = knt.shape[0]
            Gx_scipy = 2.0 * D_scipy[:, :N].transpose()
            Gy_scipy = 2.0 * D_scipy[:, N : 2 * N].transpose()
            Gz_scipy = 2.0 * D_scipy[:, 2 * N :].transpose()
            G_scipy = sp.vstack([Gx_scipy, Gy_scipy, Gz_scipy]).tocsr()
            G_sparse = make_sparse_operator(G_scipy, cpu_spmv_backend=cpu_spmv_backend)
            G_sparse = jax.device_put(G_sparse, dev_g)
            del Gx_scipy, Gy_scipy, Gz_scipy

        del Dx_scipy, Dy_scipy, Dz_scipy
        Dx_sparse = Dy_sparse = Dz_sparse = None
        Gx_sparse = Gy_sparse = Gz_sparse = None

        from amg_utils import assemble_exchange_anisotropy_matrix_cpu

        K_eff_scipy = assemble_exchange_anisotropy_matrix_cpu(
            conn32, volume, l_grad_phi, A_red, K1_red, k_easy_lookup, mat_id
        )

        Kx_sparse = Ky_sparse = Kz_sparse = None
        if num_gpus >= 3:
            K_eff_coo = K_eff_scipy.tocoo()
            N = knt.shape[0]
            P_idx_row = (K_eff_coo.row % 3) * N + (K_eff_coo.row // 3)
            P_idx_col = (K_eff_coo.col % 3) * N + (K_eff_coo.col // 3)
            K_eff_blocked = sp.csr_matrix((K_eff_coo.data, (P_idx_row, P_idx_col)), shape=(3 * N, 3 * N))
            Kx_scipy = K_eff_blocked[:N, :]
            Ky_scipy = K_eff_blocked[N : 2 * N, :]
            Kz_scipy = K_eff_blocked[2 * N :, :]

            Kx_sparse = make_sparse_operator(Kx_scipy, cpu_spmv_backend=cpu_spmv_backend)
            Kx_sparse = jax.device_put(Kx_sparse, assignments["Kx"])

            Ky_sparse = make_sparse_operator(Ky_scipy, cpu_spmv_backend=cpu_spmv_backend)
            Ky_sparse = jax.device_put(Ky_sparse, assignments["Ky"])

            Kz_sparse = make_sparse_operator(Kz_scipy, cpu_spmv_backend=cpu_spmv_backend)
            Kz_sparse = jax.device_put(Kz_sparse, assignments["Kz"])

            K_eff_sparse = None
        else:
            K_eff_sparse = make_sparse_operator(K_eff_scipy, cpu_spmv_backend=cpu_spmv_backend)
            if num_gpus == 2:
                K_eff_sparse = jax.device_put(K_eff_sparse, assignments["Keff"])

        assembled_kwargs = {
            "A_sparse": A_sparse,
            "Dx_sparse": None,
            "Dy_sparse": None,
            "Dz_sparse": None,
            "A_diag": A_diag,
            "K_eff_sparse": K_eff_sparse,
            "Kx_sparse": Kx_sparse,
            "Ky_sparse": Ky_sparse,
            "Kz_sparse": Kz_sparse,
            "num_gpus": num_gpus,
            "Gx_sparse": None,
            "Gy_sparse": None,
            "Gz_sparse": None,
            "D_sparse": D_sparse,
            "G_sparse": G_sparse,
            "K_eff_scipy": K_eff_scipy,
            "D_scipy": D_scipy,
            "G_scipy": G_scipy,
        }
        print("[ok] Finished assembly and GPU transfer.")

    res = run_hysteresis_loop(
        points=knt,
        geom=geom,
        A_lookup=jnp.asarray(A_red, dtype=jnp.float64),
        K1_lookup=jnp.asarray(K1_red, dtype=jnp.float64),
        Js_lookup=jnp.asarray(Js_red, dtype=jnp.float64),
        k_easy_lookup=jnp.asarray(k_easy_lookup, dtype=jnp.float64),
        m0=jnp.asarray(m0, dtype=jnp.float64),
        params=params,
        V_mag=float(V_mag),
        node_volumes=jnp.asarray(node_vols, dtype=jnp.float64),
        M_nodal=jnp.asarray(M_nodal, dtype=jnp.float64),
        B_bias=jnp.asarray(B_bias, dtype=jnp.float64) if B_bias is not None else None,
        precond_type=args.precond_type,
        grad_backend=grad_backend,
        chunk_elems=int(args.chunk_elems),
        boundary_mask=jnp.asarray(boundary_mask, dtype=jnp.float64) if boundary_mask is not None else None,
        mode=mode,
        cpu_spmv_backend=cpu_spmv_backend,
        **assembled_kwargs,
    )

    # Write .mh file for mammos-mumag compatibility
    mh_name = modelname if modelname else "hysteresis"
    write_mh(Path(args.out_dir) / mh_name, res["history"])
    print(f"[ok] Wrote mammos-mumag compatibility file: {Path(args.out_dir) / mh_name}.mh")


if __name__ == "__main__":
    main()
