"""mesh_convert.py

Convert between NPZ meshes and VTK UnstructuredGrid (.vtu) tetra meshes.

NPZ format
----------
  knt: (N,3) float64 - node coordinates.
  ijk: (E,4) or (E,5) int32/int64 - connectivity. If (E,5), last column is mat_id.

VTU support
-----------
- If meshio is installed, it is used for robust VTU read/write.
- Otherwise, VTU output uses io_utils.write_vtu_tetra and input supports the ASCII VTU format
  produced by that writer.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

import argparse
import numpy as np


def _try_import_meshio() -> Any:
    """Attempt to import the meshio library.

    Returns:
        Optional[Module]: The meshio module if available, else None.
    """
    try:
        import meshio  # type: ignore
        return meshio
    except Exception:
        return None


def npz_to_vtu(npz_path: str, vtu_path: str) -> None:
    """Convert an NPZ mesh file to a VTU file.

    Args:
        npz_path (str): Path to the source .npz file.
        vtu_path (str): Path to the target .vtu file.

    Raises:
        KeyError: If the NPZ file does not contain 'knt' or 'ijk'.
        ValueError: If the connectivity array shape is invalid.

    Example:
        >>> npz_to_vtu("mesh.npz", "mesh.vtu")
    """
    data = np.load(npz_path)
    if 'knt' not in data or 'ijk' not in data:
        raise KeyError("NPZ must contain 'knt' and 'ijk'")
    knt = np.asarray(data['knt'], dtype=np.float64)
    ijk = np.asarray(data['ijk'])

    if ijk.ndim != 2 or ijk.shape[1] not in (4, 5):
        raise ValueError('ijk must have shape (E,4) or (E,5)')

    conn = ijk[:, :4].astype(np.int32)
    cell_data = {}
    if ijk.shape[1] == 5:
        cell_data['mat_id'] = ijk[:, 4].astype(np.int32)

    meshio = _try_import_meshio()
    if meshio is not None:
        cells = [('tetra', conn)]
        cd = {'mat_id': [cell_data['mat_id']]} if 'mat_id' in cell_data else None
        m = meshio.Mesh(points=knt, cells=cells, cell_data=cd)
        m.write(vtu_path)
        return

    from io_utils import write_vtu_tetra
    write_vtu_tetra(vtu_path, knt, conn, cell_data=cell_data)


def vtu_to_npz(vtu_path: str, npz_path: str) -> None:
    """Convert a VTU mesh file to an NPZ file.

    Args:
        vtu_path (str): Path to the source .vtu file.
        npz_path (str): Path to the target .npz file.

    Raises:
        ValueError: If no tetra cells are found in the VTU file.

    Example:
        >>> vtu_to_npz("mesh.vtu", "mesh.npz")
    """
    meshio = _try_import_meshio()
    if meshio is not None:
        m = meshio.read(vtu_path)
        pts = np.asarray(m.points[:, :3], dtype=np.float64)

        tets = None
        for cb in m.cells:
            if cb.type in ('tetra', 'tetra4'):
                tets = np.asarray(cb.data, dtype=np.int32)
                break
        if tets is None:
            raise ValueError('No tetra cells found')

        mat = None
        try:
            cd = m.cell_data_dict.get('mat_id', None)
            if cd is not None:
                mat = np.asarray(cd['tetra'], dtype=np.int32).ravel()
        except Exception:
            pass

        if mat is None and hasattr(m, 'cell_data'):
            for key, data_list in m.cell_data.items():
                if key == 'mat_id':
                    for cell_block, arr in zip(m.cells, data_list):
                        if cell_block.type in ('tetra', 'tetra4'):
                            mat = np.asarray(arr, dtype=np.int32).ravel()
                            break

        ijk = tets if mat is None else np.column_stack([tets, mat])
        np.savez(npz_path, knt=pts, ijk=ijk)
        return

    import xml.etree.ElementTree as ET
    tree = ET.parse(vtu_path)
    root = tree.getroot()

    pts_arr = root.find('.//Points/DataArray')
    if pts_arr is None or pts_arr.text is None:
        raise ValueError('Could not locate Points/DataArray')
    pts = np.fromstring(pts_arr.text.strip(), sep=' ', dtype=np.float32).reshape(-1, 3).astype(np.float64)

    conn_arr = root.find('.//Cells/DataArray[@Name="connectivity"]')
    if conn_arr is None or conn_arr.text is None:
        raise ValueError('Could not locate Cells/connectivity DataArray')
    conn = np.fromstring(conn_arr.text.strip(), sep=' ', dtype=np.int32)
    tets = conn.reshape(-1, 4)

    mat_arr = root.find('.//CellData/DataArray[@Name="mat_id"]')
    if mat_arr is not None and mat_arr.text and mat_arr.text.strip():
        mat = np.fromstring(mat_arr.text.strip(), sep=' ', dtype=np.int32)
        ijk = np.column_stack([tets, mat])
    else:
        ijk = tets

    np.savez(npz_path, knt=pts, ijk=ijk)


def main() -> None:
    """CLI entry point for mesh conversion.
    """
    ap = argparse.ArgumentParser(description='Convert between NPZ (knt/ijk) and VTU tetra meshes.')
    ap.add_argument('--in', dest='inp', required=True, help='Input mesh (.npz or .vtu)')
    ap.add_argument('--out', dest='out', required=True, help='Output mesh (.vtu or .npz)')
    args = ap.parse_args()

    inp = str(args.inp)
    out = str(args.out)

    if inp.lower().endswith('.npz') and out.lower().endswith('.vtu'):
        npz_to_vtu(inp, out)
    elif inp.lower().endswith('.vtu') and out.lower().endswith('.npz'):
        vtu_to_npz(inp, out)
    else:
        raise ValueError('Use (.npz -> .vtu) or (.vtu -> .npz)')


if __name__ == '__main__':
    main()
