"""poisson_solve.py

Matrix-free Poisson operator and PCG solver with:
  - Jacobi preconditioner (always)
  - Warm start (always)
  - Optional coarse correction using aggregates (agg_id + inv_sqrt_counts)

Coarse correction uses:
  z = D^{-1} r + Z E^{-1} Z^T r
with E assembled once from element stiffness contributions.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from functools import partial
from typing import Callable, Optional, Literal

import jax
import jax.numpy as jnp
from jax import lax
import jax.scipy.linalg as jsp

from fem_utils import TetGeom, pad_geom_for_chunking, chunk_mask

Array = jnp.ndarray
GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']

_GRAD_HAT = jnp.array([
    [-1.0, -1.0, -1.0],
    [ 1.0,  0.0,  0.0],
    [ 0.0,  1.0,  0.0],
    [ 0.0,  0.0,  1.0],
], dtype=jnp.float64)


def _B_from_JinvT(JinvT_c: Array, dtype) -> Array:
    return jnp.einsum('eij,aj->eai', JinvT_c.astype(dtype), _GRAD_HAT.astype(dtype))


def _compute_JinvT_from_coords(x_e: Array, dtype) -> Array:
    x0 = x_e[:, 0, :]
    J = jnp.stack([x_e[:, 1, :] - x0, x_e[:, 2, :] - x0, x_e[:, 3, :] - x0], axis=2)
    invJ = jnp.linalg.inv(J.astype(dtype))
    return jnp.swapaxes(invJ, 1, 2)


def _make_B_getter(geom_p: TetGeom, chunk_elems: int, grad_backend: GradBackend):
    if grad_backend == 'stored_grad_phi':
        if geom_p.grad_phi is None:
            raise ValueError('stored_grad_phi requires geom.grad_phi')
        grad_phi = geom_p.grad_phi
        def _get_B(conn_c: Array, s: int, dtype) -> Array:
            return lax.dynamic_slice(grad_phi, (s,0,0), (chunk_elems,4,3)).astype(dtype)
        return _get_B

    if grad_backend == 'stored_JinvT':
        if geom_p.JinvT is None:
            raise ValueError('stored_JinvT requires geom.JinvT')
        JinvT = geom_p.JinvT
        def _get_B(conn_c: Array, s: int, dtype) -> Array:
            JinvT_c = lax.dynamic_slice(JinvT, (s,0,0), (chunk_elems,3,3)).astype(dtype)
            return _B_from_JinvT(JinvT_c, dtype)
        return _get_B

    if geom_p.x_nodes is None:
        raise ValueError('on_the_fly requires geom.x_nodes')
    x_nodes = geom_p.x_nodes
    def _get_B(conn_c: Array, s: int, dtype) -> Array:
        x_e = x_nodes[conn_c].astype(dtype)
        JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
        return _B_from_JinvT(JinvT_c, dtype)
    return _get_B


def _restrict(r: Array, agg_id: Array, inv_sqrt_counts: Array, k: int) -> Array:
    w = inv_sqrt_counts[agg_id]
    return jax.ops.segment_sum(r * w, agg_id, k)


def _prolong(y: Array, agg_id: Array, inv_sqrt_counts: Array) -> Array:
    w = inv_sqrt_counts[agg_id]
    return y[agg_id] * w


def make_poisson_ops(
    geom: TetGeom,
    Ms_lookup: Array,
    *,
    chunk_elems: int = 200_000,
    reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
):
    """Return (apply_A, rhs_from_m, assemble_diag, assemble_E)."""

    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id
    Ms_lookup = jnp.asarray(Ms_lookup)

    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems

    _get_B = _make_B_getter(geom_p, chunk_elems, grad_backend)

    def apply_A(U: Array) -> Array:
        dtype = U.dtype
        def body(i, y_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask
            U_e = U[conn_c]
            gradU = jnp.einsum('ea,eak->ek', U_e, B_c)
            dot_term = jnp.einsum('eak,ek->ea', B_c, gradU)
            contrib = Ve_eff[:, None] * dot_term
            return y_acc.at[conn_c].add(contrib)
        y0 = jnp.zeros_like(U)
        y = lax.fori_loop(0, n_chunks, body, y0)
        return y + jnp.asarray(reg, dtype=dtype) * U

    def rhs_from_m(m: Array) -> Array:
        dtype = m.dtype
        def body(i, b_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask
            Ms_c = Ms_lookup[mat_c - 1].astype(dtype)
            m_e = m[conn_c]
            # M is assumed uniform per element (P0) or averaged from nodes
            M_avg = Ms_c[:, None] * jnp.mean(m_e, axis=1)
            # RHS contribution: integral( grad(phi_i) . M ) dV
            # This corresponds to the weak form of div(H) = -div(M)
            dot_term = jnp.einsum('eak,ek->ea', B_c, M_avg)
            contrib = Ve_eff[:, None] * dot_term
            return b_acc.at[conn_c].add(contrib)
        b0 = jnp.zeros((m.shape[0],), dtype=dtype)
        return lax.fori_loop(0, n_chunks, body, b0)

    def assemble_diag(N: int) -> Array:
        dtype = jnp.float64
        def body(i, d_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask
            local = Ve_eff[:, None] * jnp.sum(B_c * B_c, axis=2)
            return d_acc.at[conn_c].add(local)
        d0 = jnp.zeros((N,), dtype=dtype)
        d = lax.fori_loop(0, n_chunks, body, d0)
        return d + jnp.asarray(reg, dtype=dtype)

    def assemble_E(agg_id: Array, inv_sqrt_counts: Array) -> Array:
        dtype = jnp.float64
        k = int(inv_sqrt_counts.shape[0])
        def body(i, E_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            mask = chunk_mask(E_orig, s, chunk_elems, dtype)
            Ve_eff = Ve_c * mask
            agg_e = agg_id[conn_c]
            w_e = inv_sqrt_counts[agg_e]
            Ke = Ve_eff[:, None, None] * jnp.einsum('eai,ebi->eab', B_c, B_c)
            contrib = Ke * (w_e[:, :, None] * w_e[:, None, :])
            for a in range(4):
                for b in range(4):
                    E_acc = E_acc.at[agg_e[:, a], agg_e[:, b]].add(contrib[:, a, b])
            return E_acc
        E0 = jnp.zeros((k, k), dtype=dtype)
        E = lax.fori_loop(0, n_chunks, body, E0)
        E = E + jnp.asarray(reg, dtype=dtype) * jnp.eye(k, dtype=dtype)
        E = E + jnp.asarray(1e-18, dtype=dtype) * jnp.eye(k, dtype=dtype)
        return E

    return jax.jit(apply_A), jax.jit(rhs_from_m), jax.jit(assemble_diag, static_argnums=(0,)), jax.jit(assemble_E)


def make_pcg_solve(
    apply_A: Callable[[Array], Array],
    Mdiag: Array,
    *,
    maxiter: int = 500,
    tol: float = 1e-8,
    agg_id: Optional[Array] = None,
    inv_sqrt_counts: Optional[Array] = None,
    E_chol: Optional[Array] = None,
):
    tol = float(tol)
    use_coarse = (agg_id is not None) and (inv_sqrt_counts is not None) and (E_chol is not None)
    k = int(inv_sqrt_counts.shape[0]) if use_coarse else 0

    def apply_Minv(r: Array) -> Array:
        dtype = r.dtype
        eps = jnp.asarray(1e-30, dtype=dtype)
        z = r / (Mdiag.astype(dtype) + eps)
        if use_coarse:
            rc = _restrict(r, agg_id, inv_sqrt_counts.astype(dtype), k)
            y = jsp.solve_triangular(E_chol.astype(dtype), rc, lower=True)
            y = jsp.solve_triangular(E_chol.astype(dtype), y, lower=True, trans='T')
            z = z + _prolong(y, agg_id, inv_sqrt_counts.astype(dtype))
        return z

    def solve(b: Array, x0: Array) -> Array:
        dtype = b.dtype
        eps = jnp.asarray(1e-30, dtype=dtype)
        x = x0
        r = b - apply_A(x)
        z = apply_Minv(r)
        p = z
        rz = jnp.dot(r, z)
        bnorm2 = jnp.dot(b, b)

        def cond_fun(state):
            it, x, r, z, p, rz = state
            return jnp.logical_and(it < maxiter, rz > (tol * tol) * bnorm2 + jnp.asarray(0.0, dtype))

        def body_fun(state):
            it, x, r, z, p, rz = state
            Ap = apply_A(p)
            alpha = rz / (jnp.dot(p, Ap) + eps)
            x = x + alpha * p
            r = r - alpha * Ap
            z = apply_Minv(r)
            rz_new = jnp.dot(r, z)
            beta = rz_new / (rz + eps)
            p = z + beta * p
            return (it + 1, x, r, z, p, rz_new)

        init = (jnp.int32(0), x, r, z, p, rz)
        _, x, _, _, _, _ = lax.while_loop(cond_fun, body_fun, init)
        return x

    return jax.jit(solve)


def make_solve_U(
    geom: TetGeom,
    Ms_lookup: Array,
    *,
    chunk_elems: int = 200_000,
    cg_maxiter: int = 400,
    cg_tol: float = 1e-8,
    poisson_reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    enforce_zero_mean: bool = True,
    agg_id: Optional[Array] = None,
    inv_sqrt_counts: Optional[Array] = None,
):
    apply_A, rhs_from_m, assemble_diag, assemble_E = make_poisson_ops(
        geom,
        Ms_lookup,
        chunk_elems=chunk_elems,
        reg=poisson_reg,
        grad_backend=grad_backend,
    )

    if geom.x_nodes is not None:
        N = int(geom.x_nodes.shape[0])
    else:
        import numpy as np
        N = int(np.max(geom.conn)) + 1

    Mdiag = assemble_diag(N)

    E_chol = None
    if (agg_id is not None) and (inv_sqrt_counts is not None):
        E = assemble_E(agg_id, inv_sqrt_counts)
        E_chol = jnp.linalg.cholesky(E)

    solve_linear = make_pcg_solve(
        apply_A,
        Mdiag,
        maxiter=cg_maxiter,
        tol=cg_tol,
        agg_id=agg_id,
        inv_sqrt_counts=inv_sqrt_counts,
        E_chol=E_chol,
    )

    @jax.jit
    def solve_U(m: Array, x0: Array) -> Array:
        b = rhs_from_m(m)
        if enforce_zero_mean:
            b = b - jnp.mean(b)
            x0 = x0 - jnp.mean(x0)
        U = solve_linear(b, x0)
        if enforce_zero_mean:
            U = U - jnp.mean(U)
        return U

    return solve_U
