"""poisson_solve.py

Matrix-free Poisson operator and PCG solver with support for multiple 
preconditioners (Jacobi, Chebyshev, AMG) and warm starts.

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from functools import partial
from typing import Callable, Optional, Literal, Tuple

import jax
import jax.numpy as jnp
from jax import lax

from fem_utils import TetGeom, pad_geom_for_chunking, chunk_mask, assemble_scatter, assemble_segment_sum

Array = jnp.ndarray
GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']
PrecondType = Literal['none', 'jacobi', 'chebyshev', 'amg', 'amgcl']
Assembly = Literal['scatter', 'segment_sum']

_GRAD_HAT = jnp.array([
    [-1.0, -1.0, -1.0],
    [ 1.0,  0.0,  0.0],
    [ 0.0,  1.0,  0.0],
    [ 0.0,  0.0,  1.0],
], dtype=jnp.float64)


def _B_from_JinvT(JinvT_c: Array, dtype) -> Array:
    """Compute shape function gradients B from inverse Jacobian transpose.

    Args:
        JinvT_c (Array): Inverse Jacobian transpose (chunk_elems, 3, 3).
        dtype (jnp.dtype): Target data type.

    Returns:
        Array: Shape function gradients (chunk_elems, 4, 3).
    """
    return jnp.einsum('eij,aj->eai', JinvT_c.astype(dtype), _GRAD_HAT.astype(dtype))


def _compute_JinvT_from_coords(x_e: Array, dtype) -> Array:
    """Compute inverse Jacobian transpose from tetrahedron node coordinates.

    Args:
        x_e (Array): Node coordinates for the chunk (chunk_elems, 4, 3).
        dtype (jnp.dtype): Target data type.

    Returns:
        Array: Inverse Jacobian transpose (chunk_elems, 3, 3).
    """
    x0 = x_e[:, 0, :]
    J = jnp.stack([x_e[:, 1, :] - x0, x_e[:, 2, :] - x0, x_e[:, 3, :] - x0], axis=2)
    invJ = jnp.linalg.inv(J.astype(dtype))
    return jnp.swapaxes(invJ, 1, 2)


def _make_B_getter(geom_p: TetGeom, chunk_elems: int, grad_backend: GradBackend) -> Callable[[Array, int, jnp.dtype], Array]:
    """Create a helper function to retrieve shape function gradients for a chunk.

    Args:
        geom_p (TetGeom): Padded geometry container.
        chunk_elems (int): Size of element chunks.
        grad_backend (GradBackend): Strategy for gradients.

    Returns:
        Callable: A function _get_B(connectivity, chunk_start_index, dtype).
    """
    if grad_backend == 'stored_grad_phi':
        if geom_p.grad_phi is None:
            raise ValueError('stored_grad_phi requires geom.grad_phi')
        grad_phi = geom_p.grad_phi
        def _get_B(conn_c: Array, s: int, dtype) -> Array:
            return lax.dynamic_slice(grad_phi, (s,0,0), (chunk_elems,4,3)).astype(dtype)
        return _get_B

    if grad_backend == 'stored_JinvT':
        if geom_p.JinvT is None:
            raise ValueError('stored_JinvT requires geom.JinvT')
        JinvT = geom_p.JinvT
        def _get_B(conn_c: Array, s: int, dtype) -> Array:
            JinvT_c = lax.dynamic_slice(JinvT, (s,0,0), (chunk_elems,3,3)).astype(dtype)
            return _B_from_JinvT(JinvT_c, dtype)
        return _get_B

    if geom_p.x_nodes is None:
        raise ValueError('on_the_fly requires geom.x_nodes')
    x_nodes = geom_p.x_nodes
    def _get_B(conn_c: Array, s: int, dtype) -> Array:
        x_e = x_nodes[conn_c].astype(dtype)
        JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
        return _B_from_JinvT(JinvT_c, dtype)
    return _get_B

def make_poisson_ops(
    geom: TetGeom,
    Js_lookup: Array,
    *,
    chunk_elems: int = 200_000,
    reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    assembly: Assembly = 'scatter',
    boundary_mask: Optional[Array] = None,
) -> Tuple[Callable[[Array], Array], Callable[[Array], Array], Callable[[int], Array]]:
    """Create JIT-compiled matrix-free Poisson operators.

    Args:
        geom (TetGeom): Geometry container.
        Js_lookup (Array): Saturation polarization for each material.
        chunk_elems (int, optional): Elements per loop iteration. Defaults to 200_000.
        reg (float, optional): Tikhonov regularization for the diagonal. 
            Defaults to 1e-12.
        grad_backend (GradBackend, optional): Strategy for shape function gradients. 
            Defaults to 'stored_grad_phi'.
        assembly (Assembly, optional): Nodal assembly method. Defaults to 'scatter'.
        boundary_mask (Optional[Array], optional): Dirichlet boundary mask (0.0 at boundary).
            Defaults to None.

    Returns:
        Tuple[Callable, Callable, Callable]: (apply_A, rhs_from_m, assemble_diag).
            apply_A: Computes matrix-vector product A @ U.
            rhs_from_m: Computes demag RHS from magnetization m.
            assemble_diag: Computes the diagonal of A.
    """

    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id
    Js_lookup = jnp.asarray(Js_lookup)

    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems
    
    if geom_p.x_nodes is not None:
        N = int(geom_p.x_nodes.shape[0])
    else:
        import numpy as np
        N = int(np.max(geom.conn)) + 1

    _get_B = _make_B_getter(geom_p, chunk_elems, grad_backend)

    def apply_A(U: Array) -> Array:
        """Compute the matrix-vector product A @ U.
        
        Optimization Choice: Matrix-free implementation. 
        Rather than storing the global stiffness matrix A (which can be 100s of GBs
        for large meshes), we compute the product by re-evaluating the local
        FEM contributions on the fly. This turns a memory-bound problem into a 
        compute-bound one, which is ideal for modern GPUs.
        """
        dtype = U.dtype
        def body(i: int, y_acc: Array) -> Array:
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            U_e = U[conn_c]
            
            # Unrolled element gradient: grad_U = sum_b U_b * grad_phi_b
            # Manual unrolling here minimizes temporary array creation and
            # improves register allocation in the XLA-compiled kernel.
            grad_U = (B_c[:, 0, :] * U_e[:, 0, None] +
                      B_c[:, 1, :] * U_e[:, 1, None] +
                      B_c[:, 2, :] * U_e[:, 2, None] +
                      B_c[:, 3, :] * U_e[:, 3, None])
            
            # Unrolled node contribution: contrib_a = Ve * (grad_phi_a . grad_U)
            contrib = Ve_c[:, None] * (B_c[..., 0] * grad_U[:, 0, None] + 
                                       B_c[..., 1] * grad_U[:, 1, None] + 
                                       B_c[..., 2] * grad_U[:, 2, None])

            if assembly == 'scatter':
                return assemble_scatter(y_acc, conn_c, contrib)
            else:
                return y_acc + assemble_segment_sum(N, conn_c, contrib, dtype)
        y0 = jnp.zeros_like(U)
        y = lax.fori_loop(0, n_chunks, body, y0)
        y = y + jnp.asarray(reg, dtype=dtype) * U
        
        # Choice: Dirichlet boundary conditions (U=0) are enforced by zeroing out
        # the corresponding rows of the operator.
        if boundary_mask is not None:
            y = y * boundary_mask
        return y

    def rhs_from_m(m: Array) -> Array:
        dtype = m.dtype
        def body(i: int, b_acc: Array) -> Array:
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            Js_c = Js_lookup[mat_c - 1].astype(dtype)
            m_e = m[conn_c]
            
            # Unrolled RHS: contrib_a = (Js * Ve / 4) * (sum_b m_b . grad_phi_a)
            m_sum = m_e[:, 0, :] + m_e[:, 1, :] + m_e[:, 2, :] + m_e[:, 3, :]
            dot_term = 0.25 * (B_c[..., 0] * m_sum[:, 0, None] + 
                               B_c[..., 1] * m_sum[:, 1, None] + 
                               B_c[..., 2] * m_sum[:, 2, None])
            
            contrib = (Ve_c * Js_c)[:, None] * dot_term
            if assembly == 'scatter':
                return assemble_scatter(b_acc, conn_c, contrib)
            else:
                return b_acc + assemble_segment_sum(N, conn_c, contrib, dtype)
        b0 = jnp.zeros((m.shape[0],), dtype=dtype)
        return lax.fori_loop(0, n_chunks, body, b0)

    def assemble_diag(N: int) -> Array:
        dtype = jnp.float64
        def body(i: int, d_acc: Array) -> Array:
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            # Unrolled norm squared: |grad_phi_a|^2
            local = Ve_c[:, None] * (B_c[..., 0]**2 + B_c[..., 1]**2 + B_c[..., 2]**2)
            if assembly == 'scatter':
                return assemble_scatter(d_acc, conn_c, local)
            else:
                return d_acc + assemble_segment_sum(N, conn_c, local, dtype)
        d0 = jnp.zeros((N,), dtype=dtype)
        d = lax.fori_loop(0, n_chunks, body, d0)
        return d + jnp.asarray(reg, dtype=dtype)

    return jax.jit(apply_A), jax.jit(rhs_from_m), jax.jit(assemble_diag, static_argnums=(0,))


def estimate_spectral_radius(apply_A: Callable[[Array], Array], Mdiag: Array, boundary_mask: Optional[Array], N: int, n_iters: int = 15) -> float:
    """Estimate the spectral radius (max eigenvalue) of M^-1 A using the power method.

    Args:
        apply_A (Callable): Matrix-vector product.
        Mdiag (Array): Preconditioning diagonal.
        boundary_mask (Optional[Array]): Dirichlet boundary mask.
        N (int): Number of nodes.
        n_iters (int, optional): Power method iterations. Defaults to 15.

    Returns:
        float: Estimated spectral radius.
    """
    key = jax.random.PRNGKey(42)
    v = jax.random.normal(key, (N,), dtype=jnp.float64)
    if boundary_mask is not None:
        v = v * boundary_mask
    
    def body(i: int, v_curr: Array) -> Array:
        v_next = (apply_A(v_curr) / (Mdiag + 1e-30))
        if boundary_mask is not None:
            v_next = v_next * boundary_mask
        return v_next / (jnp.linalg.norm(v_next) + 1e-30)
    
    v_final = lax.fori_loop(0, n_iters, body, v)
    lam_max = jnp.vdot(v_final, (apply_A(v_final) / (Mdiag + 1e-30)))
    return float(lam_max)

def make_pcg_solve(
    apply_A: Callable[[Array], Array],
    Mdiag: Array,
    *,
    precond_type: PrecondType = 'none',
    apply_Minv_amg: Optional[Callable[[Array, Optional[list]], Array]] = None,
    order: int = 3,
    maxiter: int = 500,
    tol: float = 1e-8,
    boundary_mask: Optional[Array] = None,
    l_max: float = 2.0,
) -> Callable[[Array, Array, Optional[float], Optional[list]], Tuple[Array, int, float]]:
    """Create a JIT-compiled PCG solver function.

    Args:
        apply_A (Callable): Matrix-vector product.
        Mdiag (Array): Jacobi preconditioning diagonal.
        precond_type (PrecondType, optional): Preconditioning strategy. 
            Defaults to 'none'.
        apply_Minv_amg (Optional[Callable], optional): AMG V-cycle function.
            Required for 'amg' or 'amgcl' preconditioning. Defaults to None.
        order (int, optional): Polynomial order for Chebyshev preconditioner.
            Defaults to 3.
        maxiter (int, optional): Maximum solver iterations. Defaults to 500.
        tol (float, optional): Default relative tolerance. Defaults to 1e-8.
        boundary_mask (Optional[Array], optional): Dirichlet boundary mask.
            Defaults to None.
        l_max (float, optional): Spectral radius for Chebyshev preconditioning.
            Defaults to 2.0.

    Returns:
        Callable: solve(rhs, x0, tol, hierarchy) -> (solution, iterations, residual_norm_squared).
    """
    default_tol = float(tol)

    def apply_Minv(r: Array, hierarchy: Optional[list] = None) -> Array:
        if precond_type == 'none':
            if boundary_mask is not None:
                return r * boundary_mask
            return r

        if precond_type in ['amg', 'amgcl'] and apply_Minv_amg is not None:
            return apply_Minv_amg(r, hierarchy)
            
        dtype = r.dtype
        eps = jnp.asarray(1e-30, dtype=dtype)
        
        # Initial Jacobi guess
        z0 = r / (Mdiag.astype(dtype) + eps)
        
        if precond_type == 'chebyshev' and order > 0:
            lam_max = l_max
            lam_min = lam_max / 10.0 
            d = (lam_max + lam_min) / 2.0
            c = (lam_max - lam_min) / 2.0
            alpha = 1.0 / d
            y = alpha * z0
            y_prev = jnp.zeros_like(y)
            curr_alpha = alpha
            for k in range(1, order):
                res = r - apply_A(y)
                if boundary_mask is not None: res = res * boundary_mask
                z = res / (Mdiag.astype(dtype) + eps)
                beta = (c * curr_alpha / 2.0)**2
                curr_alpha = 1.0 / (d - beta)
                y_next = y + curr_alpha * z + curr_alpha * beta * (y - y_prev)
                y_prev = y
                y = y_next
            z = y
        else:
            z = z0
        
        if boundary_mask is not None:
            z = z * boundary_mask
        return z

    def solve(b: Array, x0: Array, tol: Optional[float] = None, hierarchy: Optional[list] = None) -> Tuple[Array, int, float]:
        dtype = b.dtype
        eps = jnp.asarray(1e-30, dtype=dtype)
        current_tol = jnp.asarray(tol if tol is not None else default_tol, dtype=dtype)
        
        if boundary_mask is not None:
            b = b * boundary_mask
            x = x0 * boundary_mask
        else:
            x = x0

        r = b - apply_A(x)
        if boundary_mask is not None: r = r * boundary_mask
            
        z = apply_Minv(r, hierarchy)
        p = z
        rz = jnp.dot(r, z)
        r2 = jnp.dot(r, r)
        bnorm2 = jnp.dot(b, b)
        tol2 = (current_tol * current_tol) * bnorm2

        def cond_fun(state: Tuple[jnp.int32, Array, Array, Array, Array, Array, Array]) -> bool:
            it, x, r, z, p, rz, r2 = state
            return (it < maxiter) & (r2 > tol2)

        def body_fun(state: Tuple[jnp.int32, Array, Array, Array, Array, Array, Array]) -> Tuple[jnp.int32, Array, Array, Array, Array, Array, Array]:
            it, x, r, z, p, rz, r2 = state
            Ap = apply_A(p)
            if boundary_mask is not None: Ap = Ap * boundary_mask
            alpha = rz / (jnp.dot(p, Ap) + eps)
            x_new = x + alpha * p
            r_new = r - alpha * Ap
            z_new = apply_Minv(r_new, hierarchy)
            rz_new = jnp.dot(r_new, z_new)
            beta = rz_new / (rz + eps)
            p_new = z_new + beta * p
            r2_new = jnp.dot(r_new, r_new)
            return (it + 1, x_new, r_new, z_new, p_new, rz_new, r2_new)

        init = (jnp.int32(0), x, r, z, p, rz, r2)
        final_state = lax.while_loop(cond_fun, body_fun, init)
        it_final, x_final, _, _, _, _, r2_final = final_state
        return x_final, it_final, r2_final

    return jax.jit(solve, static_argnums=(3,))

def make_solve_U(
    geom: TetGeom,
    Js_lookup: Array,
    *,
    precond_type: PrecondType = 'jacobi',
    order: int = 3,
    chunk_elems: int = 200_000,
    cg_maxiter: int = 400,
    cg_tol: float = 1e-8,
    poisson_reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    enforce_zero_mean: Optional[bool] = None,
    boundary_mask: Optional[Array] = None,
    assembly: Assembly = 'scatter',
) -> Callable[[Array, Array, Optional[float], bool], Array | Tuple[Array, int, float]]:
    """Create a high-level function to solve the Poisson potential U.

    Orchestrates operator creation, preconditioning setup (including AMG on CPU),
    and PCG execution.

    Args:
        geom (TetGeom): Geometry container.
        Js_lookup (Array): Saturation polarization lookup table.
        precond_type (PrecondType, optional): Preconditioning type. 
            Defaults to 'jacobi'.
        order (int, optional): Chebyshev polynomial order. Defaults to 3.
        chunk_elems (int, optional): elements per loop chunk. Defaults to 200_000.
        cg_maxiter (int, optional): maximum PCG iterations. Defaults to 400.
        cg_tol (float, optional): PCG relative tolerance. Defaults to 1e-8.
        poisson_reg (float, optional): Tikhonov regularization. Defaults to 1e-12.
        grad_backend (GradBackend, optional): Strategy for shape function gradients.
            Defaults to 'stored_grad_phi'.
        enforce_zero_mean (Optional[bool], optional): Project solution to zero mean.
            Required for pure Neumann problems. Defaults to True if no boundary mask.
        boundary_mask (Optional[Array], optional): Dirichlet boundary mask.
            Defaults to None.
        assembly (Assembly, optional): Nodal assembly method. Defaults to 'scatter'.

    Returns:
        Callable: solve_U(m, x0, tol, return_info) -> U or (U, iterations, residual).
    """
    if enforce_zero_mean is None:
        enforce_zero_mean = (boundary_mask is None)
        
    apply_A, rhs_from_m, assemble_diag = make_poisson_ops(
        geom, Js_lookup, chunk_elems=chunk_elems, reg=poisson_reg,
        grad_backend=grad_backend, assembly=assembly, boundary_mask=boundary_mask,
    )

    if geom.x_nodes is not None:
        N = int(geom.x_nodes.shape[0])
    else:
        import numpy as np
        N = int(np.max(geom.conn)) + 1

    Mdiag = assemble_diag(N)
    l_max = 2.0
    apply_Minv_amg = None
    hierarchy_jax = None
    
    if precond_type == 'chebyshev':
        l_max = 1.1 * estimate_spectral_radius(apply_A, Mdiag, boundary_mask, N)
    
    elif precond_type in ['amg', 'amgcl']:
        print(f"Setting up AMG hierarchy on CPU (PyAMG, mode={precond_type})...")
        import pyamg
        from amg_utils import assemble_poisson_matrix_cpu, setup_amg_hierarchy, make_jax_amg_vcycle, make_jax_amgcl_vcycle
        import numpy as np
        
        if geom.grad_phi is not None:
            gp = np.array(geom.grad_phi)
        else:
            from loop import compute_grad_phi_from_JinvT
            gp = compute_grad_phi_from_JinvT(np.array(geom.JinvT))

        A_cpu = assemble_poisson_matrix_cpu(
            np.array(geom.conn), np.array(geom.volume), gp, 
            boundary_mask=np.array(boundary_mask) if boundary_mask is not None else None,
            reg=poisson_reg
        )
        
        ml = pyamg.smoothed_aggregation_solver(
            A_cpu, 
            strength='evolution',
            smooth='energy',
            max_levels=10,
            max_coarse=1000
        )

        print(f"AMG hierarchy has {len(ml.levels)} levels.")
        
        levels_jax = []
        for i in range(len(ml.levels)):
            level = ml.levels[i]
            from amg_utils import csr_to_jax_bCOO, compute_spai0_diagonal
            csr_A = level.A.tocsr()
            level_dict = {
                'A_sparse': csr_to_jax_bCOO(csr_A),
                'Mdiag': jnp.asarray(csr_A.diagonal()),
                'Mdiag_spai0': jnp.asarray(compute_spai0_diagonal(csr_A))
            }
            if i < len(ml.levels) - 1:
                level_dict['P'] = csr_to_jax_bCOO(level.P.tocsr())
                level_dict['R'] = csr_to_jax_bCOO(level.R.tocsr())
            else:
                level_dict['A_dense'] = jnp.asarray(csr_A.todense())
            levels_jax.append(level_dict)
            
        from amg_utils import AMGHierarchy
        hierarchy_jax = AMGHierarchy(levels_jax)

        def apply_A_masked(v: Array) -> Array:
            res = apply_A(v)
            if boundary_mask is not None: res = res * boundary_mask
            return res

        if precond_type == 'amgcl':
            apply_Minv_amg = make_jax_amgcl_vcycle(apply_A_masked)
        else:
            apply_Minv_amg = make_jax_amg_vcycle(apply_A_masked)

    solve_linear = make_pcg_solve(
        apply_A, Mdiag, precond_type=precond_type, apply_Minv_amg=apply_Minv_amg,
        order=order, maxiter=cg_maxiter, tol=cg_tol, boundary_mask=boundary_mask, l_max=l_max,
    )

    @partial(jax.jit, static_argnums=(3,))
    def solve_U(m: Array, x0: Array, tol: Optional[float] = None, return_info: bool = False) -> Array | Tuple[Array, int, float]:
        """Perform the Poisson solve for a given magnetization state m.

        Args:
            m (Array): Nodal unit magnetization vectors (N, 3).
            x0 (Array): Initial guess for the potential U (N,).
            tol (Optional[float], optional): PCG relative tolerance. 
                Defaults to the closure's cg_tol.
            return_info (bool, optional): If True, return (U, iterations, residual).
                Defaults to False.

        Returns:
            Array | Tuple[Array, int, float]: Potential U (N,) or solver info.
        """
        b = rhs_from_m(m)
        bnorm2 = jnp.vdot(b, b)
        
        # Choice: For open boundary problems (no Dirichlet mask), the Poisson 
        # equation is only solvable up to an additive constant (pure Neumann).
        # Projecting both b and x0 to zero mean removes the null-space component
        # and stabilizes the CG solver.
        if enforce_zero_mean:
            b = b - jnp.mean(b)
            x0 = x0 - jnp.mean(x0)
        
        U, it, r2 = solve_linear(b, x0, tol=tol, hierarchy=hierarchy_jax)
        
        if enforce_zero_mean: U = U - jnp.mean(U)
        if return_info:
            rel_res = jnp.sqrt(r2 / (bnorm2 + 1e-30))
            return U, it, rel_res
        return U

    return solve_U
