"""poisson_solve.py

Matrix-free Poisson operator and PCG solver with:
  - Jacobi preconditioner
  - Chebyshev polynomial preconditioner (accelerated Jacobi)
  - Warm start
  - Dirichlet boundary conditions (U=0) via masking

Author: generated by M365 Copilot
License: MIT
"""

from __future__ import annotations

from functools import partial
from typing import Callable, Optional, Literal

import jax
import jax.numpy as jnp
from jax import lax

from fem_utils import TetGeom, pad_geom_for_chunking, chunk_mask, assemble_scatter, assemble_segment_sum

Array = jnp.ndarray
GradBackend = Literal['stored_grad_phi', 'stored_JinvT', 'on_the_fly']
PrecondType = Literal['jacobi', 'chebyshev', 'amg']
Assembly = Literal['scatter', 'segment_sum']

_GRAD_HAT = jnp.array([
    [-1.0, -1.0, -1.0],
    [ 1.0,  0.0,  0.0],
    [ 0.0,  1.0,  0.0],
    [ 0.0,  0.0,  1.0],
], dtype=jnp.float64)


def _B_from_JinvT(JinvT_c: Array, dtype) -> Array:
    return jnp.einsum('eij,aj->eai', JinvT_c.astype(dtype), _GRAD_HAT.astype(dtype))


def _compute_JinvT_from_coords(x_e: Array, dtype) -> Array:
    x0 = x_e[:, 0, :]
    J = jnp.stack([x_e[:, 1, :] - x0, x_e[:, 2, :] - x0, x_e[:, 3, :] - x0], axis=2)
    invJ = jnp.linalg.inv(J.astype(dtype))
    return jnp.swapaxes(invJ, 1, 2)


def _make_B_getter(geom_p: TetGeom, chunk_elems: int, grad_backend: GradBackend):
    if grad_backend == 'stored_grad_phi':
        if geom_p.grad_phi is None:
            raise ValueError('stored_grad_phi requires geom.grad_phi')
        grad_phi = geom_p.grad_phi
        def _get_B(conn_c: Array, s: int, dtype) -> Array:
            return lax.dynamic_slice(grad_phi, (s,0,0), (chunk_elems,4,3)).astype(dtype)
        return _get_B

    if grad_backend == 'stored_JinvT':
        if geom_p.JinvT is None:
            raise ValueError('stored_JinvT requires geom.JinvT')
        JinvT = geom_p.JinvT
        def _get_B(conn_c: Array, s: int, dtype) -> Array:
            JinvT_c = lax.dynamic_slice(JinvT, (s,0,0), (chunk_elems,3,3)).astype(dtype)
            return _B_from_JinvT(JinvT_c, dtype)
        return _get_B

    if geom_p.x_nodes is None:
        raise ValueError('on_the_fly requires geom.x_nodes')
    x_nodes = geom_p.x_nodes
    def _get_B(conn_c: Array, s: int, dtype) -> Array:
        x_e = x_nodes[conn_c].astype(dtype)
        JinvT_c = _compute_JinvT_from_coords(x_e, dtype)
        return _B_from_JinvT(JinvT_c, dtype)
    return _get_B


def make_poisson_ops(
    geom: TetGeom,
    Js_lookup: Array,
    *,
    chunk_elems: int = 200_000,
    reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    assembly: Assembly = 'scatter',
    boundary_mask: Optional[Array] = None,
):
    """Return (apply_A, rhs_from_m, assemble_diag)."""

    geom_p, E_orig = pad_geom_for_chunking(geom, chunk_elems)
    conn, Ve, mat_id = geom_p.conn, geom_p.volume, geom_p.mat_id
    Js_lookup = jnp.asarray(Js_lookup)

    E_pad = int(conn.shape[0])
    n_chunks = E_pad // chunk_elems
    
    if geom_p.x_nodes is not None:
        N = int(geom_p.x_nodes.shape[0])
    else:
        import numpy as np
        N = int(np.max(geom.conn)) + 1

    _get_B = _make_B_getter(geom_p, chunk_elems, grad_backend)

    def apply_A(U: Array) -> Array:
        dtype = U.dtype
        def body(i, y_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            U_e = U[conn_c]
            # Fused einsum to compute node contributions in one step
            dot_term = jnp.einsum('eak,ebk,eb->ea', B_c, B_c, U_e)
            contrib = Ve_c[:, None] * dot_term
            if assembly == 'scatter':
                return assemble_scatter(y_acc, conn_c, contrib)
            else:
                return y_acc + assemble_segment_sum(N, conn_c, contrib, dtype)
        y0 = jnp.zeros_like(U)
        y = lax.fori_loop(0, n_chunks, body, y0)
        y = y + jnp.asarray(reg, dtype=dtype) * U
        if boundary_mask is not None:
            y = y * boundary_mask
        return y

    def rhs_from_m(m: Array) -> Array:
        dtype = m.dtype
        def body(i, b_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            mat_c = lax.dynamic_slice(mat_id, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            Js_c = Js_lookup[mat_c - 1].astype(dtype)
            m_e = m[conn_c]
            # Fused einsum for RHS assembly
            dot_term = 0.25 * jnp.einsum('eak,ebk->ea', B_c, m_e)
            contrib = (Ve_c * Js_c)[:, None] * dot_term
            if assembly == 'scatter':
                return assemble_scatter(b_acc, conn_c, contrib)
            else:
                return b_acc + assemble_segment_sum(N, conn_c, contrib, dtype)
        b0 = jnp.zeros((m.shape[0],), dtype=dtype)
        return lax.fori_loop(0, n_chunks, body, b0)

    def assemble_diag(N: int) -> Array:
        dtype = jnp.float64
        def body(i, d_acc):
            s = i * chunk_elems
            conn_c = lax.dynamic_slice(conn, (s,0), (chunk_elems,4))
            Ve_c = lax.dynamic_slice(Ve, (s,), (chunk_elems,))
            B_c = _get_B(conn_c, s, dtype)
            local = Ve_c[:, None] * jnp.sum(B_c * B_c, axis=2)
            if assembly == 'scatter':
                return assemble_scatter(d_acc, conn_c, local)
            else:
                return d_acc + assemble_segment_sum(N, conn_c, local, dtype)
        d0 = jnp.zeros((N,), dtype=dtype)
        d = lax.fori_loop(0, n_chunks, body, d0)
        return d + jnp.asarray(reg, dtype=dtype)

    return jax.jit(apply_A), jax.jit(rhs_from_m), jax.jit(assemble_diag, static_argnums=(0,))


def estimate_spectral_radius(apply_A: Callable[[Array], Array], Mdiag: Array, boundary_mask: Optional[Array], N: int, n_iters: int = 15) -> float:
    """Power method to estimate max eigenvalue of M^-1 A."""
    key = jax.random.PRNGKey(42)
    v = jax.random.normal(key, (N,), dtype=jnp.float64)
    if boundary_mask is not None:
        v = v * boundary_mask
    
    def body(i, v_curr):
        v_next = (apply_A(v_curr) / (Mdiag + 1e-30))
        if boundary_mask is not None:
            v_next = v_next * boundary_mask
        return v_next / (jnp.linalg.norm(v_next) + 1e-30)
    
    v_final = lax.fori_loop(0, n_iters, body, v)
    lam_max = jnp.vdot(v_final, (apply_A(v_final) / (Mdiag + 1e-30)))
    return float(lam_max)


def make_pcg_solve(
    apply_A: Callable[[Array], Array],
    Mdiag: Array,
    *,
    precond_type: PrecondType = 'jacobi',
    apply_Minv_amg: Optional[Callable[[Array], Array]] = None,
    order: int = 3,
    maxiter: int = 500,
    tol: float = 1e-8,
    boundary_mask: Optional[Array] = None,
    l_max: float = 2.0,
):
    default_tol = float(tol)

    def apply_Minv(r: Array) -> Array:
        if precond_type == 'amg' and apply_Minv_amg is not None:
            return apply_Minv_amg(r)
            
        dtype = r.dtype
        eps = jnp.asarray(1e-30, dtype=dtype)
        
        # Initial Jacobi guess
        z0 = r / (Mdiag.astype(dtype) + eps)
        
        if precond_type == 'chebyshev' and order > 0:
            # Chebyshev polynomial step using 3-term recurrence
            # Target range: [lam_min, lam_max]
            lam_max = l_max
            lam_min = lam_max / 10.0 
            
            d = (lam_max + lam_min) / 2.0
            c = (lam_max - lam_min) / 2.0
            
            # k = 0
            alpha = 1.0 / d
            y = alpha * z0
            y_prev = jnp.zeros_like(y)
            
            # We use a Python loop for the recurrence to allow unrolling/JIT optimization
            # for small fixed orders.
            curr_alpha = alpha
            for k in range(1, order):
                res = r - apply_A(y)
                z = res / (Mdiag.astype(dtype) + eps)
                
                beta = (c * curr_alpha / 2.0)**2
                curr_alpha = 1.0 / (d - beta)
                
                y_next = y + curr_alpha * z + curr_alpha * beta * (y - y_prev)
                y_prev = y
                y = y_next
            
            z = y
        else:
            z = z0
        
        if boundary_mask is not None:
            z = z * boundary_mask
        return z

    def solve(b: Array, x0: Array, tol: Optional[float] = None) -> Array:
        dtype = b.dtype
        eps = jnp.asarray(1e-30, dtype=dtype)
        # Use provided tol or fallback to default
        current_tol = jnp.asarray(tol if tol is not None else default_tol, dtype=dtype)
        
        if boundary_mask is not None:
            b = b * boundary_mask
            x = x0 * boundary_mask
        else:
            x = x0

        r = b - apply_A(x)
        z = apply_Minv(r)
        p = z
        rz = jnp.dot(r, z)
        bnorm2 = jnp.dot(b, b)

        def cond_fun(state):
            it, x, r, z, p, rz = state
            return jnp.logical_and(it < maxiter, rz > (current_tol * current_tol) * bnorm2 + jnp.asarray(0.0, dtype))

        def body_fun(state):
            it, x, r, z, p, rz = state
            Ap = apply_A(p)
            alpha = rz / (jnp.dot(p, Ap) + eps)
            
            # Fuse x and r updates
            x_new = x + alpha * p
            r_new = r - alpha * Ap
            
            z_new = apply_Minv(r_new)
            rz_new = jnp.dot(r_new, z_new)
            beta = rz_new / (rz + eps)
            
            # Fuse p update
            p_new = z_new + beta * p
            return (it + 1, x_new, r_new, z_new, p_new, rz_new)

        init = (jnp.int32(0), x, r, z, p, rz)
        _, x, _, _, _, _ = lax.while_loop(cond_fun, body_fun, init)
        return x

    return jax.jit(solve)


def make_solve_U(
    geom: TetGeom,
    Js_lookup: Array,
    *,
    precond_type: PrecondType = 'jacobi',
    order: int = 3,
    chunk_elems: int = 200_000,
    cg_maxiter: int = 400,
    cg_tol: float = 1e-8,
    poisson_reg: float = 1e-12,
    grad_backend: GradBackend = 'stored_grad_phi',
    enforce_zero_mean: bool = True,
    boundary_mask: Optional[Array] = None,
    assembly: Assembly = 'scatter',
):
    apply_A, rhs_from_m, assemble_diag = make_poisson_ops(
        geom,
        Js_lookup,
        chunk_elems=chunk_elems,
        reg=poisson_reg,
        grad_backend=grad_backend,
        assembly=assembly,
        boundary_mask=boundary_mask,
    )

    if geom.x_nodes is not None:
        N = int(geom.x_nodes.shape[0])
    else:
        import numpy as np
        N = int(np.max(geom.conn)) + 1

    Mdiag = assemble_diag(N)
    
    l_max = 2.0
    apply_Minv_amg = None
    
    if precond_type == 'chebyshev':
        l_max = 1.1 * estimate_spectral_radius(apply_A, Mdiag, boundary_mask, N)
    
    elif precond_type == 'amg':
        # Setup AMG on CPU
        print("Setting up AMG hierarchy on CPU (PyAMG)...")
        from amg_utils import assemble_poisson_matrix_cpu, setup_amg_hierarchy, csr_to_jax_bCOO, make_jax_amg_vcycle
        import numpy as np
        
        # We need the full grad_phi for assembly. If it's padded, we slice it.
        # For simplicity, we assume grad_phi is available in geom.
        A_cpu = assemble_poisson_matrix_cpu(
            np.array(geom.conn), 
            np.array(geom.volume), 
            np.array(geom.grad_phi), 
            boundary_mask=np.array(boundary_mask) if boundary_mask is not None else None,
            reg=poisson_reg
        )
        
        hierarchy_cpu = setup_amg_hierarchy(A_cpu)
        
        # Move hierarchy to JAX
        hierarchy_jax = []
        for i, level in enumerate(hierarchy_cpu):
            level_dict = {
                'P': csr_to_jax_bCOO(level['P']),
                'R': csr_to_jax_bCOO(level['R']),
                'A_sparse': csr_to_jax_bCOO(level['A']),
                'Mdiag': jnp.asarray(level['A'].diagonal())
            }
            # For the coarsest level, also store as dense matrix for exact solve
            if i == len(hierarchy_cpu) - 1:
                level_dict['A_dense'] = jnp.asarray(level['A'].todense())
            
            hierarchy_jax.append(level_dict)
            
        apply_Minv_amg = make_jax_amg_vcycle(apply_A, Mdiag, hierarchy_jax)

    solve_linear = make_pcg_solve(
        apply_A,
        Mdiag,
        precond_type=precond_type,
        apply_Minv_amg=apply_Minv_amg,
        order=order,
        maxiter=cg_maxiter,
        tol=cg_tol,
        boundary_mask=boundary_mask,
        l_max=l_max,
    )

    @jax.jit
    def solve_U(m: Array, x0: Array, tol: Optional[float] = None) -> Array:
        b = rhs_from_m(m)
        if enforce_zero_mean:
            b = b - jnp.mean(b)
            x0 = x0 - jnp.mean(x0)
        U = solve_linear(b, x0, tol=tol)
        if enforce_zero_mean:
            U = U - jnp.mean(U)
        return U

    return solve_U
